metadata-classic/objects/Arbitration__c.object
<CustomObject>
    <description>Custom object to store information for the arbitration (e.g., FairClaims) activities related to a marketplace trust and safety incident.</description>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the MI Incident</description>
        <label>Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>IncidentArbitrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Arbitration</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Arbitration</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentArbitrationControllerTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-08-18   Mendel Guillaume       Created
========+============+=================+===============================================*/

@IsTest
private class IncidentArbitrationControllerTest
{
	@TestSetup
	static void createData()
	{
		Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
		insert customer;

		Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
		insert pro;

		MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id);
		insert incident;
	}

	static testMethod void testSave()
	{
		MIIncident__c incident = [SELECT Id FROM MIIncident__c];
		Arbitration__c arb = new Arbitration__c(Incident__c = incident.Id, Name = 'Request');

		System.assertEquals('Success', IncidentArbitrationController.save(arb));
		System.assertNotEquals(null, arb.Id);
	}

	static testMethod void testGetStatuses()
	{
		System.assertNotEquals(0, IncidentArbitrationController.getStatuses().size());
	}

	static testMethod void testGetDisputeChannels()
	{
		System.assertNotEquals(0, IncidentArbitrationController.getDisputeChannels().size());
	}

	static testMethod void testGetArbitration()
	{
		MIIncident__c incident = [SELECT Id FROM MIIncident__c];
		Arbitration__c arb = new Arbitration__c(Incident__c = incident.Id, Name = 'Request');
		insert arb;

		System.assertEquals(arb.Id, IncidentArbitrationController.getArbitration(incident.Id).Id);
	}

	static testMethod void testGetIncident()
	{
		MIIncident__c incident = [SELECT Id FROM MIIncident__c];

		System.assertEquals(incident.Id, IncidentArbitrationController.getIncident(incident.Id).Id);
	}
}