metadata-classic/objects/Arbitration__c.object
<CustomObject>
    <description>Custom object to store information for the arbitration (e.g., FairClaims) activities related to a marketplace trust and safety incident.</description>
    <fields>
        <fullName>DateSubmitted__c</fullName>
        <description>The date the pro/customer claim was filed with FairClaims.</description>
        <label>Date Submitted</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the MI Incident</description>
        <label>Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>IncidentArbitrations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Claimant signed up</fullName>
                </value>
                <value>
                    <fullName>Respondent signed up</fullName>
                </value>
                <value>
                    <fullName>Claimant did not sign up</fullName>
                </value>
                <value>
                    <fullName>Respondent did not sign up</fullName>
                </value>
                <value>
                    <fullName>Decision made</fullName>
                </value>
                <value>
                    <fullName>Settlement reached</fullName>
                </value>
                <value>
                    <fullName>Payment made</fullName>
                </value>
                <value>
                    <fullName>Payment overdue</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>arbitrator_decision__c</fullName>
        <label>Arbitrator Decision</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>brief_description_of_dispute__c</fullName>
        <label>Brief Description of Dispute</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>claimant_email__c</fullName>
        <label>Claimant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>claimant_first_name__c</fullName>
        <label>Claimant First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>claimant_last_name__c</fullName>
        <label>Claimant Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>claimant_phone__c</fullName>
        <label>Claimant Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>dispute_amount__c</fullName>
        <label>Dispute Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>dispute_channels__c</fullName>
        <label>Dispute Channels</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>arbitration_with_chat</fullName>
                </value>
                <value>
                    <fullName>chat_only</fullName>
                </value>
                <value>
                    <fullName>arbitration_only</fullName>
                    <isActive>false</isActive>
                    <label>arbitration_only</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>dispute_code__c</fullName>
        <externalId>true</externalId>
        <label>Dispute Code</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>hearing_date__c</fullName>
        <label>Hearing Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>respondent_email__c</fullName>
        <label>Respondent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>respondent_first_name__c</fullName>
        <label>Respondent First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>respondent_last_name__c</fullName>
        <label>Respondent Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>respondent_phone__c</fullName>
        <label>Respondent Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>support_team_member_email__c</fullName>
        <label>Support Team Member Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>support_team_member_name__c</fullName>
        <label>Support Team Member Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Arbitration</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Arbitration</pluralLabel>
    <recordTypes>
        <fullName>Arbitration</fullName>
        <active>true</active>
        <description>Record type used to manage arbitration (e.g., Fairclaims) solutions.</description>
        <label>Arbitration</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>AmountInDispute__c</fullName>
        <description>Amount that the customer is disputing.</description>
        <inlineHelpText>This is the amount that the customer is disputing</inlineHelpText>
        <label>Amount in Dispute</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the contact record for the customer associated with the incident.</description>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerEmail__c</fullName>
        <description>Email address of the related customer; populated via external data query when incident is created, but editable on the MI Incident for communication purposes - when changed on MI Incident it will not update the customer&apos;s account or Admin.</description>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CustomerPhone__c</fullName>
        <description>The phone number of the related customer; populated on incident creation via external data source, however editable by MI agent during incident resolution; if edited on incident it does not update the customer&apos;s account phone number in admin.</description>
        <label>Customer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>DescriptionOfDispute__c</fullName>
        <description>A brief description of the dispute between the pro and customer.</description>
        <label>Description of Dispute</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>IncidentRef__c</fullName>
        <description>Formula field to extract the &quot;MI-&quot; from the Incident number, used in 3rd party external integrations.</description>
        <formula>SUBSTITUTE(IncidentNumber__c,&quot;MI-&quot;,&quot;&quot;)</formula>
        <label>Incident Ref</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProEmail__c</fullName>
        <description>Email address of the pro; populated via external data query when incident is created, but editable on the MI Incident for communication purposes - when changed on MI Incident it will not update the Pro&apos;s account or Admin.</description>
        <label>Pro Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ProPhone__c</fullName>
        <description>The phone number of the related pro; populated on incident creation via external data source, however editable by MI agent during incident resolution; if edited on incident it does not update the pro&apos;s account phone number in admin.</description>
        <label>Pro Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/IncidentArbitrationController.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-08-18   Mendel Guillaume       Created
========+============+=================+===============================================*/

public with sharing class IncidentArbitrationController
{
	@AuraEnabled 
	public static List<IncidentChargeCardManagerController.Option> getStatuses()
	{
		List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
		List<Schema.PicklistEntry> ples = Arbitration__c.Status__c.getDescribe().getPicklistValues();

		for(Schema.PicklistEntry p : ples)
		{
			options.add(new IncidentChargeCardManagerController.Option(p.getLabel(), p.getValue()));
		}

		return options;
	}

	@AuraEnabled
	public static List<IncidentChargeCardManagerController.Option> getDisputeChannels()
	{
		List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
		List<Schema.PicklistEntry> ples = Arbitration__c.dispute_channels__c.getDescribe().getPicklistValues();

		for(Schema.PicklistEntry p : ples)
		{
			options.add(new IncidentChargeCardManagerController.Option(p.getLabel(), p.getValue()));
		}

		return options;
	}

	@AuraEnabled
	public static String save(Arbitration__c arbitration)
	{
		String response = 'Success';
		Savepoint sp = null;
		MIIncident__c incident = null;

		try
		{
			//make sure a new arbitration is not created
			if(arbitration.Id == null)
			{
				Arbitration__c temp = getArbitration(arbitration.Incident__c);

				if(temp.Id != null)
				{
					arbitration.Id = temp.Id;
				}
			}

			upsert arbitration;
			
			incident = getIncident(arbitration.Incident__c);

			if(arbitration.brief_description_of_dispute__c != incident.DescriptionOfDispute__c)
			{
				update new MIIncident__c(Id = incident.Id, DescriptionOfDispute__c = arbitration.brief_description_of_dispute__c);
			}
		}
		catch(Exception ex)
		{
			if(sp != null)
			{
				Database.rollback(sp);
			}

			response = ex.getMessage() + ' - ' + ex.getStackTraceString();
		}

		return response;
	}

	@AuraEnabled
	public static Arbitration__c getArbitration(String incidentId)
	{
		Arbitration__c arbitration = new Arbitration__c();
		List<Arbitration__c> arbs = [SELECT Id, Name, Status__c, dispute_channels__c, dispute_amount__c, dispute_code__c,
										hearing_date__c, arbitrator_decision__c, support_team_member_email__c, support_team_member_name__c,
										claimant_first_name__c, claimant_last_name__c, claimant_phone__c, claimant_email__c,
										respondent_first_name__c, respondent_last_name__c, respondent_phone__c, respondent_email__c,
										brief_description_of_dispute__c, Incident__c, DateSubmitted__c
									FROM Arbitration__c
									WHERE Incident__c =: incidentId
									ORDER BY LastModifiedDate DESC];

		if(!arbs.isEmpty())
		{
			arbitration = arbs[0];
		}
		else
		{
			arbitration.DateSubmitted__c = Date.today();
		}

		return arbitration;
	}

	@AuraEnabled
	public static MIIncident__c getIncident(String incidentId)
	{
		return [SELECT Id, Name, IncidentRef__c, AmountInDispute__c, OwnerId, Owner.Name, Owner.Email, CustomerAccount__c,
					CustomerAccount__r.usr_first_name__c, CustomerAccount__r.usr_last_name__c, CustomerPhone__c,
					CustomerEmail__c, ProAccount__r.usr_first_name__c, ProAccount__c, ProAccount__r.usr_last_name__c, ProPhone__c,
					ProEmail__c, DescriptionOfDispute__c, CustomerContact__c, CustomerContact__r.Name
				FROM MIIncident__c
				WHERE Id =: incidentId];

	}
}