metadata-classic/objects/BackgroundCheck__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>BGCReportId__c</fullName>
        <description>The ID of the external background check report.</description>
        <externalId>true</externalId>
        <label>BGC Report Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BackgroundCheck__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Background Check</label>
        <referenceTo>BackgroundCheck__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>L1 category issue - this is where the general area goes.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account / Profile</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Customer Payments</fullName>
                </value>
                <value>
                    <fullName>Delete Account</fullName>
                </value>
                <value>
                    <fullName>Getting Started</fullName>
                </value>
                <value>
                    <fullName>Marketplace Integrity</fullName>
                </value>
                <value>
                    <fullName>Notifications</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Pricing and Payments</fullName>
                </value>
                <value>
                    <fullName>Instant Match</fullName>
                </value>
                <value>
                    <fullName>Quotes</fullName>
                </value>
                <value>
                    <fullName>Quoting Service</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>Requests</fullName>
                </value>
                <value>
                    <fullName>Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsTestData__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox marked true if case is test data.</description>
        <label>Is Test Data</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubCategory__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>App pricing / purchase</fullName>
                </value>
                <value>
                    <fullName>Background check</fullName>
                </value>
                <value>
                    <fullName>Background check (clear)</fullName>
                </value>
                <value>
                    <fullName>Background check (mismatch)</fullName>
                </value>
                <value>
                    <fullName>Background check (not clear)</fullName>
                </value>
                <value>
                    <fullName>Called for customer</fullName>
                </value>
                <value>
                    <fullName>Called for pro</fullName>
                </value>
                <value>
                    <fullName>Called for specific employee</fullName>
                </value>
                <value>
                    <fullName>Canceled request</fullName>
                </value>
                <value>
                    <fullName>Cash refund</fullName>
                </value>
                <value>
                    <fullName>Certification agreement</fullName>
                </value>
                <value>
                    <fullName>Churn</fullName>
                </value>
                <value>
                    <fullName>Competitive report</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Concerning review</fullName>
                </value>
                <value>
                    <fullName>Connection issues - didn&apos;t talk</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - Call back needed</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - CC not provided</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - PA Live</fullName>
                </value>
                <value>
                    <fullName>Customer / other</fullName>
                </value>
                <value>
                    <fullName>Customer contact</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Disconnected (pro or customer)</fullName>
                </value>
                <value>
                    <fullName>Disconnected (specialist)</fullName>
                </value>
                <value>
                    <fullName>Dispute</fullName>
                </value>
                <value>
                    <fullName>DMCA/Copyright</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Duplicate request</fullName>
                </value>
                <value>
                    <fullName>Dynamic pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/CheckerAPISettings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>BaseURL__c</fullName>
        <label>BaseURL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>1</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Checker API Settings</label>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/BackgroundCheckTriggerHandlerTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:
------------
Version    Date     Author            Description
=======+===========+=================+================================================
1.0     04-12-2017  Scott Purcell      Created
=======+===========+=================+================================================
*/
@isTest
private class BackgroundCheckTriggerHandlerTest {
	
	@isTest static void testAddBCheckToCase() {
        CheckerAPISettings__c cs = new CheckerAPISettings__c();
            cs.Name='default';
            cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
            cs.Password__c = '1';
            cs.UserName__c = 'user' ;
            //cs.Other fields values
            insert cs;

        User testUser = [SELECT id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive=true LIMIT 1];
        System.runAs(testUser) {
            Id caseRTId=Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer Support').getRecordTypeId();
            Id accountRTId=Account.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            Account a = new Account(Name='Chester Tester',RecordTypeId=accountRTId,usr_email__c = 'test@test.com');
            insert a;
            Case cas = new Case(Status='New',RecordTypeId=caseRTId,Origin='Phone',AccountId=a.Id,IsTestData__c=false,Category__c='Phone',SubCategory__c='Trigger Testing',SuppliedEmail='test@test.com',Subject ='CONSIDER',Description ='The background check for Andrea Deemaine Jewell completed with a status CONSIDER.You can review the detailed report at: https://dashboard.checkr.com/reports/19f490e9f89cd5297979d6bd If you have any questions about the results, please reply to this email.You can update your email notification settings here:https://dashboard.checkr.com/user/settings-- The Checkr team');
            
            insert cas;
            Test.startTest();
            cas.BGCReportId__c = '1234';
            update cas;

          
            BackgroundCheck__c bc = [Select Id,CandidateId__c From BackgroundCheck__c];
            bc.CandidateId__c = '123456';
            update bc;
            bc.AdverseItems__c = 'advers item 1,advers item2';
            update bc;
            Test.stopTest();
            system.assert(bc != null);
            Case c = [Select Id,BackgroundCheck__c From Case];
            system.assertEquals(c.BackgroundCheck__c , bc.Id);
        }
    } 
	
	
	
}