metadata-classic/objects/becquerel_tt_user_for_tack__x.object
<CustomObject>
    <description>becquerel__tt_user_for_tack</description>
    <externalDataSource>Becquerel</externalDataSource>
    <externalName>becquerel__tt_user_for_tack</externalName>
    <fields>
        <fullName>user_pk_id__c</fullName>
        <description>user_pk_id</description>
        <externalDeveloperName>user_pk_id</externalDeveloperName>
        <label>user_pk_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>usr_email__c</fullName>
        <description>usr_email</description>
        <externalDeveloperName>usr_email</externalDeveloperName>
        <label>usr_email</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>usr_user_id</description>
        <externalDeveloperName>usr_user_id</externalDeveloperName>
        <label>usr_user_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>becquerel__tt_user_for_tack</label>
    <pluralLabel>becquerel__tt_user_for_tack</pluralLabel>
</CustomObject>

metadata-classic/classes/ScheduledGetTTUsersTest.cls
/*
   Copyright (c) 2017 Thumbtack, All rights reserved.

Change List:
------------
Version   Date         Author           Description
========+============+=================+================================================
1.0       11/8/17      paulcoleman          Created
========+============+=================+===============================================*/
@IsTest
public with sharing class ScheduledGetTTUsersTest
{
    /**
       * @author Paul Coleman
       * @date 2017-11-08
       * @description Simulate running a remote Becquerel External Object sync.
       */
    @IsTest
    private static void testBeckySyncForUsers() {

        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            becquerel_tt_user_for_tack__x tackUser = BecquerelUtility.createTestExternalUsers( 1, true )[0];
            Account testAccount = TestUtilities.CORE_ACCOUNT.clone();
            testAccount.usr_user_id__c = tackUser.usr_user_id__c;
            testAccount.user_pk_id__c = String.valueOf( tackUser.user_pk_id__c );
            testAccount.usr_email__c = tackUser.usr_email__c;
            testAccount.LastSyncedWithDataPlatform__c = Datetime.now(); //prevent normal becky trigger-based sync
            insert testAccount;

            Test.startTest();

                testAccount.usr_email__c = 'somethingtotallybogus@testingbeckysync.com';
                update testAccount;
                new ScheduledGetTTUsers().execute( (SchedulableContext)NULL );

            Test.stopTest();

            // No Assertion because impossible to meet Account.CreateDate threshold job < 24 hours but greater than 6 hourse old

        } //end RunAs
    }
}