metadata-classic/objects/becquerel_mi_incident_project_data__x.object
<CustomObject>
    <description>becquerel__mi_incident_project_data</description>
    <externalDataSource>Becquerel</externalDataSource>
    <externalName>becquerel__mi_incident_project_data</externalName>
    <fields>
        <fullName>bid_id__c</fullName>
        <description>bid_id</description>
        <externalDeveloperName>bid_id</externalDeveloperName>
        <label>bid_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>customer_is_disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>customer_is_disabled</description>
        <externalDeveloperName>customer_is_disabled</externalDeveloperName>
        <label>customer_is_disabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>pro_is_disabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>pro_is_disabled</description>
        <externalDeveloperName>pro_is_disabled</externalDeveloperName>
        <label>pro_is_disabled</label>
        <type>Checkbox</type>
    </fields>
    <label>becquerel__mi_incident_project_data</label>
    <pluralLabel>becquerel__mi_incident_project_data</pluralLabel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>MICategory__c</fullName>
        <description>Marketplace Integrity Incident categories.</description>
        <label>MI Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concern about user</fullName>
                </value>
                <value>
                    <fullName>Deposit no show</fullName>
                </value>
                <value>
                    <fullName>Payment issues</fullName>
                </value>
                <value>
                    <fullName>Physical harm / Inappropriate contact</fullName>
                </value>
                <value>
                    <fullName>Property damage</fullName>
                </value>
                <value>
                    <fullName>Theft</fullName>
                </value>
                <value>
                    <fullName>Unprofessional behavior</fullName>
                </value>
                <value>
                    <fullName>Unsatisfactory work</fullName>
                </value>
                <value>
                    <fullName>Work not complete</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MISubcategory__c</fullName>
        <description>Marketplace Integrity Incident Subcategories.</description>
        <label>MI Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MICategory__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Charged Unfairly</fullName>
                </value>
                <value>
                    <fullName>Check or payment scam</fullName>
                </value>
                <value>
                    <fullName>Criminal history</fullName>
                </value>
                <value>
                    <fullName>Fraudulent charges</fullName>
                </value>
                <value>
                    <fullName>Harassment</fullName>
                </value>
                <value>
                    <fullName>Licensing concerns</fullName>
                </value>
                <value>
                    <fullName>Threat or intimidation</fullName>
                </value>
                <value>
                    <fullName>Unprofessional communication</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bid_id__c</fullName>
        <description>External bid/quote ID from the the TT database.</description>
        <externalId>true</externalId>
        <label>bid_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentManagerController.cls
public class IncidentManagerController {
	
	@AuraEnabled
	public static MIIncident__c getIncident(Id incidentId) {

		MIIncident__c result;
		if (incidentId != null) {

			result = (MIIncident__c) Database.query(
				'Select ' + String.join(MIUtility.miIncidentFields, ', ') + ' From MIIncident__c '
				+ 'Where Id = :incidentId '
			);

		}
		return result;

	}

	@AuraEnabled
	public static List<IncidentChargeCardManagerController.Option> getCategorySubs(string category)
	{
		List<String> dependencies = UtilityDependentPicklist.GetDependentOptions('MIIncident__c', 'MICategory__c', 'MISubcategory__c', category);
		List<IncidentChargeCardManagerController.Option> opts = new List<IncidentChargeCardManagerController.Option>();


		for (String d : dependencies)
		{
			opts.add(new IncidentChargeCardManagerController.Option(d, d));
		}

		return opts;
	}

	@AuraEnabled
	public static becquerel_mi_incident_project_data__x getIncidentProjectData(Integer bidId)
	{
		becquerel_mi_incident_project_data__x ipd = null;
		List<becquerel_mi_incident_project_data__x> ipds = [SELECT bid_id__c, customer_is_disabled__c, pro_is_disabled__c
						FROM becquerel_mi_incident_project_data__x WHERE bid_id__c = :bidId];

		if(!ipds.isEmpty())
		{
			ipd = ipds[0];
		}

		return ipd;
	}

}