metadata-classic/objects/becquerel_qs_bid_bids__x.object
<CustomObject>
    <description>becquerel__qs_bid_bids</description>
    <externalDataSource>Becquerel</externalDataSource>
    <externalName>becquerel__qs_bid_bids</externalName>
    <fields>
        <fullName>bid_bid_id__c</fullName>
        <description>bid_bid_id</description>
        <externalDeveloperName>bid_bid_id</externalDeveloperName>
        <label>bid_bid_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>becquerel__qs_bid_bids</label>
    <pluralLabel>becquerel__qs_bid_bids</pluralLabel>
</CustomObject>

metadata-classic/objects/Quote__c.object
<CustomObject>
</CustomObject>

metadata-classic/classes/ScheduledGetQuoteTest.cls
/*

   Copyright (c) 2017 Thumbtack. All rights reserved.

Change List:
------------
Version      Date          Author            Description
========+============+=================+================================================
1.0       04/04/2017     Scott Purcell          Created
2.0       10/20/1027   Paul Coleman      Refactored for new Queueables
========+============+=================+===============================================*/
@isTest
private class ScheduledGetQuoteTest {

    /**
    * @author Paul Coleman
    * @date 2017-10-17
    * @description Simulate running a remote Becquerel External Object sync.
    */
    @IsTest
    private static void testBeckySyncForQuotes() {

        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            becquerel_qs_bid_bids__x bid = BecquerelUtility.createTestExternalBids(1)[0];
            Quote__c quote = new Quote__c( Name = 'Bogus Name', bid_bid_id__c = bid.bid_bid_id__c );
            insert quote;

            Test.startTest();

                new ScheduledGetQuote().execute(NULL);

            Test.stopTest();

            System.assertEquals( String.valueOf( bid.bid_bid_id__c ), [SELECT Name FROM Quote__c WHERE Id = :quote.Id LIMIT 1].Name, 'ScheduledGetQuote sync did not create Bid => Quote parity on bid_bid_id__c => Name' );


        } //end RunAs
    }
	
}