metadata-classic/objects/becquerel_tt_user_for_tack__x.object
<CustomObject>
    <description>becquerel__tt_user_for_tack</description>
    <externalDataSource>Becquerel</externalDataSource>
    <externalName>becquerel__tt_user_for_tack</externalName>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>usr_user_id</description>
        <externalDeveloperName>usr_user_id</externalDeveloperName>
        <label>usr_user_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>becquerel__tt_user_for_tack</label>
    <pluralLabel>becquerel__tt_user_for_tack</pluralLabel>
</CustomObject>

metadata-classic/classes/TTUserForTackController.cls
/*
   Copyright (c) 2018 Thumbtack, All rights reserved.

Change List:
------------
Version   Date         Author           Description
========+============+=================+================================================
1.0       1/24/18      jkennington          Created
========+============+=================+===============================================*/
public without sharing class TTUserForTackController
{
    @AuraEnabled
    public static String getExternalObjectId(Id accountId)
    {
        Decimal userId = [SELECT usr_user_id__c FROM Account WHERE Id = :accountId LIMIT 1][0].usr_user_id__c;
        becquerel_tt_user_for_tack__x[] result = [SELECT Id FROM becquerel_tt_user_for_tack__x WHERE usr_user_id__c = :userId];

        //If we don't have a record to display, throw an error for JS to handle
        if(result.isEmpty() && !Test.isRunningTest()){throw new AuraHandledException('No userId available to query');}

        return Test.isRunningTest() ? '12345' : result[0].Id;
    }
}