metadata-classic/objects/becquerel_mi_incident_project_data__x.object
<CustomObject>
    <description>becquerel__mi_incident_project_data</description>
    <externalDataSource>Becquerel</externalDataSource>
    <externalName>becquerel__mi_incident_project_data</externalName>
    <fields>
        <fullName>bid_id__c</fullName>
        <description>bid_id</description>
        <externalDeveloperName>bid_id</externalDeveloperName>
        <label>bid_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>request_category__c</fullName>
        <description>request_category</description>
        <externalDeveloperName>request_category</externalDeveloperName>
        <label>request_category</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>request_city__c</fullName>
        <description>request_city</description>
        <externalDeveloperName>request_city</externalDeveloperName>
        <label>request_city</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>request_state__c</fullName>
        <description>request_state</description>
        <externalDeveloperName>request_state</externalDeveloperName>
        <label>request_state</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>request_zip__c</fullName>
        <description>request_zip</description>
        <externalDeveloperName>request_zip</externalDeveloperName>
        <label>request_zip</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>becquerel__mi_incident_project_data</label>
    <pluralLabel>becquerel__mi_incident_project_data</pluralLabel>
</CustomObject>

metadata-classic/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>user_pk_id__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Foreign key value for Salesforce Connect; PK ID from the database. This field is mapped / synced with website.usr_user.user_user_pk</description>
        <externalId>true</externalId>
        <label>Thumbtack User PK</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/Dispute__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeExperience__c.object
<CustomObject>
    <description>Custom object that will store the Solution Center dispute experience configuration records.</description>
    <fields>
        <fullName>DefaultExperience__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate if the record is used as the default dispute experience.</description>
        <inlineHelpText>Indicates if this dispute experience is the default experience for the Solution Center.</inlineHelpText>
        <label>Default Experience</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResolutionOptions__c</fullName>
        <description>The available resolution options for an agent to select from when creating a dispute.  Used in lightning component.</description>
        <inlineHelpText>The available resolution options for an agent to select from when creating a dispute.</inlineHelpText>
        <label>Resolution Options (Agent facing)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete or redo the work</fullName>
                </value>
                <value>
                    <fullName>Complete or redo the work and refund</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist whose values indicate the overall publication status of the Dispute Experience.</description>
        <inlineHelpText>Publication status of the dispute experience.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Needs approval</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dispute Experience</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Experiences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>AmountInDispute__c</fullName>
        <description>Amount that the customer is disputing.</description>
        <inlineHelpText>This is the amount that the customer is disputing</inlineHelpText>
        <label>Amount in Dispute</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the contact record for the customer associated with the incident.</description>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DescriptionOfDispute__c</fullName>
        <description>A brief description of the dispute between the pro and customer.</description>
        <label>Description of Dispute</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the contact record for the pro associated to the incident.</description>
        <label>Pro Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bid_id__c</fullName>
        <description>External bid/quote ID from the the TT database.</description>
        <externalId>true</externalId>
        <label>bid_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>request_category__c</fullName>
        <description>The category of the request related to the bid_id of the incident; used in workflows and populated via SF Connect.</description>
        <label>request_category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/DisputeController.cls
/**
 * Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+===============================================
   1.0      2018-01-10   Mendel Guillaume       Created
   ========+============+=================+===============================================
 */

public with sharing class DisputeController
{
	@AuraEnabled
	public static Dispute__c getNewDispute(Id incidentId)
	{
		List<Dispute__c> disputes = [SELECT Id, Name, Status__c, Stage__c, LastStageChangeDate__c, SolutionCenterLink__c,
											OverallDisputeTimeInDays__c, OverallMessageCount__c, OverallOfferCount__c
										FROM Dispute__c WHERE MIIncident__c = :incidentId LIMIT 1];
		Dispute__c d = null;

		if(disputes.isEmpty())
		{
			MIIncident__c incident = getIncident(incidentId);
			List<DisputeExperience__c> defaultExperiences = [SELECT Id FROM DisputeExperience__c WHERE DefaultExperience__c = true AND Status__c = 'Published'];
			List<becquerel_mi_incident_project_data__x> projectData = null;

			d = new Dispute__c(MIIncident__c = incidentId, Status__c = 'Awaiting', Stage__c = 'Initiator confirmation needed');

			if (!defaultExperiences.isEmpty())
			{
				d.DisputeExperience__c = defaultExperiences[0].Id;
			}

			if (String.isNotBlank(incident.bid_id__c))
			{
				if (Test.isRunningTest())
				{
					projectData = new List<becquerel_mi_incident_project_data__x>
					{
						new becquerel_mi_incident_project_data__x(request_category__c = 'Test Category',
							request_city__c = 'Salt Lake City', request_state__c = 'UT', request_zip__c = '84044', bid_id__c = 123456)
					};
				}
				else
				{
					projectData = [
						SELECT Id, request_category__c, request_city__c, request_state__c, request_zip__c
						FROM becquerel_mi_incident_project_data__x
						WHERE bid_id__c = :Decimal.valueOf(incident.bid_id__c)
						LIMIT 1
					];
				}

				if (!projectData.isEmpty())
				{
					d.request_zip__c = projectData[0].request_zip__c;
					d.request_state__c = projectData[0].request_state__c;
					d.request_city__c = projectData[0].request_city__c;
					d.request_category__c = projectData[0].request_category__c;
				}
			}

			d.PrePopulatedResolutionAmount__c = incident.AmountInDispute__c;
			d.Description__c = incident.DescriptionOfDispute__c;
			d.bid_pk__c = incident.bid_id__c;
			d.InitiatorContact__c = incident.CustomerContact__c;
		}
		else
		{
			d = disputes[0];
		}

		return d;
	}

	@AuraEnabled
	public static MIIncident__c getIncident(Id incidentId)
	{
		return [SELECT Id, ProContact__c, ProAccount__c, ProContact__r.Name, CustomerAccount__c, CustomerContact__c,
					CustomerContact__r.Name, AmountInDispute__c, DescriptionOfDispute__c, bid_id__c,
					ProContact__r.user_pk_id__c, CustomerContact__r.user_pk_id__c
				FROM MIIncident__c WHERE Id = :incidentId];
	}

	@AuraEnabled
	public static List<String> getResolutions(Id disputeExperienceId)
	{
		List<String> options = new List<String>();
		List<DisputeExperience__c> experiences = [SELECT ResolutionOptions__c FROM DisputeExperience__c WHERE Id = :disputeExperienceId AND Status__c = 'Published'];

		if(!experiences.isEmpty() && string.isNotBlank(experiences[0].ResolutionOptions__c))
		{
			options = experiences[0].ResolutionOptions__c.split(';');
		}

		return options;
	}

	@AuraEnabled
	public static String saveDispute(Dispute__c dispute)
	{
		String result = 'Success';

		try
		{
			insert dispute;
		}
		catch (Exception ex)
		{
			result = ex.getMessage();
		}

		return result;
	}
}