metadata-classic/objects/Bug__c.object
<CustomObject>
    <description>Custom object to define actual Thumbtack.com product bugs, as opposed to bug reports which are actual reports of (potential/possible/thought to be) bugs and act as a junction object between Case and Bug</description>
    <fields>
        <fullName>Affects__c</fullName>
        <description>Who is affected by the bug: Pros, Customers, or both.</description>
        <inlineHelpText>Who is affected by the bug: Pros, Customers, or both.</inlineHelpText>
        <label>Affects</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Professionals</fullName>
                </value>
                <value>
                    <fullName>Customers</fullName>
                </value>
                <value>
                    <fullName>Both</fullName>
                </value>
                <value>
                    <fullName>Agents</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Approved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Approved ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>BugDescription__c</fullName>
        <description>if App Bug, include tracker link here</description>
        <inlineHelpText>if App Bug, include tracker link here</inlineHelpText>
        <label>Bug Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>DateFixed__c</fullName>
        <description>The date on which the bug was fixed.</description>
        <inlineHelpText>The date on which the bug was fixed.</inlineHelpText>
        <label>Date Fixed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateLogged__c</fullName>
        <description>The date on which the bug was first logged.</description>
        <inlineHelpText>The date on which the bug was first logged.</inlineHelpText>
        <label>Date Logged</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IssueSentToJiraStatus__c</fullName>
        <label>Jira Sync Status</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IssueType__c</fullName>
        <label>Issue Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JIRALink__c</fullName>
        <description>The URL to the JIRA card for this bug.</description>
        <inlineHelpText>The URL to the JIRA card for this bug.</inlineHelpText>
        <label>JIRA Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>JiraId__c</fullName>
        <label>Jira Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Labels__c</fullName>
        <label>Labels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer-Support</fullName>
                </value>
                <value>
                    <fullName>Customer-Support-Non-Urgent</fullName>
                </value>
                <value>
                    <fullName>Customer-Support-Semi-Urgent</fullName>
                </value>
                <value>
                    <fullName>Customer-Support-Urgent</fullName>
                </value>
                <value>
                    <fullName>Customer-Support-Ongoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Highest / Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Lowest / Only track</fullName>
                </value>
                <value>
                    <fullName>Untriaged</fullName>
                    <default>true</default>
                    <label>Untriaged</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Urgency__c</fullName>
        <description>The Level of Urgency assigned to this Bug.</description>
        <inlineHelpText>The Level of Urgency assigned to this Bug.</inlineHelpText>
        <label>Urgency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Non-Urgent</fullName>
                </value>
                <value>
                    <fullName>Semi-Urgent</fullName>
                </value>
                <value>
                    <fullName>Urgent/Severe</fullName>
                </value>
                <value>
                    <fullName>Android Customer App (Punk)</fullName>
                </value>
                <value>
                    <fullName>Android Pro App (Daft)</fullName>
                </value>
                <value>
                    <fullName>iOS Customer App (BowTie)</fullName>
                </value>
                <value>
                    <fullName>iOS Pro App (WingTip)</fullName>
                </value>
                <value>
                    <fullName>Polish - Approved</fullName>
                </value>
                <value>
                    <fullName>Polish - Suggestion</fullName>
                </value>
                <value>
                    <fullName>Not a Bug</fullName>
                </value>
                <value>
                    <fullName>Under Investigation</fullName>
                </value>
                <value>
                    <fullName>Tracker Bug</fullName>
                </value>
                <value>
                    <fullName>Eng Won&apos;t Fix Tracker</fullName>
                </value>
                <value>
                    <fullName>Instant Quote</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bug</label>
    <nameField>
        <label>Bug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bugs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Comments__c</fullName>
        <description>Comment field use for anytime general comments are needed.</description>
        <label>Comments</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SuppliedThumbtackID__c</fullName>
        <description>The Thumbtack user ID - data passed in from outside sources - used to match to account/contact.</description>
        <label>Supplied Thumbtack ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Comments__c.object
<CustomObject>
    <description>JIRA Comments</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bug__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bug</label>
        <referenceTo>Bug__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SupportProcess__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Support Process</label>
        <referenceTo>SupportProcess__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/JiraAPI__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>BaseURL__c</fullName>
        <label>BaseURL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>JiraAPI</label>
</CustomObject>

metadata-classic/objects/SupportProcess__c.object
<CustomObject>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/JiraCalloutTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:
------------
Version    Date     Author            Description
=======+===========+=================+================================================
1.0     01-13-2017  Scott Purcell      Created
=======+===========+=================+================================================
*/
@istest
public with sharing class JiraCalloutTest 
{

	public static testMethod void testSingleCallout() 
	{
		JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;

		Test.setMock(HttpCalloutMock.class, new JiraMock());
		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        //insert new JiraAPI__c(Name = 'default',Endpoint__c = 'http://api.salesforce.com/foo/bar',Password__c = 'pass',UserName__c = 'user');

		Bug__c bug = new Bug__c();
		bug.Affects__c = 'Customers';
		bug.BugDescription__c='This is a text field';
		bug.DateFixed__c=Date.Today();
		bug.DateLogged__c=Date.Today().addDays(-5);
		bug.JIRALink__c='http://Google.com';
		bug.Urgency__c='Non-Urgent';
		bug.Priority__c = 'High';
		bug.IssueType__c = 'bug';
		bug.Approved__c = true;
		bug.Labels__c = 'Customer-Support;Customer-Support-Non-Urgent;Customer-Support-Semi-Urgent;Customer-Support-Urgent;Customer-Support-Ongoing';
		
		System.runAs(testUser) 
        {
			Test.startTest();
			insert bug;
			JiraCallout.UpdateIssue(bug.Id);
			Test.stopTest();
			List<Bug__c> bugs = [Select Id,Affects__c,BugDescription__c,DateFixed__c,DateLogged__c,IssueSentToJiraStatus__c,JIRALink__c,Urgency__c From Bug__c Where Id =:bug.Id];
			system.debug(bugs);
			//Verify response received contains fake values
			String contentType = JiraCallout.res.getHeader('Content-Type');
			System.assert(contentType == 'application/json');
			String actualValue = JiraCallout.res.getBody();
			String expectedValue = '{"id":"21466","key":"AV-8940","self":"https://thumbtack.atlassian.net/rest/api/2/issue/21466"}';
			System.assertEquals(actualValue, expectedValue);
			System.assertEquals(200, JiraCallout.res.getStatusCode());
		}

    }
    @isTest static void testSingleNoteInsert() {
    	JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;

		Test.setMock(HttpCalloutMock.class, new JiraMock());
		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        //insert new JiraAPI__c(Name = 'default',Endpoint__c = 'http://api.salesforce.com/foo/bar',Password__c = 'pass',UserName__c = 'user');

		Bug__c bug = new Bug__c();
		bug.Affects__c = 'Customers';
		bug.BugDescription__c='This is a text field';
		bug.DateLogged__c=Date.Today().addDays(-5);
		bug.Urgency__c='Non-Urgent';
		bug.Priority__c = 'High';
		bug.IssueType__c = 'bug';
		//bug.Approved__c = true;
		bug.Labels__c = 'Customer-Support;Customer-Support-Non-Urgent;Customer-Support-Semi-Urgent;Customer-Support-Urgent;Customer-Support-Ongoing';
		insert bug;
		Note note = new Note();
		note.Title ='test note';
		note.ParentId = bug.Id;
		note.Body = 'this is the body';
		System.runAs(testUser) 
        {
			Test.startTest();
			insert note;
			Test.stopTest();
			Note notes = [Select Id,Title,ParentId From Note where ParentId =: bug.Id LIMIT 1];
			system.debug(notes);
			system.assert(notes!= null);
			system.assertEquals(bug.Id,Notes.ParentId);
			
		}
	}
	@isTest static void testSingleCommentInsert() {
    	JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;

		Test.setMock(HttpCalloutMock.class, new JiraMock());
		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        //insert new JiraAPI__c(Name = 'default',Endpoint__c = 'http://api.salesforce.com/foo/bar',Password__c = 'pass',UserName__c = 'user');

		Bug__c bug = new Bug__c();
		bug.Affects__c = 'Customers';
		bug.BugDescription__c='This is a text field';
		bug.DateLogged__c=Date.Today().addDays(-5);
		bug.Urgency__c='Non-Urgent';
		bug.Priority__c = 'High';
		bug.IssueType__c = 'bug';
		//bug.Approved__c = true;
		bug.Labels__c = 'Customer-Support;Customer-Support-Non-Urgent;Customer-Support-Semi-Urgent;Customer-Support-Urgent;Customer-Support-Ongoing';
		insert bug;
		List<String> noteList = new List<String>();
		Comments__c note = new Comments__c();
		note.Name ='test note';
		note.Bug__c= bug.Id;
		note.Body__c = 'this is the body';
		insert note;
		noteList.add(note.Id);
		System.runAs(testUser) 
        {
			Test.startTest();
				JiraCallout.addComment(noteList);
			Test.stopTest();
		}
	}
	 public static testMethod void testSingleSupportProcessCallout() 
	{
		JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;

		Test.setMock(HttpCalloutMock.class, new JiraMock());
		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        //insert new JiraAPI__c(Name = 'default',Endpoint__c = 'http://api.salesforce.com/foo/bar',Password__c = 'pass',UserName__c = 'user');
        Id caseRTId=Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer Support').getRecordTypeId();
        Case c = new Case(Status='New',RecordTypeId=caseRTId,Origin='Web',SuppliedEmail='tester@bogus.testing.com',SuppliedName='Chester CaseTester',SuppliedThumbtackID__c=120);
        insert c;
		SupportProcess__c sp = new SupportProcess__c();
		sp.DateBugFixed__c=Date.Today();
		sp.JIRASummary__c='summary';
		sp.JIRALink__c='http://Google.com';
		sp.JIRAEscalationNotes__c = 'notes';
		sp.Case__c = c.Id;
		insert sp;
		
		System.runAs(testUser) 
        {
			Test.startTest();
				JiraCallout.createSupportProcessIssue(sp.Id);
				JiraCallout.updateSupportProcessIssue(sp.Id);
			Test.stopTest();
			List<SupportProcess__c> bugs = [Select Id,DateBugFixed__c,IssueSentToJiraStatus__c,JIRALink__c From SupportProcess__c Where Id =:sp.Id];
			system.debug(bugs);
			//Verify response received contains fake values
			String contentType = JiraCallout.res.getHeader('Content-Type');
			System.assert(contentType == 'application/json');
			String actualValue = JiraCallout.res.getBody();
			String expectedValue = '{"id":"21466","key":"AV-8940","self":"https://thumbtack.atlassian.net/rest/api/2/issue/21466"}';
			System.assertEquals(actualValue, expectedValue);
			System.assertEquals(200, JiraCallout.res.getStatusCode());
		}

    }
    public static testMethod void testGetComments() 
	{
		JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;

		Test.setMock(HttpCalloutMock.class, new JiraMock());
		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        //insert new JiraAPI__c(Name = 'default',Endpoint__c = 'http://api.salesforce.com/foo/bar',Password__c = 'pass',UserName__c = 'user');
        Id caseRTId=Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer Support').getRecordTypeId();
        Case c = new Case(Status='New',RecordTypeId=caseRTId,Origin='Web',SuppliedEmail='tester@bogus.testing.com',SuppliedName='Chester CaseTester',SuppliedThumbtackID__c=120);
        insert c;
		SupportProcess__c sp = new SupportProcess__c();
		sp.DateBugFixed__c=Date.Today();
		sp.JIRASummary__c='summary';
		sp.JIRALink__c='http://Google.com';
		sp.JIRAEscalationNotes__c = 'notes';
		sp.Case__c = c.Id;
		insert sp;
		
		System.runAs(testUser) 
        {
			Test.startTest();
				JiraCallout.getComments(sp.Id,'1234',true);
			Test.stopTest();
			List<SupportProcess__c> bugs = [Select Id,DateBugFixed__c,IssueSentToJiraStatus__c,JIRALink__c From SupportProcess__c Where Id =:sp.Id];
			system.debug(bugs);
			//Verify response received contains fake values
			String contentType = JiraCallout.res.getHeader('Content-Type');
			System.assert(contentType == 'application/json');
			String actualValue = JiraCallout.res.getBody();
			String expectedValue = '{"id":"21466","key":"AV-8940","self":"https://thumbtack.atlassian.net/rest/api/2/issue/21466"}';
			System.assertEquals(actualValue, expectedValue);
			System.assertEquals(200, JiraCallout.res.getStatusCode());
		}

    }
    public static testMethod void testSingleCalloutUpdate()                               
	{
		JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;

		Test.setMock(HttpCalloutMock.class, new JiraMock());
		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        //insert new JiraAPI__c(Name = 'default',Endpoint__c = 'http://api.salesforce.com/foo/bar',Password__c = 'pass',UserName__c = 'user');

		Bug__c bug = new Bug__c();
		bug.Affects__c = 'Customers';
		bug.BugDescription__c='This is a text field';
		bug.DateFixed__c=Date.Today();
		bug.DateLogged__c=Date.Today().addDays(-5);
		bug.JIRALink__c='http://Google.com';
		bug.Urgency__c='Non-Urgent';
		bug.Priority__c = 'High';
		bug.IssueType__c = 'bug';
		bug.Labels__c = 'Customer-Support;Customer-Support-Non-Urgent;Customer-Support-Semi-Urgent;Customer-Support-Urgent;Customer-Support-Ongoing';
		insert bug;
		
		System.runAs(testUser) 
        {
			Test.startTest();
			bug.Approved__c = true;
			update bug;
			Test.stopTest();
			List<Bug__c> bugs = [Select Id,Affects__c,BugDescription__c,DateFixed__c,DateLogged__c,IssueSentToJiraStatus__c,JIRALink__c,Urgency__c From Bug__c Where Id =:bug.Id];
			system.debug(bugs);
			//Verify response received contains fake values
			String contentType = JiraCallout.res.getHeader('Content-Type');
			System.assert(contentType == 'application/json');
			String actualValue = JiraCallout.res.getBody();
			String expectedValue = '{"id":"21466","key":"AV-8940","self":"https://thumbtack.atlassian.net/rest/api/2/issue/21466"}';
			System.assertEquals(actualValue, expectedValue);
			System.assertEquals(200, JiraCallout.res.getStatusCode());
		}

    }
	public static testMethod void testBulkCallout()
	{
		JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;
		Test.setMock(HttpCalloutMock.class, new JiraMock());
		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        //insert new JiraAPI__c(Name = 'default',Endpoint__c = 'http://api.salesforce.com/foo/bar',Password__c = 'pass',UserName__c = 'user');
		List<Bug__c> bugList = new List<Bug__c>();
		for(Integer i = 0;i<100;i++)
		{
			Bug__c bug = new Bug__c();
			bug.Affects__c = 'Customers';
			bug.BugDescription__c='This is a text field';
			bug.DateFixed__c=Date.Today();
			bug.DateLogged__c=Date.Today().addDays(-5);
			bug.JIRALink__c='http://Google.com';
			bug.Urgency__c='Non-Urgent';
			bug.Priority__c = 'High';
			bug.IssueType__c = 'bug';
			bug.Approved__c = true;
			bug.Labels__c = 'Customer-Support;Customer-Support-Non-Urgent;Customer-Support-Semi-Urgent;Customer-Support-Urgent;Customer-Support-Ongoing';
			buglist.add(bug);
		}
		System.runAs(testUser) 
        {
			Test.startTest();
			insert bugList;
			Test.stopTest();

			List<Bug__c> bugs = [Select Id,Affects__c,BugDescription__c,DateFixed__c,DateLogged__c,IssueSentToJiraStatus__c,JIRALink__c,Urgency__c From Bug__c Where Id IN: bugList];
			system.debug(bugs);
			// Verify response received contains fake values
       		String contentType = JiraCallout.res.getHeader('Content-Type');
			System.assert(contentType == 'application/json');
			String actualValue = JiraCallout.res.getBody();
			String expectedValue = '{"id":"21466","key":"AV-8940","self":"https://thumbtack.atlassian.net/rest/api/2/issue/21466"}';
			System.assertEquals(actualValue, expectedValue);
			System.assertEquals(200, JiraCallout.res.getStatusCode());
		}
    }
    public static testMethod void testBulkCalloutUpdate()
	{
		JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;
		Test.setMock(HttpCalloutMock.class, new JiraMock());
		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        //insert new JiraAPI__c(Name = 'default',Endpoint__c = 'http://api.salesforce.com/foo/bar',Password__c = 'pass',UserName__c = 'user');
		List<Bug__c> bugList = new List<Bug__c>();
		for(Integer i = 0;i<100;i++)
		{
			Bug__c bug = new Bug__c();
			bug.Affects__c = 'Customers';
			bug.BugDescription__c='This is a text field';
			bug.DateFixed__c=Date.Today();
			bug.DateLogged__c=Date.Today().addDays(-5);
			bug.JIRALink__c='http://Google.com';
			bug.Urgency__c='Non-Urgent';
			bug.Priority__c = 'High';
			bug.IssueType__c = 'bug';
			bug.Labels__c = 'Customer-Support;Customer-Support-Non-Urgent;Customer-Support-Semi-Urgent;Customer-Support-Urgent;Customer-Support-Ongoing';
			buglist.add(bug);
			
		}
		insert bugList;
		System.runAs(testUser) 
        {
			Test.startTest();
			for(Bug__c b:bugList)b.Approved__c = true;
			update bugList;
			Test.stopTest();

			List<Bug__c> bugs = [Select Id,Affects__c,BugDescription__c,DateFixed__c,DateLogged__c,IssueSentToJiraStatus__c,JIRALink__c,Urgency__c From Bug__c Where Id IN: bugList];
			system.debug(bugs);
			// Verify response received contains fake values
       		String contentType = JiraCallout.res.getHeader('Content-Type');
			System.assert(contentType == 'application/json');
			String actualValue = JiraCallout.res.getBody();
			String expectedValue = '{"id":"21466","key":"AV-8940","self":"https://thumbtack.atlassian.net/rest/api/2/issue/21466"}';
			System.assertEquals(actualValue, expectedValue);
			System.assertEquals(200, JiraCallout.res.getStatusCode());
		}
    }
    @isTest static void testUpdateAttachment() 
	{
		JiraAPI__c cs = new JiraAPI__c();
        cs.Name='default';
        cs.BaseURL__c = 'http://api.salesforce.com/foo/bar';
        cs.Password__c = 'pass';
        cs.UserName__c = 'user' ;
        //cs.Other fiels values
     	insert cs;
		Test.setMock(HttpCalloutMock.class, new JiraMock());

		User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';

		Bug__c bug = new Bug__c();
		bug.Affects__c = 'Customers';
		bug.BugDescription__c='This is a text field';
		bug.DateLogged__c=Date.Today().addDays(-5);
		bug.Urgency__c='Non-Urgent';
		bug.Priority__c = 'High';
		bug.IssueType__c = 'bug';
		bug.Approved__c = false;
		bug.JiraId__c = '123456';
		bug.Labels__c = 'Customer-Support;Customer-Support-Non-Urgent;Customer-Support-Semi-Urgent;Customer-Support-Urgent;Customer-Support-Ongoing';
		insert bug;

		Attachment attach=new Attachment();   	
    	attach.Name='Unit Test Attachment';
    	Blob bodyBlob=Blob.valueOf('Unit Test Attachment Body');
    	attach.body=bodyBlob;
        attach.parentId=bug.id;
        insert attach;

		System.runAs(testUser) 
        {
			Test.startTest();
        		update attach;
    		Test.stopTest();
    	
	    	List<Attachment> attachments=[Select Id,Name From Attachment Where ParentId =: bug.Id];
	    	System.assertEquals(1, attachments.size());
    	}
	}
	
}