metadata-classic/objects/Bug__c.object
<CustomObject>
    <description>Custom object to define actual Thumbtack.com product bugs, as opposed to bug reports which are actual reports of (potential/possible/thought to be) bugs and act as a junction object between Case and Bug</description>
    <fields>
        <fullName>BugDescription__c</fullName>
        <description>if App Bug, include tracker link here</description>
        <inlineHelpText>if App Bug, include tracker link here</inlineHelpText>
        <label>Bug Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>DateFixed__c</fullName>
        <description>The date on which the bug was fixed.</description>
        <inlineHelpText>The date on which the bug was fixed.</inlineHelpText>
        <label>Date Fixed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateLogged__c</fullName>
        <description>The date on which the bug was first logged.</description>
        <inlineHelpText>The date on which the bug was first logged.</inlineHelpText>
        <label>Date Logged</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IssueSentToJiraStatus__c</fullName>
        <label>Jira Sync Status</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>IssueType__c</fullName>
        <label>Issue Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Bug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>JIRAComments__c</fullName>
        <label>JIRA Comments</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>JIRALink__c</fullName>
        <description>The URL to the JIRA card for this bug.</description>
        <inlineHelpText>The URL to the JIRA card for this bug.</inlineHelpText>
        <label>JIRA Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>JiraAttachmentList__c</fullName>
        <label>JiraAttachmentList</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>JiraId__c</fullName>
        <label>Jira Id</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>JiraStatus__c</fullName>
        <label>Jira Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>To Do</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Needs Design</fullName>
                </value>
                <value>
                    <fullName>In Code Review</fullName>
                </value>
                <value>
                    <fullName>Not Doing</fullName>
                </value>
                <value>
                    <fullName>Done</fullName>
                </value>
                <value>
                    <fullName>Backlog</fullName>
                </value>
                <value>
                    <fullName>Tracking</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Labels__c</fullName>
        <label>Labels</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Customer-Support</fullName>
                </value>
                <value>
                    <fullName>Customer-Support-Non-Urgent</fullName>
                </value>
                <value>
                    <fullName>Customer-Support-Semi-Urgent</fullName>
                </value>
                <value>
                    <fullName>Customer-Support-Urgent</fullName>
                </value>
                <value>
                    <fullName>Customer-Support-Ongoing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Highest / Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Lowest / Only track</fullName>
                </value>
                <value>
                    <fullName>Untriaged</fullName>
                    <default>true</default>
                    <label>Untriaged</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProjectId__c</fullName>
        <formula>CASE(Project__c, 
&apos;Bowtie (iOS Customer App) (BT)&apos;,&apos;10203&apos;,
&apos;Business Applications (SYS)&apos;,&apos;13702&apos;,
&apos;Customer Growth (GR)&apos;,&apos;10806&apos;,
&apos;Customer Project Experience (CPX)&apos;,&apos;13708&apos;,
&apos;Daft (Android Pro App) (DAFT)&apos;,&apos;11100&apos;,
&apos;Design Systems (DS)&apos;,&apos;13707&apos;,
&apos;First Contact (FC)&apos;,&apos;13709&apos;,
&apos;Marketplace (IR)&apos;,&apos;13200&apos;,
&apos;Marketplace Trust &amp; Safety (MI)&apos;,&apos;12900&apos;,
&apos;Needs Triage (TT)&apos;,&apos;10100&apos;,
&apos;Payments (PAY)&apos;,&apos;12400&apos;,
&apos;Pro Growth (PROG)&apos;,&apos;13714&apos;,
&apos;Pro Project Experience (PPX)&apos;,&apos;13711&apos;,
&apos;Punk (Android Consumer App) (PUNK)&apos;,&apos;12700&apos;,
&apos;Reach &amp; Reporting (RR)&apos;,&apos;13712&apos;,
&apos;StoreFurrront (STOR)&apos;,&apos;13713&apos;,
&apos;Technical Infrastructure (TI)&apos;,&apos;13701&apos;,
&apos;Tophat (TH)&apos;,&apos;11000&apos;,
&apos;Wingtip (iOS Pro App) (WT)&apos;,&apos;10204&apos;,
&apos;Customer Experience (PCX)&apos;,&apos;11400&apos;,
&apos;Data Platform (DP)&apos;,&apos;10000&apos;,
&apos;Foundation (FN)&apos;,&apos;10400&apos;,
&apos;Front-End Engineering (FE)&apos;,&apos;10800&apos;,
&apos;Marketplace Mechanics (MM)&apos;,&apos;10500&apos;,
&apos;Monetization (M10N)&apos;,&apos;12800&apos;,
&apos;Pro Success (PS)&apos;,&apos;13000&apos;,
&apos;Pro Tools (PT)&apos;,&apos;13100&apos;,
&apos;Procaptivate (PRO)&apos;,&apos;10900&apos;,
&apos; &apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bowtie (iOS Customer App) (BT)</fullName>
                </value>
                <value>
                    <fullName>Customer Growth (GR)</fullName>
                </value>
                <value>
                    <fullName>Customer Project Experience (CPX)</fullName>
                </value>
                <value>
                    <fullName>Daft (Android Pro App) (DAFT)</fullName>
                </value>
                <value>
                    <fullName>Design Systems (DS)</fullName>
                </value>
                <value>
                    <fullName>First Contact (FC)</fullName>
                </value>
                <value>
                    <fullName>Marketplace (IR)</fullName>
                </value>
                <value>
                    <fullName>Marketplace Trust &amp; Safety (MI)</fullName>
                </value>
                <value>
                    <fullName>Needs Triage (TT)</fullName>
                </value>
                <value>
                    <fullName>Payments (PAY)</fullName>
                </value>
                <value>
                    <fullName>Pro Growth (PROG)</fullName>
                </value>
                <value>
                    <fullName>Pro Project Experience (PPX)</fullName>
                </value>
                <value>
                    <fullName>Punk (Android Consumer App) (PUNK)</fullName>
                </value>
                <value>
                    <fullName>Reach &amp; Reporting (RR)</fullName>
                </value>
                <value>
                    <fullName>StoreFurrront (STOR)</fullName>
                </value>
                <value>
                    <fullName>Technical Infrastructure (TI)</fullName>
                </value>
                <value>
                    <fullName>Tophat (TH)</fullName>
                </value>
                <value>
                    <fullName>Wingtip (iOS Pro App) (WT)</fullName>
                </value>
                <value>
                    <fullName>***Below are No Longer in Use***</fullName>
                </value>
                <value>
                    <fullName>Customer Experience (PCX)</fullName>
                </value>
                <value>
                    <fullName>Data Platform (DP)</fullName>
                </value>
                <value>
                    <fullName>Foundation (FN)</fullName>
                </value>
                <value>
                    <fullName>Front-End Engineering (FE)</fullName>
                </value>
                <value>
                    <fullName>Marketplace Mechanics (MM)</fullName>
                </value>
                <value>
                    <fullName>Monetization (M10N)</fullName>
                </value>
                <value>
                    <fullName>Pro Success (PS)</fullName>
                </value>
                <value>
                    <fullName>Pro Tools (PT)</fullName>
                </value>
                <value>
                    <fullName>Procaptivate (PRO)</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bug</label>
    <nameField>
        <label>Bug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bugs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Comments__c.object
<CustomObject>
    <description>JIRA Comments</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Bug__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bug</label>
        <referenceTo>Bug__c</referenceTo>
        <relationshipLabel>Comments</relationshipLabel>
        <relationshipName>Comments</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Comment</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/CustomException__c.object
<CustomObject>
    <fields>
        <fullName>BugRecordType__c</fullName>
        <label>Bug Record Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Account</fullName>
                </value>
                <value>
                    <fullName>Contact</fullName>
                </value>
                <value>
                    <fullName>Jira Integration</fullName>
                </value>
                <value>
                    <fullName>Lead</fullName>
                </value>
                <value>
                    <fullName>Service</fullName>
                </value>
                <value>
                    <fullName>WorkItem</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>Error Message</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>RecordId__c</fullName>
        <label>Record Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Custom Exception</label>
    <nameField>
        <label>Custom Exception Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Exceptions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/JiraAPI__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>BaseURL__c</fullName>
        <label>BaseURL</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>JiraAPI</label>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/GetJiraIssue.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:
------------
Version    Date     Author            Description
=======+===========+=================+================================================
1.0     01-13-2017  Scott Purcell      Created
=======+===========+=================+================================================
*/
global class GetJiraIssue {
	public static HttpResponse res {get;set;}
    public class customException extends Exception{}

	webservice static void getIssue(String bugId )
    {
        List<Comments__c> noteList = new List<Comments__c>();
        List<Comments__c> notes = [Select Id,Body__c,Name From Comments__c WHERE Bug__c =: bugId];
        Boolean isCreate = false;
        Boolean attachmentsExist = false;
        Bug__c bug = [Select Id,ProjectId__c,JIRAComments__c,JiraAttachmentList__c,Labels__c,Comments__c,Name,JiraStatus__c,JiraId__c,BugDescription__c,DateFixed__c,DateLogged__c,IssueSentToJiraStatus__c,JIRALink__c,IssueType__c,Priority__c,Project__c From Bug__c Where Id =:bugId LIMIT 1]; 
        if(bug == null) return;
        
        String baseUrl; 
        String username;
        String password;
        for(JiraAPI__c jira : JiraAPI__c.getAll().values())
        {
            baseUrl = jira.BaseURL__c;        // Base URL of your JIRA instance
            username = jira.Username__c;       // JIRA username
            password = jira.Password__c;       // JIRA password
        }

        HttpRequest req = new HttpRequest();

        
            req.setMethod( 'GET');
            req.setEndpoint(baseUrl + '/'+ bug.JiraId__c);
            req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username+ ':'+password)));
            req.setHeader('Content-Type', 'application/json');
            //req.setBody(getbody(bug,isCreate));
            string errMsg = (isCreate?'Not Created':'Not Synced To Salesforce On: '+String.valueOf(Date.today()));
            system.debug('request: '+req);
            try
            {
               res = (new Http()).send(req);
               system.debug('res.getStatusCode(): '+res.getStatusCode()+', result: '+res);
                
            } Catch(Exception ex){
                /*CustomException__c exeption = new CustomException__c();
                exeption.Name = 'GetJiraIssue Exeption';
                exeption.ErrorMessage__c = ex.getMessage();
                exeption.RecordId__c = bugId;
                insert exeption;*/
                system.debug(ex);
                
                
            }

            if(res != null){
                
                if(res.getStatusCode() == 200)
                {
                    //success
                    getIssueObj myReturn = (GetJiraIssue.getIssueObj)JSON.deserialize(res.getBody(), GetJiraIssue.getIssueObj.class);
                    
                    //bug.Summary__c = myReturn.Fields.summary;
                    bug.JiraStatus__c = myReturn.Fields.status.name;
                    bug.Priority__c = myReturn.Fields.priority.name;
                   /* bug.BugDescription__c = myReturn.Fields.description;
                    system.debug('description from JIRA: '+bug.BugDescription__c);
                    bug.BugDescription__c = bug.BugDescription__c .unescapeHtml4();
                    bug.BugDescription__c = bug.BugDescription__c.replace('"https://','<br>"https://');
                    bug.BugDescription__c = bug.BugDescription__c.replace('"https://','<br>"https://');
                    system.debug('description from JIRA: '+bug.BugDescription__c);*/
                    //************************ TODO COmments ********************
                    system.debug('attachments: '+myReturn.Fields.attachment);
                    bug.JiraAttachmentList__c = null;
                    if(myReturn.Fields.attachment !=null)
                    {
                        for(Attachments a:myReturn.Fields.attachment)
                        {
                            bug.JiraAttachmentList__c += a.filename+',';
                        }
                    }
                    system.debug('bug.JiraAttachmentList__c: '+bug.JiraAttachmentList__c);
                    if(myReturn.Fields.comment != null)
                    {
                        for(Comments c:myReturn.Fields.comment.comments)
                        {
                            Boolean exist = false;
                            for(Comments__c note:notes)
                            {
                                //system.debug('not.Title: '+note.Title + ', comment.Id: JIRA COMMENT -'+c.id);
                                if(note.Name.contains(c.id) || c.body.contains('SALESFORCE COMMENT'))
                                {
                                    system.debug('Exists = true');
                                    exist = true;
                                }
                            }
                            if(exist == false)
                            {
                                system.debug('exists = false');
                                Comments__c n = new Comments__c();
                                n.Bug__c = bugId;
                                n.Name = 'JIRA COMMENT - '+c.Id;
                                n.Body__c = c.body;
                                noteList.add(n);
                                system.debug('c.body: '+c.body);
                            }
                            
                        }
                    }
                    bug.IssueSentToJiraStatus__c = 'Issue Synced to Salesforce On: '+String.valueOf(Date.today());
                    
                } else {
                   /* CustomException__c exeption = new CustomException__c();
                    exeption.Name = 'GetJiraIssue Exeption';
                    exeption.ErrorMessage__c = res.getBody();
                    exeption.RecordId__c = bugId;
                    exeption.BugRecordType__c = 'Jira Integration';
                    insert exeption;*/
                    bug.IssueSentToJiraStatus__c = errMsg;
                }
                
            }
        update bug;
        if(noteList.size()>0)insert noteList;
    }
    

    
    public class getIssueObj{

        public Status Status;
        public Attachment Attachment;
        public Assignee Assignee;
        public Comment Comment;

        public String expand;
        public String id;
        public String self;
        public String key;
        public Fields fields;

        public Priority Priority;
        public Watches Watches;
        public Comments Comments;
        public Components Components;
        public Project Project;
        public StatusCategory StatusCategory;
        public Issuetype Issuetype;

    }

    public class Status {
        public String self;
        public String description;
        public String iconUrl;
        public String name;
        public String id;
    }
    public class Attachments {
        public String self;
        public String id;
        public String filename;
    }

    public class Assignee {
        public String self;
        public String name;
        public String key;
        public String emailAddress;
        //public AvatarUrls avatarUrls;
        public String displayName;
        public Boolean active;
        public String timeZone;
    }
    public class Comment {
        public Integer startAt;
        public Integer maxResults;
        public Integer total;
        public List<Comments> comments;
    }
    

    public class Priority {
        public String self;
        public String iconUrl;
        public String name;
        public String id;
    }

    public class Watches {
        public String self;
        public Integer watchCount;
        public Boolean isWatching;
    }

    public class Comments {
        public String id;
        public String self;
        public String body;
        public DateTime created;
    }

    public class Customfield_10030 {
        public String self;
        public String value;
        public String id;
    }

    public class Components {
        public String self;
        public String id;
        public String name;
    }

    public class Project {
        public String self;
        public String id;
        public String key;
        public String name;
    }

    public class StatusCategory {
        public String self;
        public Integer id;
        public String key;
        public String colorName;
        public String name;
    }

    public class Fields {
        public Issuetype issuetype;
        public Project project;
        public List<FixVersions> fixVersions;
        public Integer workratio;
        public String lastViewed;
        public Watches watches;
        public String created;
        public Priority priority;
        public List<FixVersions> versions;
        public Assignee assignee;
        public String updated;
        public Status status;
        public List<Components> components;
        public String description;
        public String summary;
        public Assignee creator;
        public Assignee reporter;
        public Comment comment;
        public Votes votes;
        public List<Attachments> attachment;
    }

    public class FixVersions {
        public String self;
        public String id;
        public String description;
        public String name;
        public Boolean archived;
        public Boolean released;
    }

    public class Issuetype {
        public String self;
        public String id;
        public String description;
        public String iconUrl;
        public String name;
        public Boolean subtask;
        public Integer avatarId;
    }

    public class Votes {
        public String self;
        public Integer votes;
        public Boolean hasVoted;
    }

    public class createIssueReturn{
        public string Id;//unique Id
        public string key;//Id used for api calls and searching in JIRA
        public string self;//url to get the created issue
    }
}