metadata-classic/objects/Bug__c.object
<CustomObject>
    <description>Custom object to define actual Thumbtack.com product bugs, as opposed to bug reports which are actual reports of (potential/possible/thought to be) bugs and act as a junction object between Case and Bug</description>
    <fields>
        <fullName>BugDescription__c</fullName>
        <description>if App Bug, include tracker link here</description>
        <inlineHelpText>if App Bug, include tracker link here</inlineHelpText>
        <label>Bug Description</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>DateFixed__c</fullName>
        <description>The date on which the bug was fixed.</description>
        <inlineHelpText>The date on which the bug was fixed.</inlineHelpText>
        <label>Date Fixed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Highest / Emergency</fullName>
                </value>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
                <value>
                    <fullName>Lowest / Only track</fullName>
                </value>
                <value>
                    <fullName>Untriaged</fullName>
                    <default>true</default>
                    <label>Untriaged</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Alyssa Wilson</fullName>
                </value>
                <value>
                    <fullName>Kevin Giltz</fullName>
                </value>
                <value>
                    <fullName>Deirdre Galluzzo</fullName>
                </value>
                <value>
                    <fullName>Kyle Thorup</fullName>
                </value>
                <value>
                    <fullName>Kristine Ann Pielago</fullName>
                </value>
                <value>
                    <fullName>Christina Caacoy</fullName>
                </value>
                <value>
                    <fullName>Jeff Oviatt</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Bug</label>
    <nameField>
        <label>Bug Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bugs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SuppliedThumbtackID__c</fullName>
        <description>The Thumbtack user ID - data passed in from outside sources - used to match to account/contact.</description>
        <label>Supplied Thumbtack ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/SupportProcess__c.object
<CustomObject>
</CustomObject>

metadata-classic/classes/BugTriggerHandlerTest.cls
/*
   Copyright (c) 2017 Thumbtack, All rights reserved.

Change List:
------------
Version   Date         Author           Description
========+============+=================+================================================
1.0       11/6/17      jkennington          Created
========+============+=================+===============================================*/
@IsTest
private class BugTriggerHandlerTest
{
    @IsTest
    private static void testBugCreationAndDateFixedUpdate()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            //Support Process Record Type
            Id spRTId = SupportProcess__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Bug Report').getRecordTypeId();
            Id caseRTId=Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer Support').getRecordTypeId();

            Case newCase = new Case(Status='New',RecordTypeId=caseRTId,Origin='Web',SuppliedEmail='tester@testing.com',SuppliedName='Phil Painter',SuppliedThumbtackID__c=120);
            insert newCase;

            Bug__c bug = new Bug__c();
            bug.Name = 'Test Bug';
            //bug.User__c = TestUtilities.USER_TACK_BOT.Id;
            bug.Priority__c = 'High';
            bug.BugDescription__c = 'Test Bug Description';
            insert bug;

            SupportProcess__c supportProcess = new SupportProcess__c();
            supportProcess.Case__c = newCase.Id;
            supportProcess.RecordTypeId = spRTId;
            supportProcess.Bug__c = bug.Id;
            insert supportProcess;


            Test.startTest();
            bug.DateFixed__c = System.today();
            update bug;

            Test.stopTest();

            //Assert that the trigger updated the child support process's
            System.assertEquals([SELECT DateBugFixed__c FROM SupportProcess__c WHERE Bug__c = :bug.Id][0].DateBugFixed__c, [SELECT DateFixed__c FROM Bug__c WHERE Id = :bug.Id][0].DateFixed__c,'Support Process and Bug Fixed Dates do not match');
        }
    }
}