metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>MICategory__c</fullName>
        <description>Marketplace Integrity Category</description>
        <inlineHelpText>Marketplace Integrity Category</inlineHelpText>
        <label>MI Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Background</fullName>
                </value>
                <value>
                    <fullName>Certification Agreement</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Dispute About Customer</fullName>
                </value>
                <value>
                    <fullName>Dispute About Professional</fullName>
                </value>
                <value>
                    <fullName>Follow Up with Customer</fullName>
                </value>
                <value>
                    <fullName>Follow Up with Professional</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MISubcategory__c</fullName>
        <description>Marketplace Integrity Subcategory</description>
        <inlineHelpText>Marketplace Integrity Subcategory</inlineHelpText>
        <label>MI Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MICategory__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Operating w/o Owner&apos;s Permission</fullName>
                </value>
                <value>
                    <fullName>Attorney General</fullName>
                </value>
                <value>
                    <fullName>Badge Applied</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>Charged Unfairly</fullName>
                </value>
                <value>
                    <fullName>Check/Payment Scam</fullName>
                </value>
                <value>
                    <fullName>Collateral Damage</fullName>
                </value>
                <value>
                    <fullName>Community Guidlines Violation</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Customer ceased contact</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>DMCA - Owner</fullName>
                </value>
                <value>
                    <fullName>DMCA - Response</fullName>
                </value>
                <value>
                    <fullName>DOJ - No longer on site</fullName>
                </value>
                <value>
                    <fullName>Failed BGC</fullName>
                </value>
                <value>
                    <fullName>Fraud - Braintree</fullName>
                </value>
                <value>
                    <fullName>Fraud - Card Owner</fullName>
                </value>
                <value>
                    <fullName>Good Samaritan Report - Background</fullName>
                </value>
                <value>
                    <fullName>Good Samaritan Report - License</fullName>
                </value>
                <value>
                    <fullName>Harassment</fullName>
                </value>
                <value>
                    <fullName>Insufficient Info</fullName>
                </value>
                <value>
                    <fullName>MBG Pilot</fullName>
                </value>
                <value>
                    <fullName>Money Back Guarantee</fullName>
                </value>
                <value>
                    <fullName>No Badge</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>No documentation provided</fullName>
                </value>
                <value>
                    <fullName>No Longer on Site</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paid Pro - No Show/Late</fullName>
                </value>
                <value>
                    <fullName>Paid Pro - Unsatisfactory Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>MarketplaceIntegrity</fullName>
        <active>true</active>
        <businessProcess>Customer Support</businessProcess>
        <description>Record type for MI cases</description>
        <label>Marketplace Integrity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>usr_user_id</description>
        <externalId>true</externalId>
        <label>User ID (Unique)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>This record type is used for all thumbtack customers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>MICategory__c</fullName>
        <description>Marketplace Integrity Incident categories.</description>
        <label>MI Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concern about user</fullName>
                </value>
                <value>
                    <fullName>Deposit no show</fullName>
                </value>
                <value>
                    <fullName>Payment issues</fullName>
                </value>
                <value>
                    <fullName>Physical harm / Inappropriate contact</fullName>
                </value>
                <value>
                    <fullName>Property damage</fullName>
                </value>
                <value>
                    <fullName>Theft</fullName>
                </value>
                <value>
                    <fullName>Unprofessional behavior</fullName>
                </value>
                <value>
                    <fullName>Unsatisfactory work</fullName>
                </value>
                <value>
                    <fullName>Work not complete</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MISubcategory__c</fullName>
        <description>Marketplace Integrity Incident Subcategories.</description>
        <label>MI Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MICategory__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Charged Unfairly</fullName>
                </value>
                <value>
                    <fullName>Check or payment scam</fullName>
                </value>
                <value>
                    <fullName>Criminal history</fullName>
                </value>
                <value>
                    <fullName>Fraudulent charges</fullName>
                </value>
                <value>
                    <fullName>Harassment</fullName>
                </value>
                <value>
                    <fullName>Licensing concerns</fullName>
                </value>
                <value>
                    <fullName>Threat or intimidation</fullName>
                </value>
                <value>
                    <fullName>Unprofessional communication</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RequestID__c</fullName>
        <inlineHelpText>Request ID of the customer&apos;s request that the pro quoted on.</inlineHelpText>
        <label>Request ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResolutionTier__c</fullName>
        <description>Tier of resolution for the Incident</description>
        <label>Resolution Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 0 - Lost Communication</fullName>
                </value>
                <value>
                    <fullName>Tier 1 - Re-established Communication</fullName>
                </value>
                <value>
                    <fullName>Tier 2 - Found Middle Ground</fullName>
                </value>
                <value>
                    <fullName>Tier 3 - Flagged Pro</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Removed Pro</fullName>
                </value>
                <value>
                    <fullName>Tier 5 - Thumbtack Compensation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>customer_id__c</fullName>
        <description>The id of the customer related to the bid_id of the incident.</description>
        <label>customer_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pro_user_id__c</fullName>
        <description>The id of the pro related to the bid_id of the incident.</description>
        <label>pro_user_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>quotes_bid_id__c</fullName>
        <externalId>true</externalId>
        <label>quotes_bid_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>quotes_customer_id__c</fullName>
        <label>quotes_customer_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>quotes_pro_user_id__c</fullName>
        <label>quotes_pro_user_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <recordTypes>
        <fullName>MarketplaceIntegrity</fullName>
        <active>true</active>
        <description>Record Type for MI Incidents</description>
        <label>Marketplace Integrity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The overall status of the incident action.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Soft decline</fullName>
                </value>
                <value>
                    <fullName>Hard decline</fullName>
                </value>
                <value>
                    <fullName>No charge possible</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pre-adjuster resolution process</fullName>
                </value>
                <value>
                    <fullName>Claim sent to adjuster</fullName>
                </value>
                <value>
                    <fullName>Claim in process</fullName>
                </value>
                <value>
                    <fullName>Paid (under Property Damage Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Money Back Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Satisfaction)</fullName>
                </value>
                <value>
                    <fullName>Not paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Payment sent</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent for approval</fullName>
                </value>
                <value>
                    <fullName>No card on file</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <recordTypes>
        <fullName>Guarantee</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with the TT property damage or money back guarantees.</description>
        <label>Guarantee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Payout</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with the MI Incident compensation payouts.</description>
        <label>Payout</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with follow-up tasks.</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/classes/IncidentActionControllerTest.cls
@isTest
private class IncidentActionControllerTest {
	public static Id miRecordTypeId = MIIncident__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('MI Incident').getRecordTypeId();
	public static Id PayoutRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Payout').getRecordTypeId();
    public static Id ChargeRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Charge Card').getRecordTypeId();
   // public static Id SolutionRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Solution Center').getRecordTypeId();
    public static Id GuaranteeRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Guarantee').getRecordTypeId();
   // public static Id CollectionsRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Collections').getRecordTypeId();
    //public static Id ArbitrationRTId = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Arbitration').getRecordTypeId();
    public static Id TaskRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Task').getRecordTypeId();
	
	@isTest static void test1() {
	
	User testUser = [SELECT id FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        Id accProRT = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId();
        Id accCustomerRT = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
        Id caseRT = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Marketplace Integrity').getRecordTypeId();
        Id miCaseQueueId = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'MarketplaceIntegrity'].Id;
        Decimal testProUserId = 100;
        Decimal testCustomerUserId = 200;
        Account aPro = new Account(Name='Chester Pro', usr_user_id__c=testProUserId, usr_email__c='protester@t.est', RecordTypeId=accProRT);
        Account aPro2 = new Account(Name='Chester Pro2', usr_user_id__c=123, usr_email__c='protester2@t.est', RecordTypeId=accProRT);
        Account aCustomer = new Account(Name='Tester Customer', usr_user_id__c=testCustomerUserId, usr_email__c='customertester@t.est', RecordTypeId=accCustomerRT);
        Account aCustomer2 = new Account(Name='Tester Customer2', usr_user_id__c=12345, usr_email__c='customertester2@t.est', RecordTypeId=accCustomerRT);
        insert new Account[]{aPro,aPro2,aCustomer,aCustomer2};
         Contact con = new Contact( LastName = 'Last',FirstName = 'First', AccountId = aPro.Id);
        insert con;
        Case aCase = new Case(accountId=aPro.Id, Subject='MI Test Case', Status = 'New', Origin = 'Email',RecordTypeId=caseRT);
        insert aCase;
        System.assert(null!=aCase.Id,'Test Case not inserted properly');
        Set<Id> primaryIds = new Set<Id>();
        MiIncident__c mii = new MiIncident__c(
            Name='Test',
            pro_user_id__c=String.valueOf(testProUserId), 
            customer_id__c = String.valueOf(testCustomerUserId),
            quotes_pro_user_id__c=testProUserId, 
            quotes_customer_id__c=testCustomerUserId, 
            quotes_bid_id__c = 1, 
            RequestID__c = '1',
            ResolutionTier__c = 'Tier 0 - Lost Communication',
            MICategory__c = 'Removed',
            MISubcategory__c = 'Other',
            Status__c = 'In Progress', 
            IncidentCategorization__c ='0 - Not enough details');     
            insert mii;
            primaryIds.add(mii.Id);
            mii.ProAccount__c =aPro2.Id; 
            mii.CustomerAccount__c = aCustomer2.Id;
            mii.ResolutionTier__c = 'Compensation Reason';
            mii.Status__c = 'Closed';
            mii.RecordTypeId = miRecordTypeId;
            mii.OutcomeCustomer__c = 'Flagged';
            mii.OutcomePro__c = 'Unresponsive';
            mii.CSATOfferedPro__c = false;
            mii.MICategory__c= 'Property damage';
            mii.DoNotSurveyPro__c = false;
            mii.ClosedDate__c= Date.today(); 
            mii.OutcomePro__c='Pro fixed work';
            update mii;   

            MiIncident__c mii2 = new MiIncident__c(
            Name='Testy', 
            pro_user_id__c='110', 
            customer_id__c = '210',
            quotes_pro_user_id__c=110, 
            quotes_customer_id__c=210, 
            quotes_bid_id__c = 2, 
            RequestID__c = '2',
            ResolutionTier__c = 'Tier 0 - Lost Communication',
            MICategory__c = 'Removed',
            MISubcategory__c = 'Other',
            Status__c = 'In Progress', 
            IncidentCategorization__c ='0 - Not enough details');     
            
            MIIncidentAction__c mia = new MIIncidentAction__c();
			mia.RecordTypeId = TaskRTId;
			mia.MIIncident__c = mii.Id;
			mia.Type__c = 'Follow-up';
			mia.Status__c = 'Open';
			insert mia;

			MIIncidentAction__c mia2 = new MIIncidentAction__c();
			mia2.MIIncident__c = mii.Id;
			mia2.Type__c = 'Note';
			mia2.Status__c = 'Open';
			mia2.RecordTypeId = TaskRTId;
			insert mia2;

			MIIncidentAction__c mia3 = new MIIncidentAction__c();
			mia3.MIIncident__c = mii.Id;
			//mia3.Type__c = 'Note';
			mia3.Status__c = 'Open';
			insert mia3;
        //System.runAs(testUser) { 
            Test.startTest();

                List<MIIncidentAction__c> miList = IncidentActionController.getActions(mii.Id, 'Open');
            
                List<IncidentActionController.NoteWrapper> miList2 = IncidentActionController.getNotes(mii.Id);
                MIIncidentAction__c miareturn = IncidentActionController.upsertAction(mia3, '2017-08-10');
                IncidentActionController.deleteAction(mia3.Id);
        
            Test.stopTest();
       // }
    }
	
}