metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship between Cases and Incidents.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>This record type is used for all thumbtack customers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/MIUtilityTest.cls
@isTest
private class MIUtilityTest
{
	static testMethod void testMiFields()
	{
		List<String> fields = MIUtility.miIncidentFields;

		System.assertNotEquals(0, fields.size());
	}

	static testMethod void testMiIncidentActionFields()
	{
		List<String> fields = MIUtility.miIncidentActionFields;

		System.assertNotEquals(0, fields.size());
	}

	static testMethod void testEmailMessageFields()
	{
		List<String> fields = MIUtility.emailMessageFields;

		System.assertNotEquals(0, fields.size());
	}

	static testMethod void testTaskFields()
	{
		List<String> fields = MIUtility.taskFields;

		System.assertNotEquals(0, fields.size());
	}

	static testMethod void testGetCaseIds()
	{
		Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
		Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
		insert new List<Account>{customer, pro};

		Contact cCust = new Contact(FirstName = 'Test', LastName = 'Customer', AccountId = customer.Id);
		Contact cPro = new Contact(FirstName = 'Test', LastName = 'Pro', AccountId = pro.Id);
		insert new List<Contact>{cCust, cPro};

		MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id, Status__c = 'New');
		insert incident;

		Case c1 = new Case(AccountId = customer.Id, ContactId = cCust.Id, Subject='MI Test Case 1', Status = 'New', Incident__c = incident.Id, Origin = 'Suggestion Box' );
		Case c2 = new Case(AccountId = pro.Id, ContactId = cPro.Id, Subject='MI Test Case 2', Status = 'New', Incident__c = incident.Id, Origin = 'Suggestion Box' );
		Case c3 = new Case(AccountId = pro.Id, ContactId = cPro.Id,  Subject='MI Test Case 3', Status = 'New', Incident__c = incident.Id, Origin = 'Suggestion Box' );
		insert new List<Case>{c1, c2, c3};

		Set<ID> caseIds = MIUtility.getCaseIds(incident.Id, null);

		System.assertEquals(3, caseIds.size());

		caseIds = MIUtility.getCaseIds(incident.Id, cPro.Id);

		System.assertEquals(2, caseIds.size());

		caseIds = MIUtility.getCaseIds(incident.Id, cCust.Id);

		System.assertEquals(1, caseIds.size());
	}
}