metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship between Cases and Incidents.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MICasePrimaryCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean to indicate the case is the primary Pro case for the MI Incident.</description>
        <label>MI Case Primary - Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MICasePrimaryPro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean to indicate true if the case is the primary customer case for the MI incident.</description>
        <label>MI Case Primary - Pro</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MIDoNotRelateIncident__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox used in code to indicate if the case should be disassociated from the open mi incident.</description>
        <label>MI: Do Not Relate Incident</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OwnerIsQueue__c</fullName>
        <description>True if owner is queue, false if owner is user</description>
        <formula>BEGINS(OwnerId,&quot;00G&quot;)</formula>
        <label>Owner Is Queue</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/IncidentCasesController.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-08-28   Mendel Guillaume       Created
========+============+=================+===============================================*/

public with sharing class IncidentCasesController
{
	@AuraEnabled
	public static List<Case> getRecords(String incidentId)
	{
		return [SELECT Id, CaseNumber, AccountId, Account.Name, Status, Owner.Name, MICasePrimaryCustomer__c,
					MICasePrimaryPro__c, OwnerId, OwnerIsQueue__c
				FROM Case WHERE Incident__c =: incidentId ORDER BY CaseNumber];
	}

	@AuraEnabled
	public static String detachCase(String caseId)
	{
		string result = 'success';

		try
		{
			Case c = new Case(ID = caseId, MIDoNotRelateIncident__c = true, Incident__c = null);

			update c;
		}
		catch(Exception ex)
		{
			result = ex.getMessage();
		}

		return result;
	}

	@AuraEnabled
	public static String saveCase(Case editCase)
	{
		string result = 'success';

		try
		{
			update editCase;
		}
		catch(Exception ex)
		{
			result = ex.getMessage();
		}

		return result;
	}

	@AuraEnabled
	public static List<Group> getQueues()
	{
		return [SELECT Id, Name
				FROM Group
				WHERE Type = 'Queue'
				AND Name IN ('Marketplace Integrity', 'Proactive MI Queue', 'Guarantee Queue', 'Low Dollar Satisfaction Queue',
								'Customer Support', 'Customer Support - Email', 'Pro Services')];
	}
}