metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSATEligible__c</fullName>
        <description>Formula field to display eligibility text if a case meets certain criteria for a survey offer.</description>
        <formula>IF(Contact.DoNotSurvey__c, &quot;Not Eligible&quot;, 
IF(ISPICKVAL(Origin, &quot;Outbound Phone&quot;), &quot;Not Eligible&quot;, 
IF(AutoClosed__c, &quot;Not Eligible&quot;, 
IF(Contact.ContactIsThumbtackStaff__c, &quot;Not Eligible&quot;, 
IF(SurveyOffered__c, &quot;Not Eligible&quot;, 
IF(IsTestData__c, &quot;Not Eligible&quot;,
IF(AND(NOT ISBLANK(Incident__c),
       Incident__r.RecordType.Name = &quot;MI Incident&quot;), &quot;Not Eligible&quot;, 
IF(ContactEmailRouting__c = &quot;Route to Sales &amp; Account Management&quot;, &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Marketplace Integrity&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Customer/Pro Requested&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Special Projects&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Abusive Pro/Customer&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;QA Audit&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Sys Admin Bulk Close&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(Origin, &quot;App Integration&quot;), &quot;Not Eligible&quot;, 
IF(ISBLANK(ClosedDate), &quot;Not Eligible&quot;, 
IF((NOW() - ClosedDate &gt;= 14), &quot;Not Eligible&quot;, 
IF(ISBLANK(Contact.Email), &quot;Not Eligible&quot;, 
IF(NOT ISBLANK( DuplicateOf__c ), &quot;Not Eligible&quot;, 
IF( ElapsedSurveyHours__c &lt;= 24, &quot;Not Eligible&quot;, 
IF( 
OR( 
ISPICKVAL(Category__c, &quot;Delete Account&quot;), 
ISPICKVAL(Category__c, &quot;Chat&quot;), 
AND( 
ISPICKVAL(Category__c, &quot;Phone&quot;), 
ISPICKVAL(SubCategory__c, &quot;Wrong number&quot;)), 
AND( 
ISPICKVAL(Category__c, &quot;Marketplace Integrity&quot;), 
 OR(ISPICKVAL(SubCategory__c, &quot;Duplicate&quot;),
    ISPICKVAL(SubCategory__c, &quot;Background check&quot;),
    ISPICKVAL(SubCategory__c, &quot;Certification agreement&quot;),
    ISPICKVAL(SubCategory__c, &quot;DMCA/Copyright&quot;), 
    ISPICKVAL(SubCategory__c, &quot;Negative review&quot;),
    ISPICKVAL(SubCategory__c, &quot;Concerning review&quot;),
    ISPICKVAL(SubCategory__c, &quot;Incident&quot;),
    ISPICKVAL(SubCategory__c, &quot;License&quot;),
    ISPICKVAL(SubCategory__c, &quot;Trademark&quot;),
    ISPICKVAL(SubCategory__c, &quot;Other&quot;))),
AND( 
ISPICKVAL(Category__c, &quot;Notifications&quot;), 
ISPICKVAL(SubCategory__c, &quot;Unsubscribe&quot;)), 
AND( 
ISPICKVAL(Category__c, &quot;Other&quot;), 
OR(ISPICKVAL(SubCategory__c, &quot;Background check (mismatch)&quot;), 
ISPICKVAL(SubCategory__c, &quot;Message intended for customer&quot;), 
ISPICKVAL(SubCategory__c, &quot;Message intended for pro&quot;), 
ISPICKVAL(SubCategory__c, &quot;Foreign language&quot;), 
ISPICKVAL(SubCategory__c, &quot;Press inquiries&quot;), 
ISPICKVAL(SubCategory__c, &quot;Noise&quot;), 
ISPICKVAL(SubCategory__c, &quot;Not enough info&quot;), 
ISPICKVAL(SubCategory__c, &quot;Proactive - no response&quot;))), 
AND( 
ISPICKVAL(Category__c,&quot;Quotes&quot;), 
ISPICKVAL(SubCategory__c,&quot;Quote intended for customer&quot;))), 
&quot;Not Eligible&quot;, 
IF( 
AND( 
TEXT(Category__c) = Contact.LastSurveyedCaseCategory__c, 
TEXT(SubCategory__c) = Contact.LastSurveyedCaseSubcategory__c, 
ElapsedSurveyHours__c &lt;= 48), &quot;Not Eligible&quot;, 
&quot;Eligible&quot;))))))))))))))))))))))</formula>
        <label>CSAT Eligible</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Categorization__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/CategorizationDefinition__c.object
<CustomObject>
    <description>Metadata object - the records from this object define what Categorization options are available for a given record.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not this Categorization Definition is currently available for use.</description>
        <inlineHelpText>Whether or not this Categorization Definition is currently available for use.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnCase__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, this definition is available on the Case object.</description>
        <inlineHelpText>If true, this definition is available on the Case object.</inlineHelpText>
        <label>Available On Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSATEligible__c</fullName>
        <description>The CSAT eligibility of this Definition</description>
        <inlineHelpText>The CSAT eligibility of this Definition</inlineHelpText>
        <label>CSAT Eligible</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                    <default>true</default>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Always Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Always Eligible</label>
                </value>
                <value>
                    <fullName>Always Ineligible</fullName>
                    <isActive>false</isActive>
                    <label>Always Ineligible</label>
                </value>
                <value>
                    <fullName>Ineligible if Primary</fullName>
                    <isActive>false</isActive>
                    <label>Ineligible if Primary</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CategoryType__c</fullName>
        <description>Category or Subcategory?</description>
        <inlineHelpText>Category or Subcategory?</inlineHelpText>
        <label>Category Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>Subcategory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this category available for Customers?</description>
        <label>Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Functional__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this a functional category?</description>
        <label>Functional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>The unique key of this Categorization Definition</description>
        <displayFormat>{YYYY}{MM}-{000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>The unique key of this Categorization Definition.</inlineHelpText>
        <label>Key</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ParentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Category for use with Subcategories.</description>
        <inlineHelpText>The parent Category for use with Subcategories.</inlineHelpText>
        <label>Parent Category</label>
        <referenceTo>CategorizationDefinition__c</referenceTo>
        <relationshipLabel>Subcategories</relationshipLabel>
        <relationshipName>Subcategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this category available for Pros?</description>
        <label>Pro</label>
        <type>Checkbox</type>
    </fields>
    <label>Categorization Definition</label>
    <nameField>
        <label>Categorization Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorization Definitions</pluralLabel>
    <recordTypes>
        <fullName>Category</fullName>
        <active>true</active>
        <description>Category/Subcategory</description>
        <label>Category</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/CategorizationCategoriesPanelCtrlTest.cls
/**
   Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+================================================
   1.0      2017-11-01   Mendel Guillaume   Created
   1.1      2018-01-03   Mendel Guillaume   Updated to follow template/guidelines
   ========+============+=================+===============================================
*/

@IsTest
private class CategorizationCategoriesPanelCtrlTest
{
	@TestSetup
	static void createData()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
			insert customer;

			Case c = new Case(AccountId = customer.Id, Subject='Test Case', Status = 'New', Origin = 'Suggestion Box' );
			insert c;

			List<CategorizationDefinition__c> categories = new List<CategorizationDefinition__c>();
			categories.add(new CategorizationDefinition__c(Name = 'Parent 1', Active__c = true, AvailableOnCase__c = true, Pro__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Parent 2', Active__c = true, AvailableOnCase__c = true, Customer__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Parent 3', Active__c = true, AvailableOnCase__c = true, Functional__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			insert categories;

			categories.add(new CategorizationDefinition__c(Name = 'Child 1a', Active__c = true, AvailableOnCase__c = true,
					Pro__c = true, ParentCategory__c = categories[0].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Child 2a', Active__c = true, AvailableOnCase__c = true,
					Pro__c = true, ParentCategory__c = categories[0].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Child 1b', Active__c = true, AvailableOnCase__c = true,
					Customer__c = true, ParentCategory__c = categories[1].Id,  CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Child 1c', Active__c = true, AvailableOnCase__c = true,
					Functional__c = true, ParentCategory__c = categories[2].Id,  CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			upsert categories;
		}
	}

	@IsTest
	static void testGetCategoryTypes()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Case c = [SELECT Id FROM Case];

			Test.startTest();

			List<CategorizationCategoriesPanelController.CategoryType> cTypes = CategorizationCategoriesPanelController.getCategoryTypes(c.Id);

			Test.stopTest();

			System.assertEquals(3, cTypes.size(), 'Invalid size');
			System.assertEquals('Pro', cTypes[0].name, 'Invalid name');
			System.assertEquals('Customer', cTypes[1].name, 'Invalid name');
			System.assertEquals('Other', cTypes[2].name, 'Invalid name');
			System.assertEquals(1, cTypes[0].categories.size(), 'Invalid size');
			System.assertEquals(1, cTypes[1].categories.size(), 'Invalid size');
			System.assertEquals(1, cTypes[2].categories.size(), 'Invalid size');
			System.assertEquals(2, cTypes[0].categories[0].subCategories.size(), 'Invalid size');
			System.assertEquals(1, cTypes[1].categories[0].subCategories.size(), 'Invalid size');
			System.assertEquals(1, cTypes[2].categories[0].subCategories.size(), 'Invalid size');
			System.assertEquals(false, cTypes[0].categories[0].subSelected, 'Category selected');
			System.assertEquals(false, cTypes[1].categories[0].subSelected, 'Category selected');
			System.assertEquals(false, cTypes[2].categories[0].subSelected, 'Category selected');
		}
	}

	//Inactive Categorization Definition
	@IsTest
	static void testGetCategoryTypes2()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Case c = [SELECT Id FROM Case];
			CategorizationDefinition__c cd = [SELECT Id, Key__c FROM CategorizationDefinition__c WHERE Name = 'Parent 2'];
			cd.Active__c = false;

			Test.startTest();

			update  cd;
			List<CategorizationCategoriesPanelController.CategoryType> cTypes = CategorizationCategoriesPanelController.getCategoryTypes(c.Id);

			Test.stopTest();

			System.assertEquals(2, cTypes.size(), 'Invalid size');
			System.assertEquals('Pro', cTypes[0].name, 'Invalid name');
			System.assertEquals('Other', cTypes[1].name, 'Invalid name');
		}
	}

	//Existing Categorization records
	@IsTest
	static void testGetCategoryTypes3()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Case c = [SELECT Id FROM Case];
			CategorizationDefinition__c cd = [SELECT Id, Key__c FROM CategorizationDefinition__c WHERE Name = 'Child 1b'];

			Test.startTest();
			CategorizationCategoriesListController.CategoryWrapper newCw = CategorizationCategoriesListController.addCategory(cd.Key__c, c.Id);
			String result = CategorizationCategoriesListController.updateCategorization(new List<Categorization__c> {newCw.category});
			List<CategorizationCategoriesPanelController.CategoryType> cTypes = CategorizationCategoriesPanelController.getCategoryTypes(c.Id);
			Test.stopTest();

			System.assertEquals('Success', result, 'Update failed');
			System.assertEquals(3, cTypes.size(), 'Invalid size');
			System.assertEquals('Pro', cTypes[0].name, 'Invalid name');
			System.assertEquals('Customer', cTypes[1].name, 'Invalid name');
			System.assertEquals('Other', cTypes[2].name, 'Invalid name');
			System.assertEquals(false, cTypes[0].categories[0].subSelected, 'Category selected');
			System.assertEquals(true, cTypes[1].categories[0].subSelected, 'Category not selected');
			System.assertEquals(false, cTypes[2].categories[0].subSelected, 'Category selected');
		}
	}
}