metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>DisputeIdHash__c</fullName>
        <description>Placeholder field for solution center front end to pass over the dispute ID hash so we can use that to lookup and set the Dispute__c value.  We do not write a value to this field, only used in VRMO controller.</description>
        <inlineHelpText>Placeholder field for solution center front end to pass over the dispute ID hash so we can use that to lookup and set the Dispute__c value.  We do not write a value to this field, only used in VRMO controller.</inlineHelpText>
        <label>Dispute Id Hash</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>MarketplaceIntegrity</fullName>
        <active>true</active>
        <businessProcess>Customer Support</businessProcess>
        <description>Record type for MI cases</description>
        <label>Marketplace Integrity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/ProductFeedback__c.object
<CustomObject>
    <description>Custom object to store feedback records from Thumbtack&apos;s Pros and Customers. Includes product feedback and request form/category feedback.</description>
    <fields>
        <fullName>ProductFeedback__c</fullName>
        <description>Product feedback received from customers/pros</description>
        <inlineHelpText>Enter any feedback received from the customer or pro here.</inlineHelpText>
        <label>Product Feedback</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/PublicArticle__kav.object
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Tab</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <description>These KB articles contain externally facing information for customers and pros.</description>
    <fields>
        <fullName>AndroidPublicContent__c</fullName>
        <label>Android (Public Content)</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Audience__c</fullName>
        <description>Picklist field to indicate the audience of the article, used for internal tracking purposes.</description>
        <label>Audience</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Customer Facing</fullName>
                </value>
                <value>
                    <fullName>Pro Facing</fullName>
                </value>
                <value>
                    <fullName>Customer and Pro Facing</fullName>
                </value>
                <value>
                    <fullName>Unsearchable</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ContainsVideo__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox field; when checked (true) will display a video icon next to the article title anywhere the article is visible in the public help center.</description>
        <label>Contains Video</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>HelpCenterPublicContent__c</fullName>
        <label>Help Center (Public Content)</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>MetaDescription__c</fullName>
        <description>Used in the article&apos;s meta tags - this allows us to override the description displayed on a social media card when the article is shared.</description>
        <inlineHelpText>Overrides the description displayed on a social media card when the article is shared. Limited to 155 characters.</inlineHelpText>
        <label>Meta Description</label>
        <length>155</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MetaTitle__c</fullName>
        <description>Used in the article&apos;s meta tags. Allows the title to be overridden on social media cards when the article is shared.</description>
        <inlineHelpText>Overrides the article&apos;s title on the social media card when the article is shared.</inlineHelpText>
        <label>Meta Title</label>
        <length>60</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>iPhonePublicContent__c</fullName>
        <label>iPhone (Public Content)</label>
        <length>131072</length>
        <type>Html</type>
    </fields>
    <label>Public Article</label>
    <pluralLabel>Public Articles</pluralLabel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/HCControllerRMO.cls
/*
    Copyright (c) 2017 Thumbtack,  All rights reserved.

Change List:
------------

Version    Date     Author            Description
=======+===========+=================+=================================
 ... previous log entries committed to git
1.5     11/21/17      pcoleman       Modified requestACall function to use
                                        Queueable instead of JSONObject trigger
1.6     2018-03-05    pcoleman       Added createCase() VFRMO override
=======+===========+=================+=================================*/
global with sharing class HCControllerRMO
{
    global class HelpCenterException extends Exception{}
    global static Map<String,Id> QIds {get;set;}
    global String metadesc {get;set;}
    global String metatitle {get;set;}
    global String metacanonical {get;set;}
    global String isWebview {get;set;}
    global String useragent {get;set;}
    global String mainScript {get;set;}
    global String mainStylesheet {get;set;}

    static {
        QIds = new Map<String,Id>();
        for( Group g: [SELECT Id, Name, DeveloperName, RelatedId,Type FROM Group WHERE Type = 'Queue' AND DeveloperName IN ('MarketplaceIntegrity','SupportContent','ProductFeedbackCase','ProductFeedback') LIMIT 4] )
        {
            QIds.put(g.DeveloperName,g.Id);
        }
    }

    global HCControllerRMO() {
        PageReference currentPage = ApexPages.currentPage();

        this.metatitle = 'Thumbtack Help Center';
        this.metadesc = 'Find answers quickly. Get back to doing what you love.';
        this.metacanonical = '';
        this.isWebview = currentPage.getHeaders().get('X-Is-Webview');

        String ar = currentPage.getParameters().get('ar');
        if (ar != null) {
            PublicArticle__kav article = getArticleById(ar);
            if (article != null) {
                this.metatitle = article.Title;
                this.metadesc = article.Summary;
                this.metacanonical = 'https://help.thumbtack.com/article/' + article.UrlName;
            }
        }
        String vw = currentPage.getParameters().get('vw');
        if(vw != null)
        {
            if (vw == 'sg')
            {
                this.metatitle = 'Suggestion Box';
                this.metadesc = 'How can we improve? Share your suggestions here.';
                this.metacanonical = 'https://help.thumbtack.com/suggestions';
            }
            else if (vw == 'pg')
            {
                this.metatitle = 'Report a dispute with a pro';
                this.metadesc = '';
                this.metacanonical = 'https://help.thumbtack.com/report-a-concern';
            }
            else if (vw == 'vd')
            {
                this.metatitle = 'Video Library';
                this.metadesc = 'Check out our videos to learn about Thumbtack and get useful tips.';
                this.metacanonical = 'https://help.thumbtack.com/videos';
            }
        }
    }

    public PageReference initialize()
    {
        return null;
    }

    global static PublicArticle__kav getArticleById(String knowledgeArticleId)
    {
        PublicArticle__kav article;
        for(PublicArticle__kav[] articles: [SELECT Id,MetaImage__Length__s,MetaImage__ContentType__s,MetaDescription__c,MetaImage__Name__s,MetaImage__Body__s,MetaTitle__c,KnowledgeArticleId,Title,Summary,UrlName,Audience__c, (Select DataCategoryName From DataCategorySelections) From PublicArticle__kav WHERE (Id = :knowledgeArticleId OR KnowledgeArticleId = :knowledgeArticleId OR UrlName = :knowledgeArticleId) AND IsVisibleInPkb = true AND PublishStatus ='Online' AND Language = 'en_US' LIMIT 1]) {
            for(PublicArticle__kav ar: articles)
            {
                article = ar;
                break;
            }
        }
        return article;
    }

    /**
 * @author Paul Coleman
 * @date 2018-02-21
 * @description Overriddes the default RemoteObjectController.create() function.
 * @param String The SObject type for record insertion.
 * @param Map<String, Object> A map of field names and values for the new record's insert.
 * @return Map<String, Object> An object that represents save result of the insert dml.
 */
    @RemoteAction
    global static Map<String, Object> caseCreate(String type, Map<String, Object> fields)
    {
        Map<String, Object> result = new Map<String, Object>{ 'id' => '500000000000000QAW', 'success' => true, 'errors' => new Map<String,String>() };
        Boolean isOverride = false;
        // do not allow dispute-based inserts by anyone other than portal users
        if( 'CspLitePortal'.equalsIgnoreCase( UserInfo.getUserType() ) )
        {
            if ( 'Case'.equalsIgnoreCase(type) )
            {
                Object disputeHash = fields.get('DisputeIdHash__c');
                if( NULL != disputeHash && (disputeHash instanceof String) )
                {
                    SolutionCenterUtility.insertDisputeCase(fields);
                    isOverride = true;
                }
            }
        }
        return isOverride ? result: RemoteObjectController.create(type, fields);
    }

    @RemoteAction
    global static String getArticleDraftById(String knowledgeArticleId)
    {
        return !'Standard'.equals(UserInfo.getUserType())?'[]':JSON.serialize([Select Id,KnowledgeArticleId,iPhonePublicContent__c,AndroidPublicContent__c,Title,Summary,UrlName,HelpCenterPublicContent__c,Audience__c,ContainsVideo__c, (Select DataCategoryName From DataCategorySelections) From PublicArticle__kav WHERE (Id = :knowledgeArticleId OR KnowledgeArticleId = :knowledgeArticleId OR UrlName = :knowledgeArticleId) AND IsVisibleInPkb = true AND PublishStatus ='Draft' AND Language = 'en_US']);
    }

    @RemoteAction
    global static String searchArticles(String searchTerm, String category, String audience, Integer lim)
    {
        String searchString = 'FIND {'+searchTerm+'} IN ALL FIELDS RETURNING PublicArticle__kav(Id,HelpCenterPublicContent__c,iPhonePublicContent__c,AndroidPublicContent__c,KnowledgeArticleId,Title,Summary,VersionNumber,UrlName,Audience__c,ContainsVideo__c WHERE IsVisibleInPkb=true AND PublishStatus = \'Online\' AND Language = \'en_US\' AND IsLatestVersion=true '+ (null!=audience && !''.equals(audience.trim())?' AND Audience__c IN (\''+audience+'\',\'Customer and Pro Facing\')' :'') +' ) WITH DATA CATEGORY Thumbtack__c BELOW ThumbtackSupport__c '+ (null==lim? '':' LIMIT '+String.valueOf(lim));
        return JSON.serialize((PublicArticle__kav[])(search.query( searchString )[0]));
    }

    @RemoteAction
    global static String searchKb(String searchTerm)
    {
        String term = searchTerm.replaceAll('([\\?\\&\\|\\!\\{\\}\\[\\]\\(\\)\\^\\~\\*\\:\\\"\'\\+\\-])', '\\$1');
        Sobject[] recs = (SObject[])[FIND :term IN ALL FIELDS RETURNING PublicArticle__kav(Id,HelpCenterPublicContent__c,iPhonePublicContent__c,AndroidPublicContent__c,KnowledgeArticleId,Title,Summary,VersionNumber,UrlName,Audience__c,ContainsVideo__c WHERE PublishStatus = 'Online' AND Language = 'en_US' AND IsLatestVersion=true AND Audience__c != 'Unsearchable') ][0];
        return JSON.serialize(recs);
    }

    @RemoteAction
    global static String createCallRequest(String leadJSON) {
        try { System.enqueueJob( new RequestACallQueueable( leadJSON ) ); } catch (Exception ex) {  TackBotUtility.postTackLogException(ex, 'HCControllerRMO.createCallRequest'); }
        return '{"id":"0012F000008uTC9QAM","success":true,"errors":[],"warnings":[]}';
    }

    @RemoteAction
    global static String getProductFeedbackPickLists()
    {
        Map<String,Schema.DescribeFieldResult> meta = new Map<String,Schema.DescribeFieldResult>();
        Schema.SObjectField[] fields = Schema.SObjectType.ProductFeedback__c.fields.getMap().values();
        for(Schema.SObjectField f: fields)
        {
            Schema.DescribeFieldResult d = f.getDescribe();
            if('picklist'==String.valueOf(d.getType()).toLowerCase() ) {meta.put(d.getName(),d);}
        }
        return JSON.serialize(meta);
    }
}