metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSATEligible__c</fullName>
        <description>Formula field to display eligibility text if a case meets certain criteria for a survey offer.</description>
        <formula>IF(Contact.DoNotSurvey__c, &quot;Not Eligible&quot;, 
IF(ISPICKVAL(Origin, &quot;Outbound Phone&quot;), &quot;Not Eligible&quot;, 
IF(AutoClosed__c, &quot;Not Eligible&quot;, 
IF(Contact.ContactIsThumbtackStaff__c, &quot;Not Eligible&quot;, 
IF(SurveyOffered__c, &quot;Not Eligible&quot;, 
IF(IsTestData__c, &quot;Not Eligible&quot;,
IF(AND(NOT ISBLANK(Incident__c),
       Incident__r.RecordType.Name = &quot;MI Incident&quot;), &quot;Not Eligible&quot;, 
IF(ContactEmailRouting__c = &quot;Route to Sales &amp; Account Management&quot;, &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Marketplace Integrity&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Customer/Pro Requested&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Special Projects&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Abusive Pro/Customer&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;QA Audit&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Sys Admin Bulk Close&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(Origin, &quot;App Integration&quot;), &quot;Not Eligible&quot;, 
IF(ISBLANK(ClosedDate), &quot;Not Eligible&quot;, 
IF((NOW() - ClosedDate &gt;= 14), &quot;Not Eligible&quot;, 
IF(ISBLANK(Contact.Email), &quot;Not Eligible&quot;, 
IF(NOT ISBLANK( DuplicateOf__c ), &quot;Not Eligible&quot;, 
IF( ElapsedSurveyHours__c &lt;= 24, &quot;Not Eligible&quot;, 
IF( 
OR( 
ISPICKVAL(Category__c, &quot;Delete Account&quot;), 
ISPICKVAL(Category__c, &quot;Chat&quot;), 
AND( 
ISPICKVAL(Category__c, &quot;Phone&quot;), 
ISPICKVAL(SubCategory__c, &quot;Wrong number&quot;)), 
AND( 
ISPICKVAL(Category__c, &quot;Marketplace Integrity&quot;), 
 OR(ISPICKVAL(SubCategory__c, &quot;Duplicate&quot;),
    ISPICKVAL(SubCategory__c, &quot;Background check&quot;),
    ISPICKVAL(SubCategory__c, &quot;Certification agreement&quot;),
    ISPICKVAL(SubCategory__c, &quot;DMCA/Copyright&quot;), 
    ISPICKVAL(SubCategory__c, &quot;Negative review&quot;),
    ISPICKVAL(SubCategory__c, &quot;Concerning review&quot;),
    ISPICKVAL(SubCategory__c, &quot;Incident&quot;),
    ISPICKVAL(SubCategory__c, &quot;License&quot;),
    ISPICKVAL(SubCategory__c, &quot;Trademark&quot;),
    ISPICKVAL(SubCategory__c, &quot;Other&quot;))),
AND( 
ISPICKVAL(Category__c, &quot;Notifications&quot;), 
ISPICKVAL(SubCategory__c, &quot;Unsubscribe&quot;)), 
AND( 
ISPICKVAL(Category__c, &quot;Other&quot;), 
OR(ISPICKVAL(SubCategory__c, &quot;Background check (mismatch)&quot;), 
ISPICKVAL(SubCategory__c, &quot;Message intended for customer&quot;), 
ISPICKVAL(SubCategory__c, &quot;Message intended for pro&quot;), 
ISPICKVAL(SubCategory__c, &quot;Foreign language&quot;), 
ISPICKVAL(SubCategory__c, &quot;Press inquiries&quot;), 
ISPICKVAL(SubCategory__c, &quot;Noise&quot;), 
ISPICKVAL(SubCategory__c, &quot;Not enough info&quot;), 
ISPICKVAL(SubCategory__c, &quot;Proactive - no response&quot;))), 
AND( 
ISPICKVAL(Category__c,&quot;Quotes&quot;), 
ISPICKVAL(SubCategory__c,&quot;Quote intended for customer&quot;))), 
&quot;Not Eligible&quot;, 
IF( 
AND( 
TEXT(Category__c) = Contact.LastSurveyedCaseCategory__c, 
TEXT(SubCategory__c) = Contact.LastSurveyedCaseSubcategory__c, 
ElapsedSurveyHours__c &lt;= 48), &quot;Not Eligible&quot;, 
&quot;Eligible&quot;))))))))))))))))))))))</formula>
        <label>CSAT Eligible</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>L1 category issue - this is where the general area goes.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account / Profile</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Customer Payments</fullName>
                </value>
                <value>
                    <fullName>Delete Account</fullName>
                </value>
                <value>
                    <fullName>Getting Started</fullName>
                </value>
                <value>
                    <fullName>Marketplace Integrity</fullName>
                </value>
                <value>
                    <fullName>Notifications</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Pricing and Payments</fullName>
                </value>
                <value>
                    <fullName>Instant Match</fullName>
                </value>
                <value>
                    <fullName>Quotes</fullName>
                </value>
                <value>
                    <fullName>Quoting Service</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>Requests</fullName>
                </value>
                <value>
                    <fullName>Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SubCategory__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>App pricing / purchase</fullName>
                </value>
                <value>
                    <fullName>Background check</fullName>
                </value>
                <value>
                    <fullName>Background check (clear)</fullName>
                </value>
                <value>
                    <fullName>Background check (mismatch)</fullName>
                </value>
                <value>
                    <fullName>Background check (not clear)</fullName>
                </value>
                <value>
                    <fullName>Called for customer</fullName>
                </value>
                <value>
                    <fullName>Called for pro</fullName>
                </value>
                <value>
                    <fullName>Called for specific employee</fullName>
                </value>
                <value>
                    <fullName>Canceled request</fullName>
                </value>
                <value>
                    <fullName>Cash refund</fullName>
                </value>
                <value>
                    <fullName>Certification agreement</fullName>
                </value>
                <value>
                    <fullName>Churn</fullName>
                </value>
                <value>
                    <fullName>Competitive report</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Concerning review</fullName>
                </value>
                <value>
                    <fullName>Connection issues - didn&apos;t talk</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - Call back needed</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - CC not provided</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - PA Live</fullName>
                </value>
                <value>
                    <fullName>Customer / other</fullName>
                </value>
                <value>
                    <fullName>Customer contact</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Disconnected (pro or customer)</fullName>
                </value>
                <value>
                    <fullName>Disconnected (specialist)</fullName>
                </value>
                <value>
                    <fullName>Dispute</fullName>
                </value>
                <value>
                    <fullName>DMCA/Copyright</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Duplicate request</fullName>
                </value>
                <value>
                    <fullName>Dynamic pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/CategorizationDefinition__c.object
<CustomObject>
    <description>Metadata object - the records from this object define what Categorization options are available for a given record.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not this Categorization Definition is currently available for use.</description>
        <inlineHelpText>Whether or not this Categorization Definition is currently available for use.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available On Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnCase__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, this definition is available on the Case object.</description>
        <inlineHelpText>If true, this definition is available on the Case object.</inlineHelpText>
        <label>Available On Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnEnrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this definition is available on the Enrollment Object.</description>
        <inlineHelpText>If checked, this definition is available on the Enrollment Object.</inlineHelpText>
        <label>Available On Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSATEligible__c</fullName>
        <description>The CSAT eligibility of this Definition</description>
        <inlineHelpText>The CSAT eligibility of this Definition</inlineHelpText>
        <label>CSAT Eligible</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                    <default>true</default>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Always Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Always Eligible</label>
                </value>
                <value>
                    <fullName>Always Ineligible</fullName>
                    <isActive>false</isActive>
                    <label>Always Ineligible</label>
                </value>
                <value>
                    <fullName>Ineligible if Primary</fullName>
                    <isActive>false</isActive>
                    <label>Ineligible if Primary</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CategoryType__c</fullName>
        <description>Category or Subcategory?</description>
        <inlineHelpText>Category or Subcategory?</inlineHelpText>
        <label>Category Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>Subcategory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this category available for Customers?</description>
        <label>Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>The unique key of this Categorization Definition</description>
        <displayFormat>{YYYY}{MM}-{000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>The unique key of this Categorization Definition.</inlineHelpText>
        <label>Key</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ParentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Category for use with Subcategories.</description>
        <inlineHelpText>The parent Category for use with Subcategories.</inlineHelpText>
        <label>Parent Category</label>
        <referenceTo>CategorizationDefinition__c</referenceTo>
        <relationshipLabel>Subcategories</relationshipLabel>
        <relationshipName>Subcategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PreventRecordCreation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this subcategory will not create a Categorization__c record when &apos;submit&apos; is set.</description>
        <inlineHelpText>If checked, this subcategory will not create a Categorization__c record when &apos;submit&apos; is set.</inlineHelpText>
        <label>Prevent Record Creation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this category available for Pros?</description>
        <label>Pro</label>
        <type>Checkbox</type>
    </fields>
    <label>Categorization Definition</label>
    <nameField>
        <label>Categorization Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorization Definitions</pluralLabel>
    <recordTypes>
        <fullName>Category</fullName>
        <active>true</active>
        <description>Category/Subcategory</description>
        <label>Category</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/CategorizationCategoriesListCtrlTest.cls
/**
   Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+================================================
   1.0      2017-11-01   Mendel Guillaume   Created
   1.1      2018-01-03   Mendel Guillaume   Updated to follow template/guidelines
   ========+============+=================+===============================================
*/

@IsTest
private class CategorizationCategoriesListCtrlTest
{
	@TestSetup
	static void createData()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
			insert customer;

			Case c = new Case(AccountId = customer.Id, Subject='Test Case', Status = 'New', Origin = 'Suggestion Box' );
			insert c;

			Enrollment__c enrollment = new Enrollment__c(enrollment_id__c = '1',
					Name = 'FN LN 1-1', Account__c = customer.Id, FirstName__c = 'Test First Name ', LastName__c = 'Test Last Name ' ,
					sav_available_service_id__c = 1, user_id__c = '1'  , rca_request_category_id__c = '1', zip_cbsa_code__c = '1',
					zip_cbsa_name__c = 'Utah');
			insert enrollment;

			List<CategorizationDefinition__c> parentCategories = new List<CategorizationDefinition__c>();
			parentCategories.add(new CategorizationDefinition__c(Name = 'Parent 1', Active__c = true, AvailableOnCase__c = true, Pro__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			parentCategories.add(new CategorizationDefinition__c(Name = 'Parent 2', Active__c = true, AvailableOnCase__c = true, Customer__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			parentCategories.add(new CategorizationDefinition__c(Name = 'Account Parent 1', Active__c = true, AvailableOnAccount__c = true, Pro__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			parentCategories.add(new CategorizationDefinition__c(Name = 'Account Parent 2', Active__c = true, AvailableOnAccount__c = true, Customer__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			parentCategories.add(new CategorizationDefinition__c(Name = 'Enrollment Parent 1', Active__c = true, AvailableOnEnrollment__c = true, Pro__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			parentCategories.add(new CategorizationDefinition__c(Name = 'Enrollment Parent 2', Active__c = true, AvailableOnEnrollment__c = true, Customer__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			insert parentCategories;

			List<CategorizationDefinition__c> categories = new List<CategorizationDefinition__c>();
			categories.add(new CategorizationDefinition__c(Name = 'Child 1a', Active__c = true, AvailableOnCase__c = true,
					Pro__c = true, ParentCategory__c = parentCategories[0].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Child 2a', Active__c = true, AvailableOnCase__c = true,
					Pro__c = true, ParentCategory__c = parentCategories[0].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Child 1b', Active__c = true, AvailableOnCase__c = true,
					Customer__c = true, ParentCategory__c = parentCategories[1].Id,  CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			categories.add(new CategorizationDefinition__c(Name = 'Account Child 1a', Active__c = true, AvailableOnAccount__c = true,
					Pro__c = true, ParentCategory__c = parentCategories[2].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Account Child 2a', Active__c = true, AvailableOnAccount__c = true,
					Pro__c = true, ParentCategory__c = parentCategories[2].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Account Child 1b', Active__c = true, AvailableOnAccount__c = true,
					Customer__c = true, ParentCategory__c = parentCategories[3].Id,  CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			categories.add(new CategorizationDefinition__c(Name = 'Enrollment Child 1a', Active__c = true, AvailableOnEnrollment__c = true,
					Pro__c = true, ParentCategory__c = parentCategories[4].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Enrollment Child 2a', Active__c = true, AvailableOnEnrollment__c = true,
					Pro__c = true, ParentCategory__c = parentCategories[4].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Enrollment Child 1b', Active__c = true, AvailableOnEnrollment__c = true,
					Customer__c = true, ParentCategory__c = parentCategories[5].Id,  CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			upsert categories;
		}
	}

	@IsTest
	static void testCategoriesListController()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Case c = [SELECT Id FROM Case];
			CategorizationDefinition__c cd = [SELECT Id, Key__c FROM CategorizationDefinition__c WHERE Name = 'Child 1b'];
			List<CategorizationCategoriesListController.CategoryWrapper> cws = CategorizationCategoriesListController.getCategories(c.Id);
			System.assertEquals(0, cws.size(), 'Categories found');

			CategorizationCategoriesListController.CategoryWrapper newCw = CategorizationCategoriesListController.addCategory(cd.Key__c, c.Id);
			System.assertNotEquals(null, newCw, 'New category not set');
			System.assertEquals(null, newCw.tooltip, 'New category has tooltip');
			System.assertEquals(null, newCw.sentimentScale, 'New category has sentiment scale');
			System.assertEquals(false, newCw.preventRecordCreation, 'New category prevent record creation is true');

			Test.startTest();

			String result = CategorizationCategoriesListController.updateCategorization(new List<Categorization__c> {newCw.category});

			Test.stopTest();

			System.assertEquals('Success', result, 'Update failed');

			cws = CategorizationCategoriesListController.getCategories(c.Id);
			System.assertEquals(1, cws.size(), 'Category size not 1');
			System.assertEquals(cd.Id, cws[0].catDefinition.Id, 'Invalid Category Definition Id');
			System.assertEquals(cd.Key__c, cws[0].category.DefinitionKey__c, 'Invalid key');
		}
	}

	@IsTest
	static void testCategoriesListControllerOnAccount()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Account a = [SELECT Id FROM Account];
			CategorizationDefinition__c cd = [SELECT Id, Key__c FROM CategorizationDefinition__c WHERE Name = 'Account Child 1b'];
			List<CategorizationCategoriesListController.CategoryWrapper> cws = CategorizationCategoriesListController.getCategories(a.Id);
			System.assertEquals(0, cws.size(), 'Categories found');

			CategorizationCategoriesListController.CategoryWrapper newCw = CategorizationCategoriesListController.addCategory(cd.Key__c, a.Id);
			System.assertNotEquals(null, newCw, 'New category not set');
			System.assertEquals(null, newCw.tooltip, 'New category has tooltip');
			System.assertEquals(null, newCw.sentimentScale, 'New category has sentiment scale');
			System.assertEquals(false, newCw.preventRecordCreation, 'New category prevent record creation is true');

			Test.startTest();

			String result = CategorizationCategoriesListController.updateCategorization(new List<Categorization__c> {newCw.category});

			Test.stopTest();

			System.assertEquals('Success', result, 'Update failed');

			cws = CategorizationCategoriesListController.getCategories(a.Id);
			System.assertEquals(1, cws.size(), 'Category size not 1');
			System.assertEquals(cd.Id, cws[0].catDefinition.Id, 'Invalid Category Definition Id');
			System.assertEquals(cd.Key__c, cws[0].category.DefinitionKey__c, 'Invalid key');
		}
	}

	@IsTest
	static void testCategoriesListControllerOnEnrollment()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Enrollment__c e = [SELECT Id FROM Enrollment__c];
			CategorizationDefinition__c cd = [SELECT Id, Key__c FROM CategorizationDefinition__c WHERE Name = 'Enrollment Child 1b'];
			List<CategorizationCategoriesListController.CategoryWrapper> cws = CategorizationCategoriesListController.getCategories(e.Id);
			System.assertEquals(0, cws.size(), 'Categories found');

			CategorizationCategoriesListController.CategoryWrapper newCw = CategorizationCategoriesListController.addCategory(cd.Key__c, e.Id);
			System.assertNotEquals(null, newCw, 'New category not set');
			System.assertEquals(null, newCw.tooltip, 'New category has tooltip');
			System.assertEquals(null, newCw.sentimentScale, 'New category has sentiment scale');
			System.assertEquals(false, newCw.preventRecordCreation, 'New category prevent record creation is true');

			Test.startTest();

			String result = CategorizationCategoriesListController.updateCategorization(new List<Categorization__c> {newCw.category});

			Test.stopTest();

			System.assertEquals('Success', result, 'Update failed');

			cws = CategorizationCategoriesListController.getCategories(e.Id);
			System.assertEquals(1, cws.size(), 'Category size not 1');
			System.assertEquals(cd.Id, cws[0].catDefinition.Id, 'Invalid Category Definition Id');
			System.assertEquals(cd.Key__c, cws[0].category.DefinitionKey__c, 'Invalid key');
		}
	}

	//Saving PreventRecordCreation__c category
	@IsTest
	static void testCategoriesListController2()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Case c = [SELECT Id, Category__c, SubCategory__c FROM Case];
			System.assertEquals(null, c.Category__c, 'Case category set');
			System.assertEquals(null, c.SubCategory__c, 'Case subcategory set');

			CategorizationDefinition__c cd = [SELECT Id, Key__c FROM CategorizationDefinition__c WHERE Name = 'Child 1b'];
			cd.PreventRecordCreation__c = true;
			cd.HelpText__c = 'Help';
			cd.SentimentScale__c = '2';
			update cd;

			List<CategorizationCategoriesListController.CategoryWrapper> cws = CategorizationCategoriesListController.getCategories(c.Id);
			System.assertEquals(0, cws.size(), 'Size not 0');

			CategorizationCategoriesListController.CategoryWrapper newCw = CategorizationCategoriesListController.addCategory(cd.Key__c, c.Id);
			System.assertNotEquals(null, newCw, 'New category not set');
			System.assertEquals('Help', newCw.tooltip, 'Invalid tooltip');
			System.assertEquals('2', newCw.sentimentScale, 'Invalid sentiment scale');
			System.assertEquals(true, newCw.preventRecordCreation, 'Prevent record creation not true');

			Test.startTest();
			String result = CategorizationCategoriesListController.updateCategorization(new List<Categorization__c> {newCw.category});
			Test.stopTest();

			cws = CategorizationCategoriesListController.getCategories(c.Id);
			System.assertEquals(0, cws.size(), 'Record created');

			c = [SELECT Id, Category__c, SubCategory__c FROM Case];
			System.assertEquals('Parent 2', c.Category__c, 'Case category not updated');
			System.assertEquals('Child 1b', c.SubCategory__c, 'Case subcategory not updated');
		}
	}

	@IsTest
	static void testgetOrigins()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			List<CategorizationCategoriesListController.Option> opts = CategorizationCategoriesListController.getOrigins();

			Test.stopTest();

			System.assert(opts.size() > 0, 'No origins found.');
		}
	}
}