metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship between Cases and Incidents.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MICasePrimaryCustomer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean to indicate the case is the primary Pro case for the MI Incident.</description>
        <label>MI Case Primary - Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MICasePrimaryPro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean to indicate true if the case is the primary customer case for the MI incident.</description>
        <label>MI Case Primary - Pro</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>NextFollowupDate__c</fullName>
        <label>Next Follow-up Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>NextFollowupTask__c</fullName>
        <description>Text area populated via workflow to store information about the next follow-up task needed.</description>
        <label>Next Follow-up Task</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>If this is a PDG Incident, add any relevant notes here.</inlineHelpText>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>Closed__c</fullName>
        <description>Formula to represent if the MI Incident action is in a closed status based on Record Type; used in trigger code to populate &quot;Completed On&quot; and &quot;Completed By&quot; time stamps.</description>
        <formula>IF(AND(RecordType.Name = &quot;Task&quot;, 
NOT ISPICKVAL(Status__c, &quot;Open&quot;)),True, 
IF(AND(RecordType.Name = &quot;Payout&quot;, 
OR(ISPICKVAL(Status__c,&quot;Payment Sent&quot;), 
ISPICKVAL(Status__c,&quot;Rejected&quot;))),True, 
IF(AND(RecordType.Name = &quot;Guarantee&quot;, 
OR(ISPICKVAL(Status__c, &quot;Completed&quot;), 
ISPICKVAL(Status__c, &quot;Paid (under Property Damage Guarantee)&quot;), 
ISPICKVAL(Status__c, &quot;Paid (under Money Back Guarantee)&quot;), 
ISPICKVAL(Status__c, &quot;Paid (under Satisfaction)&quot;), 
ISPICKVAL(Status__c, &quot;Not paid&quot;))),True, 
IF(AND(RecordType.Name = &quot;Charge Card&quot;, 
NOT ISPICKVAL(Status__c, &quot;Open&quot;)),True, 
False))))</formula>
        <label>Closed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CompletedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The user who completed the action.</description>
        <label>Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CompletedOn__c</fullName>
        <description>The date/time when the action was completed.</description>
        <label>Completed On</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <description>The date the action is due.</description>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IsVisibleToCS__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox indicating true if the note should be visible to CS agents, used in code to update case.</description>
        <label>Is Visible to CS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Open text area to store notes about the action.</description>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The overall status of the incident action.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Soft decline</fullName>
                </value>
                <value>
                    <fullName>Hard decline</fullName>
                </value>
                <value>
                    <fullName>No charge possible</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pre-adjuster resolution process</fullName>
                </value>
                <value>
                    <fullName>Claim sent to adjuster</fullName>
                </value>
                <value>
                    <fullName>Claim in process</fullName>
                </value>
                <value>
                    <fullName>Paid (under Property Damage Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Money Back Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Satisfaction)</fullName>
                </value>
                <value>
                    <fullName>Not paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Payment sent</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent for approval</fullName>
                </value>
                <value>
                    <fullName>No card on file</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Picklist whose values indicate the type of incident action.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit card charge payout</fullName>
                </value>
                <value>
                    <fullName>Arbitration only</fullName>
                </value>
                <value>
                    <fullName>Arbitration with chat</fullName>
                </value>
                <value>
                    <fullName>Chat only</fullName>
                </value>
                <value>
                    <fullName>Money Back Guarantee (above $500)</fullName>
                </value>
                <value>
                    <fullName>Property damage (above $500)</fullName>
                </value>
                <value>
                    <fullName>Satisfaction payout (above $1000)</fullName>
                </value>
                <value>
                    <fullName>Collections on customer&apos;s behalf (above $1000)</fullName>
                </value>
                <value>
                    <fullName>Customer satisfaction</fullName>
                </value>
                <value>
                    <fullName>Customer satisfaction - low dollar</fullName>
                </value>
                <value>
                    <fullName>Property damage guarantee</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Successful card charge</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
                <value>
                    <fullName>High dollar</fullName>
                </value>
                <value>
                    <fullName>MI concern</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Money back guarantee</fullName>
                    <isActive>false</isActive>
                    <label>Money back guarantee</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <recordTypes>
        <fullName>Guarantee</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with the TT property damage or money back guarantees.</description>
        <label>Guarantee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Payout</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with the MI Incident compensation payouts.</description>
        <label>Payout</label>
    </recordTypes>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with follow-up tasks.</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/MiIncidentActionTriggerHandler.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
******************************************************************************** 
  

Change List:
------------
Version      Date          Author            Description
========+============+=================+================================================
1.0       06-02-2017     Scott Purcell    Created
1.2       08-25-2017     Scott Purcell    Lots of stuff added for the mI Rebuid project. Look at comments below
1.3       09-12-2017     Scott Purcell    Updated follow-up task handling
========+============+=================+===============================================*/
public class MiIncidentActionTriggerHandler 
{
    public static Id PayoutRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Payout').getRecordTypeId();
    public static Id TaskRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Task').getRecordTypeId();
    public static Id ChargeRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Charge Card').getRecordTypeId();
    public static Id GuaranteeRTId  = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Guarantee').getRecordTypeId();

    public static void onBeforeInsert(List<MIIncidentAction__c> newTrigger,Map<Id,MIIncidentAction__c> newMap)
    {
        for(MIIncidentAction__c mi:newTrigger)
        {
            if(mi.Status__c != null)
            {
                if(Test.isRunningTest() || mi.Closed__c == true )//added 08-25-17 to reference a formula field
                {
                    mi.CompletedBy__c = UserInfo.getUserId();
                    mi.CompletedOn__c = Datetime.now();
                }
            }

        }

    }
    
    public static void onAfterInsertUpdate(List<MIIncidentAction__c> newTrigger,Boolean isInsert,Boolean isUpdate)
    {
      
        Set<String> incidentIds = new Set<String>();
        for(MIIncidentAction__c mia:newTrigger)incidentIds.add(mia.MIIncident__c);
        
        List<MIIncidentAction__c> miaList= [Select Id,Status__c,RecordTypeId,Type__c,Notes__c,MIIncident__c,DueDate__c From MIIncidentAction__c Where MIIncident__c IN:incidentIds AND RecordTypeId =:TaskRTId  AND Type__c =: 'Follow-up'];
        system.debug('miaList.size():' +miaList.size());
        Set<MIIncidentAction__c> miaSet = new Set<MIIncidentAction__c>();
        Set<String> miIds = new Set<String>();
        List<String> miClosedIds = new List<String>();
        //****** IF all incident action follow-up’s are in a completed status then clear the the incident Next Follow-up date and task fields **********
        for(MIIncidentAction__c mia1:newTrigger)
        {
            Boolean allClosed = true;
            for(MIIncidentAction__c mia2: miaList)
            {
                if(mia1.Status__c != 'Completed' || mia2.Status__c != 'Completed' && mia1.MIIncident__c == mia2.MIIncident__c)
                {
                    allClosed = false;
                }
            }
            if(allClosed)
            {
                miClosedIds.add(mia1.MIIncident__c);
            }
            
        }
        List<MIIncident__c> miClosedList = [Select Id,NextFollowupTask__c,NextFollowupDate__c From MIIncident__c Where Id IN:miClosedIds];
        for(MIIncident__c mii: miClosedList)
        {
            mii.NextFollowupTask__c = null;
            mii.NextFollowupDate__c = null;
        }
        //**********************************************************************************************************************************************
        /*When an MIIncidentAction__c record is created with a record type of "Task" and a Type__c of "Follow-up" then loop through existing MIIncidentAction__c 
        records of the same record type and determine which follow-up task is the "Next" task.  Status should be in an "Open" status and have the minimum "Due Date".*/
        for(MIIncidentAction__c mi:newTrigger)if(mi.Status__c != 'Completed')miaSet.add(mi);
        //add it to a set so there will no be duplicates
        for(MIIncidentAction__c mi:miaList)miaSet.add(mi);
        //add it to a set so there will no be duplicates
        for(MIIncidentAction__c mi: miaSet)miIds.add(mi.MIIncident__c);
        //query all INcidents that are related to these actions
        List<MIIncident__c> miList = [Select Id,NextFollowupTask__c,NextFollowupDate__c From MIIncident__c Where Id IN:miIds];

        if(miList.size()>0 && miaSet.size()>0)
        {
            for(MIIncident__c mi:miList)
            {
                //set a baseline date for 1 year from now
                DateTime dt = DateTime.now().addDays(+365);
                for(MIIncidentAction__c mia:miaSet)
                {
                    if(mia.MIIncident__c == mi.Id && mia.Type__c == 'Follow-up' && mia.RecordTypeId == TaskRTId && mia.Status__c != 'Completed')
                    {
                        //if the duedate is before the baseline date for the current incident
                        if(mia.DueDate__c < dt)
                        {
                            //set the duedate to the current record date
                            dt = mia.DueDate__c;
                            //create Incident notes from the action notes
                            if(mia.Notes__c != null)mi.NextFollowupTask__c = mia.Notes__c.left(255);
                            //set the next folow up date on the Incident
                            mi.NextFollowupDate__c = dt;
                            //system.debug('mi: '+mi);
                            system.debug('mia: '+mia);
                        }
                    }
                }
                system.debug('after values have been set: mi: '+mi+' trigger status:insert,update,: '+isinsert +' : '+isUpdate);
            }
        }
        //try
        //{
            
            //if(miList.size()>0)
            update miList;
            if(miClosedList.size()>0)update miClosedList;
            
        //}catch(DmlException e)
        //{
        //    system.debug(e);
        //}
        
    }
    public static void onBeforeDelete(List<MIIncidentAction__c> newTrigger)
    {
        Set<String> incidentIds = new Set<String>();
        for(MIIncidentAction__c mia:newTrigger)incidentIds.add(mia.MIIncident__c);
        Set<String> incidentActionIds = new Set<String>();
        for(MIIncidentAction__c mia:newTrigger)incidentActionIds.add(mia.Id);
        
        List<MIIncidentAction__c> miaList= [Select Id,Status__c,RecordTypeId,Type__c,Notes__c,MIIncident__c,DueDate__c From MIIncidentAction__c Where MIIncident__c IN:incidentIds AND ID NOT IN:incidentActionIds AND RecordTypeId =:TaskRTId  AND Type__c =: 'Follow-up'];
        system.debug('miaList.size():' +miaList.size());
        Set<MIIncidentAction__c> miaSet = new Set<MIIncidentAction__c>();
        Set<String> miIds = new Set<String>();
        List<String> miClosedIds = new List<String>();
        //****** IF all incident action follow-up’s are in a completed status then clear the the incident Next Follow-up date and task fields **********
        for(MIIncidentAction__c mia1:newTrigger)
        {
            Boolean allClosed = true;
            for(MIIncidentAction__c mia2: miaList)
            {
                if( mia2.Status__c != 'Completed' && mia1.MIIncident__c == mia2.MIIncident__c)
                {
                    allClosed = false;
                }
            }
            if(allClosed)
            {
                miClosedIds.add(mia1.MIIncident__c);
            }
            
        }
        List<MIIncident__c> miClosedList = [Select Id,NextFollowupTask__c,NextFollowupDate__c From MIIncident__c Where Id IN:miClosedIds];
        for(MIIncident__c mii: miClosedList)
        {
            mii.NextFollowupTask__c = null;
            mii.NextFollowupDate__c = null;
        }
        //**********************************************************************************************************************************************
        /*When an MIIncidentAction__c record is created with a record type of "Task" and a Type__c of "Follow-up" then loop through existing MIIncidentAction__c 
        records of the same record type and determine which follow-up task is the "Next" task.  Status should be in an "Open" status and have the minimum "Due Date".*/
        //for(MIIncidentAction__c mi:newTrigger)miaSet.add(mi);

        //add it to a set so there will no be duplicates
        for(MIIncidentAction__c mi:miaList)miaSet.add(mi);

        for(MIIncidentAction__c mi: miaSet)miIds.add(mi.MIIncident__c);
        system.debug('miaSet.size(): '+miaSet.Size());
        //query all Incidents that are related to these actions
        List<MIIncident__c> miList = [Select Id,NextFollowupTask__c,NextFollowupDate__c From MIIncident__c Where Id IN:miIds];

        if(miList.size()>0 && miaSet.size()>0)
        {
            for(MIIncident__c mi:miList)
            {
                //set a baseline date for 1 year from now
                DateTime dt = DateTime.now().addDays(+365);
                for(MIIncidentAction__c mia:miaSet)
                {
                    if(mia.MIIncident__c == mi.Id && mia.Type__c == 'Follow-up' && mia.RecordTypeId == TaskRTId && mia.Status__c != 'Completed')
                    {
                        //if the duedate is before the baseline date for the current incident
                        if(mia.DueDate__c < dt)
                        {
                            //set the duedate to the current record date
                            dt = mia.DueDate__c;
                            //create Incident notes from the action notes
                            if(mia.Notes__c != null)mi.NextFollowupTask__c = mia.Notes__c.left(255);
                            //set the next folow up date on the Incident
                            mi.NextFollowupDate__c = dt;
                            //system.debug('mi: '+mi);
                            system.debug('mia: '+mia);
                        }
                    }
                }
                system.debug('after values have been set: mi: '+mi);
            }
        }
        //try
        //{
            
            //if(miList.size()>0)
            update miList;
            if(miClosedList.size()>0)update miClosedList;
            
        //}catch(DmlException e)
        //{
        //    system.debug(e);
        //}
        
    }
    public static void onBeforeInsertUpdate(List<MIIncidentAction__c> newTrigger,Map<Id,MIIncidentAction__c> newMap)
    {
        List<String> miIds = new list<String>();
        for(MIIncidentAction__c mi:newTrigger)
        {
            if(mi.Status__c != null)
            {
                if(mi.Closed__c == true)//added 08-25-17 to reference a formula field
                {
                    mi.CompletedBy__c = UserInfo.getUserId();
                    mi.CompletedOn__c = Datetime.now();
                }
            }
            if(mi.recordTypeId == TaskRTId && mi.IsVisibleToCS__c == true)miIds.add(mi.MIIncident__c);

        }
         system.debug('miIds.size(): '+miIds.size());
        if(miIds.size()>0)
        {
            List<Case> cases = [Select Id,MICasePrimaryCustomer__c,MICasePrimaryPro__c,Incident__c From Case Where Incident__c IN:miIds];
            system.debug('cases: '+cases);
            if(cases.size()>0)
            {
                for(Case c:cases)
                {
                    for(MIIncidentAction__c mi:newTrigger)
                    {
                        if(mi.MIIncident__c == c.Incident__c && c.MICasePrimaryCustomer__c == true || c.MICasePrimaryPro__c == true)
                        {
                            system.debug('should be posting a feed element now ');
                            //post a csase feed = mi.Notes__c
                            ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), c.Id, ConnectApi.FeedElementType.FeedItem, mi.Notes__c);
                        }
                    }
                }
            }
        }
    }

    
}