metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship between Cases and Incidents.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MIDoNotRelateIncident__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox used in code to indicate if the case should be disassociated from the open mi incident.</description>
        <label>MI: Do Not Relate Incident</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/IncidentCasesControllerTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-09-04   Mendel Guillaume       Created
========+============+=================+===============================================*/

@IsTest
private class IncidentCasesControllerTest
{
	@TestSetup
	static void createData()
	{
		Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
		insert customer;

		Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
		insert pro;

		MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id);
		insert incident;

		Case c = new Case(AccountId = customer.Id, Subject='MI Test Case', Status = 'New', Incident__c = incident.Id, Origin = 'Suggestion Box' );
		insert c;
	}

	static testMethod void testGetRecords()
	{
		MIIncident__c incident = [SELECT Id FROM MIIncident__c];

		System.assertEquals(1, IncidentCasesController.getRecords(incident.Id).size());
	}

	static testMethod void testDetach()
	{
		Case c = [SELECT Id, MIDoNotRelateIncident__c, Incident__c FROM Case];

		System.assertEquals(false, c.MIDoNotRelateIncident__c);
		System.assertNotEquals(null, c.Incident__c);

		System.assertEquals('success', IncidentCasesController.detachCase(c.Id));

		c = [SELECT Id, MIDoNotRelateIncident__c, Incident__c FROM Case];

		System.assertEquals(true, c.MIDoNotRelateIncident__c);
		System.assertEquals(null, c.Incident__c);
	}

	static testMethod void testSave()
	{
		Case c = [SELECT Id, Status, MIDoNotRelateIncident__c, Incident__c FROM Case];

		System.assertEquals('New', c.Status);

		c.Status = 'Pending Customer';

		System.assertEquals('success', IncidentCasesController.saveCase(c));

		c = [SELECT Id, Status, MIDoNotRelateIncident__c, Incident__c FROM Case];

		System.assertEquals('Pending Customer', c.Status);
	}

	static testMethod void testGetQueues()
	{
		System.assert(IncidentCasesController.getQueues().size() > 0);
	}
}