metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship between Cases and Incidents.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>NewEmailFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox used in workflow rule updates to determine if a new email response has been received on a closed or in progress case.</description>
        <label>New Email Flag</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/IncidentFactorAssignment__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>NewEmailFlag__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate that one or more of the related cases has a new email response.</description>
        <label>New Email Flag</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>If this is a PDG Incident, add any relevant notes here.</inlineHelpText>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Open text area to store notes about the action.</description>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The overall status of the incident action.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Soft decline</fullName>
                </value>
                <value>
                    <fullName>Hard decline</fullName>
                </value>
                <value>
                    <fullName>No charge possible</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pre-adjuster resolution process</fullName>
                </value>
                <value>
                    <fullName>Claim sent to adjuster</fullName>
                </value>
                <value>
                    <fullName>Claim in process</fullName>
                </value>
                <value>
                    <fullName>Paid (under Property Damage Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Money Back Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Satisfaction)</fullName>
                </value>
                <value>
                    <fullName>Not paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Payment sent</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent for approval</fullName>
                </value>
                <value>
                    <fullName>No card on file</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Picklist whose values indicate the type of incident action.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit card charge payout</fullName>
                </value>
                <value>
                    <fullName>Arbitration only</fullName>
                </value>
                <value>
                    <fullName>Arbitration with chat</fullName>
                </value>
                <value>
                    <fullName>Chat only</fullName>
                </value>
                <value>
                    <fullName>Money Back Guarantee (above $500)</fullName>
                </value>
                <value>
                    <fullName>Property damage (above $500)</fullName>
                </value>
                <value>
                    <fullName>Satisfaction payout (above $1000)</fullName>
                </value>
                <value>
                    <fullName>Collections on customer&apos;s behalf (above $1000)</fullName>
                </value>
                <value>
                    <fullName>Customer satisfaction</fullName>
                </value>
                <value>
                    <fullName>Customer satisfaction - low dollar</fullName>
                </value>
                <value>
                    <fullName>Property damage guarantee</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Successful card charge</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
                <value>
                    <fullName>High dollar</fullName>
                </value>
                <value>
                    <fullName>MI concern</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Money back guarantee</fullName>
                    <isActive>false</isActive>
                    <label>Money back guarantee</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with follow-up tasks.</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentDetailsController.cls
public class IncidentDetailsController {

	@AuraEnabled
	public static String closeMIIncident(Id incidentId) {
		update new MIIncident__c(Id=incidentId,Status__c='Closed',NewEmailFlag__c=false);
		return [SELECT Status__c FROM MIIncident__c WHERE Id = :incidentId LIMIT 1].Status__c;
	}

	@AuraEnabled
	public static List<IncidentFeedItem> getFeed(Id incidentId, Id contactId, String filter, String tabName) {

		List<IncidentFeedItem> result = new List<IncidentFeedItem> ();
		if (incidentId != null && String.isNotBlank(filter)) {

			Set<Id> primaryIds = new Set<Id> {incidentId};
			Map<Id, Case> casesMap = MIUtility.getCases(incidentId, contactId);

			//primaryIds.addAll(MIUtility.getCaseIds(incidentId, contactId));
			primaryIds.addAll(casesMap.keySet());
			result.addAll(getEmails(primaryIds, filter).values());

			if(tabName != 'Pro' && tabName != 'Customer')
			{
				result.addAll(getIncidentActionAndHistory(primaryIds, filter).values());
				result.addAll(getIncidentFactors(primaryIds, filter).values());
			}

			result.addAll(getPhoneCalls(casesMap, primaryIds, filter).values());
			result.addAll(getCaseFeedRecords(primaryIds, filter).values());
			result.addAll(getCaseCommentRecords(primaryIds, filter).values());
			result.sort();

		}
		return result;

	}

	public static Map<Id, IncidentFeedItem> getEmails(Set<Id> primaryIds, String filter) {

		Map<Id, IncidentFeedItem> result = new Map<Id, IncidentFeedItem> ();
		if (primaryIds != null && !primaryIds.isEmpty() && String.isNotBlank(filter) && (filter.equalsIgnoreCase('all') || filter.equalsIgnoreCase('emails'))) {

			for (EmailMessage email : (List<EmailMessage>) Database.query(
										'Select ' + String.join(MIUtility.emailMessageFields, ', ') + ' From EmailMessage '
										+ 'Where ParentId IN :primaryIds AND Status != \'5\' '
									)) {

				IncidentFeedItem item = new IncidentFeedItem ();
				item.itemType = 'email';
				item.sortDate = email.MessageDate;
				item.personName = email.FromName;
				item.summary = email.TextBody;

				if(String.isNotBlank(email.HtmlBody))
				{
					item.details = email.HtmlBody;
					item.detailType = 'html';
				}
				else
				{
					item.details = email.TextBody;
					item.detailType = 'text';
				}
				item.email = email;
				item.accountId = email.Parent.AccountId;
				item.contactId = email.Parent.ContactId;
				result.put(email.Id, item);

			}

		}
		return result;

	}

	public static Map<Id, IncidentFeedItem> getIncidentActionAndHistory(Set<Id> primaryIds, String filter) {

		Map<Id, IncidentFeedItem> result = new Map<Id, IncidentFeedItem> ();
		if (primaryIds != null && !primaryIds.isEmpty()) {

			Map<Id, IncidentFeedItem> actionMap = getIncidentActions(primaryIds, filter);
			result.putAll(actionMap);
			result.putAll(getIncidentActionHistory(primaryIds));

		}
		return result;

	}

	public static Map<Id, IncidentFeedItem> getIncidentActions(Set<Id> primaryIds, String filter) {

		Map<Id, IncidentFeedItem> result = new Map<Id, IncidentFeedItem> ();
		if (primaryIds != null && !primaryIds.isEmpty() && String.isNotBlank(filter) && (filter.equalsIgnoreCase('all') || filter.equalsIgnoreCase('actions') || filter.equalsIgnoreCase('tasks') || filter.equalsIgnoreCase('notes'))) {

			for (MIIncidentAction__c action : (List<MIIncidentAction__c>) Database.query(
										'Select ' + String.join(MIUtility.miIncidentActionFields, ', ') + ' From MIIncidentAction__c '
										+ 'Where MIIncident__c IN :primaryIds '
									)) {

				if ((filter.equalsIgnoreCase('all') || filter.equalsIgnoreCase('actions')) && action.RecordType.DeveloperName != 'Task') {

					IncidentFeedItem item = new IncidentFeedItem ();
					item.action = action;
					item.sortDate = action.CreatedDate;
					item.personName = action.CreatedBy.Name;
					item.itemType = 'action';
					item.summary = action.Name;
					item.details = action.Id;
					item.detailType = 'link';
					result.put(action.Id, item);

				}
				if ((filter.equalsIgnoreCase('all') || filter.equalsIgnoreCase('notes')) && action.RecordType.DeveloperName == 'Task' && action.Type__c == 'Note') {

					IncidentFeedItem item = new IncidentFeedItem ();
					item.action = action;
					item.sortDate = action.CreatedDate;
					item.personName = action.CreatedBy.Name;
					item.itemType = 'note';
					item.summary = action.Notes__c;
					item.details = action.Notes__c;
					item.detailType = 'text';
					result.put(action.Id, item);

				}
				if ((filter.equalsIgnoreCase('all') || filter.equalsIgnoreCase('tasks')) && action.RecordType.DeveloperName == 'Task' && action.Type__c == 'Follow-up') {

					IncidentFeedItem item = new IncidentFeedItem ();
					item.action = action;
					item.sortDate = action.CreatedDate;
					item.personName = action.CreatedBy.Name;
					item.itemType = 'task';
					item.summary = action.Notes__c;
					item.details = action.Notes__c;
					item.detailType = 'text';
					result.put(action.Id, item);

				}

			}

		}
		return result;

	}

	public static Map<Id, IncidentFeedItem> getIncidentActionHistory(Set<Id> incidentActionIds) {

		Map<Id, IncidentFeedItem> result = new Map<Id, IncidentFeedItem> ();
		if (incidentActionIds != null && !incidentActionIds.isEmpty()) {

			for (MIIncidentAction__History history : [Select Id, OldValue, NewValue, ParentId, Field, CreatedDate, CreatedBy.Name
														From MIIncidentAction__History
														Where ParentId IN :incidentActionIds]) {

				IncidentFeedItem item = new IncidentFeedItem ();
				item.itemType = 'history';
				item.history = history;
				item.sortDate = history.CreatedDate;
				item.personName = history.CreatedBy.Name;
				item.summary = 'Changed ' + history.Field + ' from ' + history.OldValue + ' to ' + history.NewValue;
				item.details = item.summary;
				item.detailType = 'text';
				result.put(history.Id, item);

			}

		}
		return result;

	}

	public static Map<Id, IncidentFeedItem> getPhoneCalls(Map<Id, Case> casesMap, Set<Id> primaryIds, String filter) {

		Map<Id, IncidentFeedItem> result = new Map<Id, IncidentFeedItem> ();

		if (primaryIds != null && !primaryIds.isEmpty() && String.isNotBlank(filter) && (filter.equalsIgnoreCase('all') || filter.equalsIgnoreCase('calls'))) {

			for (Task phoneCall : (List<Task>) Database.query(
									'Select ' + String.join(MIUtility.taskFields, ', ') + ' From Task '
									+ 'Where Type = \'Call\' '
									+ 'And WhatId IN :primaryIds '
								)) {

				Case c = casesMap.get(phoneCall.WhatId);
				IncidentFeedItem item = new IncidentFeedItem ();
				item.itemType = 'call';
				item.sortDate = phoneCall.CreatedDate;
				item.personName = phoneCall.CreatedBy.Name;
				item.summary = phoneCall.Description;
				item.details = phoneCall.Description;
				item.detailType = 'text';
				item.phoneCall = phoneCall;
				item.accountId = c == null ? null : c.AccountId;
				item.contactId = c == null ? null : c.ContactId;
				result.put(phoneCall.Id, item);

			}

		}
		return result;

	}

	public static Map<Id, IncidentFeedItem> getCaseFeedRecords(Set<Id> primaryIds, String filter)
	{
		Map<Id, IncidentFeedItem> result = new Map<Id, IncidentFeedItem> ();

		if (primaryIds != null && !primaryIds.isEmpty() && String.isNotBlank(filter) && (filter.equalsIgnoreCase('all') || filter.equalsIgnoreCase('notes')))
		{
			Set<String> types = new Set<String>{'CallLogPost', 'TextPost'};

			if(filter.equalsIgnoreCase('notes'))
			{
				types.remove('CallLogPost');
			}

			for (CaseFeed cf : [SELECT Id, Title, Body, CreatedDate, CreatedBy.Name, IsRichText, ParentId, Parent.AccountId,
					Parent.ContactId, Type
					FROM CaseFeed WHERE ParentId IN :primaryIds AND Type IN :types])
			{
				IncidentFeedItem item = new IncidentFeedItem();
				item.itemType = cf.Type;
				item.sortDate = cf.CreatedDate;
				item.personName = cf.CreatedBy.Name;
				item.summary = cf.Body != null ? cf.Body.stripHtmlTags() : '';
				item.details = cf.Body;
				item.detailType = cf.IsRichText ? 'html' : 'text';
				item.caseFeed = cf;
				item.accountId = cf.Parent.AccountId;
				item.contactId = cf.Parent.ContactId;
				result.put(cf.Id, item);
			}

		}

		return result;
	}

	public static Map<Id, IncidentFeedItem> getCaseCommentRecords(Set<Id> primaryIds, String filter)
	{
		Map<Id, IncidentFeedItem> result = new Map<Id, IncidentFeedItem> ();

		if (primaryIds != null && !primaryIds.isEmpty() && String.isNotBlank(filter) && (filter.equalsIgnoreCase('all') || filter.equalsIgnoreCase('notes')))
		{
			for (CaseComment cc : [SELECT Id, CommentBody, CreatedDate, CreatedBy.Name, ParentId, Parent.AccountId, Parent.ContactId
									FROM CaseComment WHERE ParentId IN :primaryIds])
			{
				IncidentFeedItem item = new IncidentFeedItem();
				item.itemType = 'CaseCommentPost';
				item.sortDate = cc.CreatedDate;
				item.personName = cc.CreatedBy.Name;
				item.summary = cc.CommentBody != null ? cc.CommentBody.stripHtmlTags() : '';
				item.details = cc.CommentBody;
				item.detailType = 'text';
				item.caseComment = cc;
				item.accountId = cc.Parent.AccountId;
				item.contactId = cc.Parent.ContactId;
				result.put(cc.Id, item);
			}

		}

		return result;
	}

	public static Map<Id, IncidentFeedItem> getIncidentFactors(Set<Id> primaryIds, String filter)
	{
		Map<Id, IncidentFeedItem> result = new Map<Id, IncidentFeedItem> ();

		if (primaryIds != null && !primaryIds.isEmpty() && String.isNotBlank(filter) && filter.equalsIgnoreCase('all'))
		{
			List<IncidentFactorAssignment__c> assignments = [
					SELECT Id, Factor__r.Name, Owner.Name, CreatedDate
					FROM IncidentFactorAssignment__c
					WHERE Incident__c IN :primaryIds AND IsDeleted__c != true
					ORDER BY Owner.Name, Factor__r.Name
			];

			for(IncidentFactorAssignment__c a : assignments)
			{
				IncidentFeedItem item = new IncidentFeedItem();
				item.itemType = 'IncidentFactor';
				item.sortDate = a.CreatedDate;
				item.personName = a.Owner.Name;
				item.summary = a.Factor__r.Name;
				item.details = a.Factor__r.Name;
				item.detailType = 'text';
				item.factorAssignment = a;
				result.put(a.Id, item);
			}
		}

		return result;
	}
}