metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>MICategory__c</fullName>
        <description>Marketplace Integrity Category</description>
        <inlineHelpText>Marketplace Integrity Category</inlineHelpText>
        <label>MI Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Background</fullName>
                </value>
                <value>
                    <fullName>Certification Agreement</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Dispute About Customer</fullName>
                </value>
                <value>
                    <fullName>Dispute About Professional</fullName>
                </value>
                <value>
                    <fullName>Follow Up with Customer</fullName>
                </value>
                <value>
                    <fullName>Follow Up with Professional</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>MICategory__c</fullName>
        <description>Marketplace Integrity Incident categories.</description>
        <label>MI Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concern about user</fullName>
                </value>
                <value>
                    <fullName>Deposit no show</fullName>
                </value>
                <value>
                    <fullName>Payment issues</fullName>
                </value>
                <value>
                    <fullName>Physical harm / Inappropriate contact</fullName>
                </value>
                <value>
                    <fullName>Property damage</fullName>
                </value>
                <value>
                    <fullName>Theft</fullName>
                </value>
                <value>
                    <fullName>Unprofessional behavior</fullName>
                </value>
                <value>
                    <fullName>Unsatisfactory work</fullName>
                </value>
                <value>
                    <fullName>Work not complete</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>If this is a PDG Incident, add any relevant notes here.</inlineHelpText>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>OutcomeCustomer__c</fullName>
        <description>The outcome of the dispute resolution for the customer.</description>
        <label>Outcome - Customer</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Arbitration judgement</fullName>
                </value>
                <value>
                    <fullName>Flagged</fullName>
                </value>
                <value>
                    <fullName>No action</fullName>
                </value>
                <value>
                    <fullName>Pursued outside of Thumbtack</fullName>
                </value>
                <value>
                    <fullName>Resolution reached</fullName>
                </value>
                <value>
                    <fullName>Thumbtack compensation</fullName>
                </value>
                <value>
                    <fullName>Thumbtack compensation (low dollar)</fullName>
                </value>
                <value>
                    <fullName>Unable to facilitate resolution</fullName>
                </value>
                <value>
                    <fullName>Unresponsive</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OutcomePro__c</fullName>
        <description>The outcome of the dispute resolution for the Pro.</description>
        <label>Outcome - Pro</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Flagged</fullName>
                </value>
                <value>
                    <fullName>No action</fullName>
                </value>
                <value>
                    <fullName>Pro fixed work</fullName>
                </value>
                <value>
                    <fullName>Pro offered other resolution</fullName>
                </value>
                <value>
                    <fullName>Pro resolved with refund</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Open text area to store notes about the action.</description>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The overall status of the incident action.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Soft decline</fullName>
                </value>
                <value>
                    <fullName>Hard decline</fullName>
                </value>
                <value>
                    <fullName>No charge possible</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pre-adjuster resolution process</fullName>
                </value>
                <value>
                    <fullName>Claim sent to adjuster</fullName>
                </value>
                <value>
                    <fullName>Claim in process</fullName>
                </value>
                <value>
                    <fullName>Paid (under Property Damage Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Money Back Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Satisfaction)</fullName>
                </value>
                <value>
                    <fullName>Not paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Payment sent</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent for approval</fullName>
                </value>
                <value>
                    <fullName>No card on file</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with follow-up tasks.</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/QuickCaseSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>AssignedApp__c</fullName>
        <label>Assigned App</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Incident Manager</fullName>
                    <default>true</default>
                    <label>Incident Manager</label>
                </value>
                <value>
                    <fullName>Customer Support</fullName>
                </value>
                <value>
                    <fullName>WorkItem</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Quick Case Setting</label>
    <pluralLabel>Quick Case Settings</pluralLabel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentSectionsControllerTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-09-04   Mendel Guillaume       Created
========+============+=================+===============================================*/

@IsTest
private class IncidentSectionsControllerTest
{
	@TestSetup
	static void createData()
	{
		Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
		insert customer;

		Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
		insert pro;

		MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id, Status__c = 'New');
		insert incident;
	}

	static testMethod void testSave()
	{
		MIIncident__c incident = [SELECT Id, Status__c FROM MIIncident__c];

		System.assertEquals('New', incident.Status__c);

		incident.Status__c = 'In Progress';

		System.assertEquals('Success', IncidentSectionsController.saveIncident(incident));

		incident = [SELECT Id, Status__c FROM MIIncident__c];

		System.assertEquals('In Progress', incident.Status__c);
	}

	static testMethod void testClose()
	{
		MIIncident__c incident = [SELECT Id, Status__c FROM MIIncident__c];

		System.assertEquals('New', incident.Status__c);

		incident.Status__c = 'Closed';
		incident.MICategory__c = 'Unsatisfactory work';
		incident.OutcomeCustomer__c = 'Unresponsive';
		incident.OutcomePro__c = 'Removed';

		System.assertEquals('Success', IncidentSectionsController.closeIncident(incident, 'Test Note', false));

		incident = [SELECT Id, Status__c FROM MIIncident__c];

		System.assertEquals('Closed', incident.Status__c);

		MIIncidentAction__c task = [SELECT Notes__c FROM MIIncidentAction__c
									WHERE RecordTypeId = :MiIncidentActionTriggerHandler.TaskRTId];

		System.assertEquals('Test Note', task.Notes__c);
	}

	static testMethod void testGetIncident()
	{
		MIIncident__c incident = [SELECT Id FROM MIIncident__c];
		System.assertNotEquals(null, IncidentSectionsController.getIncident(incident.Id));
	}

	static testMethod void testGetPriorities()
	{
		System.assertNotEquals(0, IncidentSectionsController.getPriorities().size());
	}

	static testMethod void testGetOrigins()
	{
		System.assertNotEquals(0, IncidentSectionsController.getOrigins().size());
	}

	static testMethod void testGetCategories()
	{
		System.assertNotEquals(0, IncidentSectionsController.getCategories().size());
	}

	static testMethod void testGetSubcategories()
	{
		System.assertNotEquals(0, IncidentSectionsController.getSubcategories().size());
	}

	static testMethod void testGetStatuses()
	{
		System.assertNotEquals(0, IncidentSectionsController.getStatuses().size());
	}

	static testMethod void testGetProOutcomes()
	{
		System.assertNotEquals(0, IncidentSectionsController.getProOutcomes().size());
	}

	static testMethod void testGetCustOutcomes()
	{
		System.assertNotEquals(0, IncidentSectionsController.getCustOutcomes().size());
	}

	static testMethod void testGetModiaStatuses()
	{
		System.assertNotEquals(0, IncidentSectionsController.getModiaStatuses().size());
	}

	static testMethod void testGetEscalationTypes()
	{
		System.assertNotEquals(0, IncidentSectionsController.getEscalationTypes().size());
	}

	static testMethod void testGetCategoryMap()
	{
		System.assertNotEquals(0, IncidentSectionsController.getCategoryMap().size());
	}

	static testMethod void testGetCategorySubs()
	{
		System.assert(IncidentSectionsController.getCategorySubs('Concern about user').size() > 0);
	}

	static testMethod void testCreateUpdateQuickCase()
	{
		List<QuickCaseSetting__mdt> settings = [SELECT Id FROM QuickCaseSetting__mdt WHERE IsActive__c = TRUE AND AssignedApp__c = 'Incident Manager' LIMIT 1];

		if(!settings.isEmpty())
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];
			incident = IncidentSectionsController.getIncident(incident.Id);

			ResponseUtility response = IncidentSectionsController.createQuickCase(incident, settings[0].Id);
			System.assertEquals(true, response.success);

			System.assertEquals(true, IncidentSectionsController.updateQuickCase(((case) response.record).Id).success);
		}
	}
}