metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>MICategory__c</fullName>
        <description>Marketplace Integrity Category</description>
        <inlineHelpText>Marketplace Integrity Category</inlineHelpText>
        <label>MI Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Background</fullName>
                </value>
                <value>
                    <fullName>Certification Agreement</fullName>
                </value>
                <value>
                    <fullName>Credit Card</fullName>
                </value>
                <value>
                    <fullName>Dispute About Customer</fullName>
                </value>
                <value>
                    <fullName>Dispute About Professional</fullName>
                </value>
                <value>
                    <fullName>Follow Up with Customer</fullName>
                </value>
                <value>
                    <fullName>Follow Up with Professional</fullName>
                </value>
                <value>
                    <fullName>Legal</fullName>
                </value>
                <value>
                    <fullName>License</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MISubcategory__c</fullName>
        <description>Marketplace Integrity Subcategory</description>
        <inlineHelpText>Marketplace Integrity Subcategory</inlineHelpText>
        <label>MI Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MICategory__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Account Operating w/o Owner&apos;s Permission</fullName>
                </value>
                <value>
                    <fullName>Attorney General</fullName>
                </value>
                <value>
                    <fullName>Badge Applied</fullName>
                </value>
                <value>
                    <fullName>BBB</fullName>
                </value>
                <value>
                    <fullName>Charged Unfairly</fullName>
                </value>
                <value>
                    <fullName>Check/Payment Scam</fullName>
                </value>
                <value>
                    <fullName>Collateral Damage</fullName>
                </value>
                <value>
                    <fullName>Community Guidlines Violation</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
                <value>
                    <fullName>Customer ceased contact</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>DMCA - Owner</fullName>
                </value>
                <value>
                    <fullName>DMCA - Response</fullName>
                </value>
                <value>
                    <fullName>DOJ - No longer on site</fullName>
                </value>
                <value>
                    <fullName>Failed BGC</fullName>
                </value>
                <value>
                    <fullName>Fraud - Braintree</fullName>
                </value>
                <value>
                    <fullName>Fraud - Card Owner</fullName>
                </value>
                <value>
                    <fullName>Good Samaritan Report - Background</fullName>
                </value>
                <value>
                    <fullName>Good Samaritan Report - License</fullName>
                </value>
                <value>
                    <fullName>Harassment</fullName>
                </value>
                <value>
                    <fullName>Insufficient Info</fullName>
                </value>
                <value>
                    <fullName>MBG Pilot</fullName>
                </value>
                <value>
                    <fullName>Money Back Guarantee</fullName>
                </value>
                <value>
                    <fullName>No Badge</fullName>
                </value>
                <value>
                    <fullName>No Contact</fullName>
                </value>
                <value>
                    <fullName>No documentation provided</fullName>
                </value>
                <value>
                    <fullName>No Longer on Site</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paid Pro - No Show/Late</fullName>
                </value>
                <value>
                    <fullName>Paid Pro - Unsatisfactory Work</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>MarketplaceIntegrity</fullName>
        <active>true</active>
        <businessProcess>Customer Support</businessProcess>
        <description>Record type for MI cases</description>
        <label>Marketplace Integrity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>usr_user_id</description>
        <externalId>true</externalId>
        <label>User ID (Unique)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>This record type is used for all thumbtack customers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/CSAT__c.object
<CustomObject>
    <description>Custom object to store customer satisfaction survey offers and responses from getfeedback and other (e.g., help center)  integrated survey tools.</description>
    <fields>
        <fullName>MIIncident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the MI Incident that initiated the CSAT record and subsequent response.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>CSATs</relationshipLabel>
        <relationshipName>CSATs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist of values to indicate the status of the survey offering.</description>
        <label>Offer Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                    <color>#0B6FCE</color>
                    <label>Pending</label>
                </value>
                <value>
                    <fullName>Offered</fullName>
                    <color>#78C953</color>
                    <label>Offered</label>
                </value>
                <value>
                    <fullName>Responded</fullName>
                    <color>#FF9900</color>
                    <label>Responded</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>CSAT</label>
    <nameField>
        <label>Survey Response Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CSATs</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>IncidentCategorization__c</fullName>
        <description>This is to help better track how many of each type of incident we see and how effective changes we make to prevent MI issues are.</description>
        <label>Incident Categorization</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0 - Not enough details</fullName>
                </value>
                <value>
                    <fullName>1 - No property damage or serious threat</fullName>
                </value>
                <value>
                    <fullName>2 - Property damage or money (less than $5k)</fullName>
                </value>
                <value>
                    <fullName>3 - Property damage or money ($5k or above)</fullName>
                </value>
                <value>
                    <fullName>4 - Bodily harm or threat of serious bodily harm</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MICategory__c</fullName>
        <description>Marketplace Integrity Incident categories.</description>
        <label>MI Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concern about user</fullName>
                </value>
                <value>
                    <fullName>Deposit no show</fullName>
                </value>
                <value>
                    <fullName>Payment issues</fullName>
                </value>
                <value>
                    <fullName>Physical harm / Inappropriate contact</fullName>
                </value>
                <value>
                    <fullName>Property damage</fullName>
                </value>
                <value>
                    <fullName>Theft</fullName>
                </value>
                <value>
                    <fullName>Unprofessional behavior</fullName>
                </value>
                <value>
                    <fullName>Unsatisfactory work</fullName>
                </value>
                <value>
                    <fullName>Work not complete</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MISubcategory__c</fullName>
        <description>Marketplace Integrity Incident Subcategories.</description>
        <label>MI Subcategory</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>MICategory__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Charged Unfairly</fullName>
                </value>
                <value>
                    <fullName>Check or payment scam</fullName>
                </value>
                <value>
                    <fullName>Criminal history</fullName>
                </value>
                <value>
                    <fullName>Fraudulent charges</fullName>
                </value>
                <value>
                    <fullName>Harassment</fullName>
                </value>
                <value>
                    <fullName>Licensing concerns</fullName>
                </value>
                <value>
                    <fullName>Threat or intimidation</fullName>
                </value>
                <value>
                    <fullName>Unprofessional communication</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequestID__c</fullName>
        <inlineHelpText>Request ID of the customer&apos;s request that the pro quoted on.</inlineHelpText>
        <label>Request ID</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ResolutionTier__c</fullName>
        <description>Tier of resolution for the Incident</description>
        <label>Resolution Tier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 0 - Lost Communication</fullName>
                </value>
                <value>
                    <fullName>Tier 1 - Re-established Communication</fullName>
                </value>
                <value>
                    <fullName>Tier 2 - Found Middle Ground</fullName>
                </value>
                <value>
                    <fullName>Tier 3 - Flagged Pro</fullName>
                </value>
                <value>
                    <fullName>Tier 4 - Removed Pro</fullName>
                </value>
                <value>
                    <fullName>Tier 5 - Thumbtack Compensation</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bid_id__c</fullName>
        <description>External bid/quote ID from the the TT database.</description>
        <externalId>true</externalId>
        <label>bid_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>customer_id__c</fullName>
        <description>The id of the customer related to the bid_id of the incident.</description>
        <label>customer_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>pro_user_id__c</fullName>
        <description>The id of the pro related to the bid_id of the incident.</description>
        <label>pro_user_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>quotes_bid_id__c</fullName>
        <externalId>true</externalId>
        <label>quotes_bid_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>quotes_customer_id__c</fullName>
        <label>quotes_customer_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>quotes_pro_user_id__c</fullName>
        <label>quotes_pro_user_id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <recordTypes>
        <fullName>MarketplaceIntegrity</fullName>
        <active>true</active>
        <description>Record Type for MI Incidents</description>
        <label>Marketplace Integrity</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/MIIncidentBidCheckApexControllerTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
******************************************************************************** 
  

Change List:
------------
Version      Date          Author            Description
========+============+=================+================================================
1.0       06-19-2017     Scott Purcell          Created
1.1       2018-01-03   Mendel Guillaume  Updated to follow template/guidelines
1.1       2018-01-04   Mendel Guillaume  Updated to account for response object
========+============+=================+===============================================*/
@IsTest
private class MIIncidentBidCheckApexControllerTest
{
    public static Id gfRecordTypeId = CSAT__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('GetFeedback CSAT').getRecordTypeId();
    public static Id miRecordTypeId = MIIncident__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('MI Incident').getRecordTypeId();

    @TestSetup
    private static void createData()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Case c = new Case(Subject = 'Test Case', Status = 'New', Origin = 'Email',
                    RecordTypeId = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Marketplace Integrity').getRecordTypeId());

            insert c;
        }
    }

    @IsTest
    static void testMIInccidentNewUpdate()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Id accProRT = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId();
            Id accCustomerRT = Schema.Sobjecttype.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            Id caseRT = Schema.Sobjecttype.Case.getRecordTypeInfosByName().get('Marketplace Integrity').getRecordTypeId();
            Id miCaseQueueId = [SELECT Id FROM Group WHERE Type = 'Queue' AND DeveloperName = 'MarketplaceIntegrity'].Id;
            Decimal testProUserId = 100;
            Decimal testCustomerUserId = 200;
            Account aPro = new Account(Name = 'Chester Pro', usr_user_id__c = testProUserId, usr_email__c = 'protester@t.est', RecordTypeId = accProRT);
            Account aPro2 = new Account(Name = 'Chester Pro2', usr_user_id__c = 123, usr_email__c = 'protester2@t.est', RecordTypeId = accProRT);
            Account aCustomer = new Account(Name = 'Tester Customer', usr_user_id__c = testCustomerUserId, usr_email__c = 'customertester@t.est', RecordTypeId = accCustomerRT);
            Account aCustomer2 = new Account(Name = 'Tester Customer2', usr_user_id__c = 12345, usr_email__c = 'customertester2@t.est', RecordTypeId = accCustomerRT);
            insert new Account[] {aPro, aPro2, aCustomer, aCustomer2};

            Case c = [SELECT Id FROM Case];
            c.AccountId = aPro.Id;
            update c;

            MiIncident__c mii = new MiIncident__c(
                    Name = 'Test',
                    pro_user_id__c = String.valueOf(testProUserId),
                    customer_id__c = String.valueOf(testCustomerUserId),
                    quotes_pro_user_id__c = testProUserId,
                    quotes_customer_id__c = testCustomerUserId,
                    quotes_bid_id__c = 1,
                    RequestID__c = '1',
                    ResolutionTier__c = 'Tier 0 - Lost Communication',
                    MICategory__c = 'Removed',
                    MISubcategory__c = 'Other',
                    Status__c = 'In Progress',
                    IncidentCategorization__c = '0 - Not enough details');
            insert mii;
            mii.ProAccount__c = aPro2.Id;
            mii.CustomerAccount__c = aCustomer2.Id;
            mii.ResolutionTier__c = 'Compensation Reason';
            mii.Status__c = 'Closed';
            mii.RecordTypeId = miRecordTypeId;
            mii.OutcomeCustomer__c = 'Flagged';
            mii.OutcomePro__c = 'Unresponsive';
            mii.CSATOfferedPro__c = false;
            mii.MICategory__c = 'Property damage';
            mii.DoNotSurveyPro__c = false;
            mii.ClosedDate__c = Date.today();
            mii.OutcomePro__c = 'Pro fixed work';
            update mii;

            MiIncident__c mii2 = new MiIncident__c(
                    Name = 'Testy',
                    pro_user_id__c = '110',
                    customer_id__c = '210',
                    quotes_pro_user_id__c = 110,
                    quotes_customer_id__c = 210,
                    quotes_bid_id__c = 2,
                    RequestID__c = '2',
                    ResolutionTier__c = 'Tier 0 - Lost Communication',
                    MICategory__c = 'Removed',
                    MISubcategory__c = 'Other',
                    Status__c = 'In Progress',
                    IncidentCategorization__c = '0 - Not enough details');

            Test.startTest();

            MiIncident__c testIncident = (MIIncident__c)MIIncidentBidCheckApexController.getIncidentFromBecky(1234, mii).record;
            System.Assert(testIncident != null, 'Incident not found');
            MiIncident__c testIncident2 = (MIIncident__c)MIIncidentBidCheckApexController.insertNewIncident(mii2, c.Id, true, false,
                    new Contact(usr_user_id__c = 11111, FirstName = 'Test', LastName = 'Customer'),
                    new Contact(usr_user_id__c = 11112, FirstName = 'Test', LastName = 'Pro')).record;
            System.Assert(testIncident2 != null, 'Incident not found');
            Case c1 = MIIncidentBidCheckApexController.getCaseValues(c.Id);
            System.Assert(c1 != null, 'Case not found');
            MiIncident__c testIncident3 = MIIncidentBidCheckApexController.createInitialIncident(c.Id);
            System.Assert(testIncident3 != null, 'Incident not created');
            List<String> values = MIIncidentBidCheckApexController.getPicklistOptions('MIIncident__c', 'Origin__c');
            System.Assert(values.size() > 0, 'No Origin options');

            Test.stopTest();
        }
    }

    @IsTest
    static void testInsertNewIncidentFromExternal()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Case c = [Select Id FROM Case];
            MIIncident__c incident = MIIncidentBidCheckApexController.createInitialIncident(c.Id);

            System.assertEquals(null, incident.Id);

            incident.customer_id__c = '11111';
            incident.CustomerEmail__c = 'test@cust.com';
            incident.CustomerName__c = 'Test Customer';
            incident.pro_user_id__c = '11112';
            incident.ProEmail__c = 'test@pro.com';
            incident.ProfessionalName__c = 'Test Pro';
            incident.bid_id__c = null;

            Test.startTest();

            MIIncidentBidCheckApexController.insertNewIncidentFromExternal(incident, c.Id, true, false);

            Test.stopTest();

            System.assertNotEquals(null, incident.Id, 'Incident created');
        }
    }

    @IsTest
    static void testFindUser1()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Test.startTest();

            System.assertEquals(null, MIIncidentBidCheckApexController.findThumbtackUser(11111), 'User found');

            Test.stopTest();
        }
    }

    @IsTest
    static void testFindUser2()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Test.startTest();

            System.assertNotEquals(null, MIIncidentBidCheckApexController.findThumbtackUser(11112), 'User not found');

            Test.stopTest();
        }
    }

	//Existing contact
	@IsTest
	static void testFindUser3()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Account a = new Account(Name = 'Chester Tester', usr_user_id__c = 11111);
			insert a;

			Test.startTest();

			System.assertNotEquals(null, MIIncidentBidCheckApexController.findThumbtackUser(11111), 'User not found');

			Test.stopTest();
		}
	}

    @IsTest
    static void testGetCategories()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Test.startTest();

            System.assertNotEquals(0, MIIncidentBidCheckApexController.getCategories().size(), 'No categories');

            Test.stopTest();
        }
    }

    @IsTest
    static void testGetCategoriesMap()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Test.startTest();

            System.assertNotEquals(0, MIIncidentBidCheckApexController.getCategoryMap().size(), 'No categories map');

            Test.stopTest();
        }
    }

    @IsTest
    static void testCreateGoodSamaritanIncidentExistingUser()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Case c = [Select Id FROM Case];
            MIIncident__c incident = MIIncidentBidCheckApexController.createInitialIncident(c.Id);
            FindUserController.FindUserResult user = MIIncidentBidCheckApexController.findThumbtackUser(11112);

            Test.startTest();

            MIIncidentBidCheckApexController.createGoodSamaritanIncidentExistingUser(incident, c.Id, user.user, true);

            Test.stopTest();

            System.assertNotEquals(null, incident.Id, 'Incident not created');
        }
    }

    @IsTest
    static void testCreateGoodSamaritanIncidentExistingContact()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Case c = [Select Id FROM Case];

            Account a = new Account(Name = 'Chester Tester');
            insert a;
            Contact ct = new Contact(LastName = 'Tester', FirstName = 'Chester', AccountId = a.Id);
            insert ct;

            MIIncident__c incident = MIIncidentBidCheckApexController.createInitialIncident(c.Id);

            Test.startTest();

            MIIncidentBidCheckApexController.createGoodSamaritanIncidentExistingContact(incident, c.Id, ct, false);

            Test.stopTest();

            System.assertNotEquals(null, incident.Id, 'Incident not created');
        }
    }

    @IsTest
    static void testCreateGoodSamaritanIncidentNewUser()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Case c = [Select Id FROM Case];
            MIIncident__c incident = MIIncidentBidCheckApexController.createInitialIncident(c.Id);

            Test.startTest();

            MIIncidentBidCheckApexController.createGoodSamaritanIncidentNewUser(incident, c.Id, 'test@cust.com', 'Test', 'Cust', false);

            Test.stopTest();

            System.assertNotEquals(null, incident.Id, 'Incident not created');
        }
    }

	//No email
	@IsTest
	static void testCreateGoodSamaritanIncidentNewUser2()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Case c = [Select Id FROM Case];
			MIIncident__c incident = MIIncidentBidCheckApexController.createInitialIncident(c.Id);

			Test.startTest();

			MIIncidentBidCheckApexController.createGoodSamaritanIncidentNewUser(incident, c.Id, '', 'Test', 'Cust', false);

			Test.stopTest();

			System.assertNotEquals(null, incident.Id, 'Incident not created');
		}
	}

    @IsTest
    static void testCreateNewAccountContact()
    {
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Test.startTest();

            System.assertNotEquals(null, MIIncidentBidCheckApexController.createNewAccountContact('test@test.com', 'Test', 'Test', MIIncidentBidCheckApexController.cRTId, 0), 'Contact not created');

            Test.stopTest();
        }
    }

	@IsTest
	static void testGetQueues()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assertNotEquals(0, MIIncidentBidCheckApexController.getQueues().size(), 'No queues');

			Test.stopTest();
		}
	}
}