metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>CSATEligible__c</fullName>
        <description>Formula field to display eligibility text if a case meets certain criteria for a survey offer.</description>
        <formula>IF(Contact.DoNotSurvey__c, &quot;Not Eligible&quot;, 
IF(ISPICKVAL(Origin, &quot;Outbound Phone&quot;), &quot;Not Eligible&quot;, 
IF(AutoClosed__c, &quot;Not Eligible&quot;, 
IF(Contact.ContactIsThumbtackStaff__c, &quot;Not Eligible&quot;, 
IF(SurveyOffered__c, &quot;Not Eligible&quot;, 
IF(IsTestData__c, &quot;Not Eligible&quot;,
IF(AND(NOT ISBLANK(Incident__c),
       Incident__r.RecordType.Name = &quot;MI Incident&quot;), &quot;Not Eligible&quot;, 
IF(ContactEmailRouting__c = &quot;Route to Sales &amp; Account Management&quot;, &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Marketplace Integrity&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Customer/Pro Requested&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Special Projects&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Abusive Pro/Customer&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;QA Audit&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(DoNotSurvey__c, &quot;Sys Admin Bulk Close&quot;), &quot;Not Eligible&quot;, 
IF(ISPICKVAL(Origin, &quot;App Integration&quot;), &quot;Not Eligible&quot;, 
IF(ISBLANK(ClosedDate), &quot;Not Eligible&quot;, 
IF((NOW() - ClosedDate &gt;= 14), &quot;Not Eligible&quot;, 
IF(ISBLANK(Contact.Email), &quot;Not Eligible&quot;, 
IF(NOT ISBLANK( DuplicateOf__c ), &quot;Not Eligible&quot;, 
IF( ElapsedSurveyHours__c &lt;= 24, &quot;Not Eligible&quot;, 
IF( 
OR( 
ISPICKVAL(Category__c, &quot;Delete Account&quot;), 
ISPICKVAL(Category__c, &quot;Chat&quot;), 
AND( 
ISPICKVAL(Category__c, &quot;Phone&quot;), 
ISPICKVAL(SubCategory__c, &quot;Wrong number&quot;)), 
AND( 
ISPICKVAL(Category__c, &quot;Marketplace Integrity&quot;), 
 OR(ISPICKVAL(SubCategory__c, &quot;Duplicate&quot;),
    ISPICKVAL(SubCategory__c, &quot;Background check&quot;),
    ISPICKVAL(SubCategory__c, &quot;Certification agreement&quot;),
    ISPICKVAL(SubCategory__c, &quot;DMCA/Copyright&quot;), 
    ISPICKVAL(SubCategory__c, &quot;Negative review&quot;),
    ISPICKVAL(SubCategory__c, &quot;Concerning review&quot;),
    ISPICKVAL(SubCategory__c, &quot;Incident&quot;),
    ISPICKVAL(SubCategory__c, &quot;License&quot;),
    ISPICKVAL(SubCategory__c, &quot;Trademark&quot;),
    ISPICKVAL(SubCategory__c, &quot;Other&quot;))),
AND( 
ISPICKVAL(Category__c, &quot;Notifications&quot;), 
ISPICKVAL(SubCategory__c, &quot;Unsubscribe&quot;)), 
AND( 
ISPICKVAL(Category__c, &quot;Other&quot;), 
OR(ISPICKVAL(SubCategory__c, &quot;Background check (mismatch)&quot;), 
ISPICKVAL(SubCategory__c, &quot;Message intended for customer&quot;), 
ISPICKVAL(SubCategory__c, &quot;Message intended for pro&quot;), 
ISPICKVAL(SubCategory__c, &quot;Foreign language&quot;), 
ISPICKVAL(SubCategory__c, &quot;Press inquiries&quot;), 
ISPICKVAL(SubCategory__c, &quot;Noise&quot;), 
ISPICKVAL(SubCategory__c, &quot;Not enough info&quot;), 
ISPICKVAL(SubCategory__c, &quot;Proactive - no response&quot;))), 
AND( 
ISPICKVAL(Category__c,&quot;Quotes&quot;), 
ISPICKVAL(SubCategory__c,&quot;Quote intended for customer&quot;))), 
&quot;Not Eligible&quot;, 
IF( 
AND( 
TEXT(Category__c) = Contact.LastSurveyedCaseCategory__c, 
TEXT(SubCategory__c) = Contact.LastSurveyedCaseSubcategory__c, 
ElapsedSurveyHours__c &lt;= 48), &quot;Not Eligible&quot;, 
&quot;Eligible&quot;))))))))))))))))))))))</formula>
        <label>CSAT Eligible</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <description>L1 category issue - this is where the general area goes.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account / Profile</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Customer Payments</fullName>
                </value>
                <value>
                    <fullName>Delete Account</fullName>
                </value>
                <value>
                    <fullName>Getting Started</fullName>
                </value>
                <value>
                    <fullName>Marketplace Integrity</fullName>
                </value>
                <value>
                    <fullName>Notifications</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Pricing and Payments</fullName>
                </value>
                <value>
                    <fullName>Instant Match</fullName>
                </value>
                <value>
                    <fullName>Quotes</fullName>
                </value>
                <value>
                    <fullName>Quoting Service</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>Requests</fullName>
                </value>
                <value>
                    <fullName>Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/CategorizationDefinition__c.object
<CustomObject>
    <description>Metadata object - the records from this object define what Categorization options are available for a given record.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not this Categorization Definition is currently available for use.</description>
        <inlineHelpText>Whether or not this Categorization Definition is currently available for use.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available On Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnCase__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, this definition is available on the Case object.</description>
        <inlineHelpText>If true, this definition is available on the Case object.</inlineHelpText>
        <label>Available On Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnEnrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this definition is available on the Enrollment Object.</description>
        <inlineHelpText>If checked, this definition is available on the Enrollment Object.</inlineHelpText>
        <label>Available On Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSATEligible__c</fullName>
        <description>The CSAT eligibility of this Definition</description>
        <inlineHelpText>The CSAT eligibility of this Definition</inlineHelpText>
        <label>CSAT Eligible</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                    <default>true</default>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Always Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Always Eligible</label>
                </value>
                <value>
                    <fullName>Always Ineligible</fullName>
                    <isActive>false</isActive>
                    <label>Always Ineligible</label>
                </value>
                <value>
                    <fullName>Ineligible if Primary</fullName>
                    <isActive>false</isActive>
                    <label>Ineligible if Primary</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>HelpText__c</fullName>
        <description>The agent-facing help text for this category.</description>
        <inlineHelpText>The agent-facing help text for this category.</inlineHelpText>
        <label>Help Text</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Icon__c</fullName>
        <description>The code for the icon to be displayed next to this category/subcategory/product update, if applicable.</description>
        <inlineHelpText>The code for the icon to be displayed next to this category/subcategory/product update, if applicable.</inlineHelpText>
        <label>Icon</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>The unique key of this Categorization Definition</description>
        <displayFormat>{YYYY}{MM}-{000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>The unique key of this Categorization Definition.</inlineHelpText>
        <label>Key</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ParentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Category for use with Subcategories.</description>
        <inlineHelpText>The parent Category for use with Subcategories.</inlineHelpText>
        <label>Parent Category</label>
        <referenceTo>CategorizationDefinition__c</referenceTo>
        <relationshipLabel>Subcategories</relationshipLabel>
        <relationshipName>Subcategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Placeholder__c</fullName>
        <description>The text placeholder to display on the input field, if any.</description>
        <inlineHelpText>The text placeholder to display on the input field, if any.</inlineHelpText>
        <label>Placeholder</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PreventRecordCreation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this subcategory will not create a Categorization__c record when &apos;submit&apos; is set.</description>
        <inlineHelpText>If checked, this subcategory will not create a Categorization__c record when &apos;submit&apos; is set.</inlineHelpText>
        <label>Prevent Record Creation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SentimentScale__c</fullName>
        <description>The availability of sentiment to be captured.
If zero, sentiment is not available.
If 2, sentiment is to be captured on a two-point scale (positive or negative)
If 3, sentiment is to be captured on a three-point scale (positive, negative, neutral)</description>
        <inlineHelpText>The availability of sentiment to be captured.
If zero, sentiment is not available.
If 2, sentiment is to be captured on a two-point scale (positive or negative).
If 3, sentiment is to be captured on a three-point scale (positive, negative, neutral).</inlineHelpText>
        <label>Sentiment Scale</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <description>The sort order of a Product Update record.</description>
        <inlineHelpText>The sort order of a Product Update record.</inlineHelpText>
        <label>Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Categorization Definition</label>
    <nameField>
        <label>Categorization Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorization Definitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/CategorizationProdUpdatesListController.cls
/*
   Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+================================================
   1.0      2017-10-27   Mendel Guillaume       Created
   ========+============+=================+===============================================
*/

public with sharing class CategorizationProdUpdatesListController
{
	public static Id CATEGORIZATION_PRODUCT_UPDATE_RT_ID = Categorization__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Product Update').getRecordTypeId();
	public static Id CATEGORIZATION_DEFINITION_PRODUCT_UPDATE_RT_ID = CategorizationDefinition__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Product Update').getRecordTypeId();

	@AuraEnabled
	public static List<CategorizationCategoriesListController.CategoryWrapper> getProductUpdates(String recordId)
	{
		List<Categorization__c> cats = new List<Categorization__c>();
		List<CategorizationCategoriesListController.CategoryWrapper> categoryWrappers = new List<CategorizationCategoriesListController.CategoryWrapper>();
		Map<String, Categorization__c> keyToCategorizationsMap = new Map<String, Categorization__c>();
		List<CategorizationDefinition__c> catDefs = database.query('SELECT Id, Name, Key__c, ParentCategory__c, ParentCategory__r.Name, ' +
				'ParentCategory__r.Key__c, SentimentScale__c, PreventRecordCreation__c, ' +
				'ParentCategory__r.PreventRecordCreation__c, Active__c, HelpText__c, Icon__c, Placeholder__c, CSATEligible__c, ' +

					'(SELECT Id, Name, Key__c, ParentCategory__c, ParentCategory__r.Name, ' +
						'ParentCategory__r.Key__c, SentimentScale__c, PreventRecordCreation__c, ' +
						'ParentCategory__r.PreventRecordCreation__c, Active__c, HelpText__c, Icon__c, Placeholder__c, CSATEligible__c ' +
					'FROM Subcategories__r ' +
					'WHERE RecordType.Name = \'Product Update\' AND '+
					(recordId != null && recordId.startsWith('500') ? 'AvailableOnCase__c = true ' : (recordId != null && recordId.startsWith('001') ? 'AvailableOnAccount__c = true ' : 'AvailableOnEnrollment__c = true ')) +
					'ORDER BY SortOrder__c NULLS LAST, Name) ' +

				'FROM CategorizationDefinition__c ' +
				'WHERE RecordType.Name = \'Product Update\' AND ParentCategory__c = null AND '+
					(recordId != null && recordId.startsWith('500') ? 'AvailableOnCase__c = true ' : (recordId != null && recordId.startsWith('001') ? 'AvailableOnAccount__c = true ' : 'AvailableOnEnrollment__c = true ')) +
				'ORDER BY SortOrder__c NULLS LAST, Name');

		if (recordId != null)
		{
			cats = [SELECT Id, Name, Case__c, Category__c, DefinitionKey__c, Enrollment__c, Feedback__c, Notes__c, SubProductUpdate__c,
							Primary__c, Sentiment__c, Subcategory__c, ParentDefinitionKey__c, ProductUpdate__c, Deleted__c, CSATEligible__c
					FROM Categorization__c
					WHERE RecordTypeId = :CATEGORIZATION_PRODUCT_UPDATE_RT_ID AND (Case__c = :recordId OR Enrollment__c = :recordId OR Account__c = :recordId)
					ORDER BY Name];

			for(Categorization__c c : cats)
			{
				if(c.DefinitionKey__c != null)
				{
					keyToCategorizationsMap.put(c.DefinitionKey__c, c);
				}
			}

			for(CategorizationDefinition__c cd : catDefs)
			{
				CategorizationCategoriesListController.CategoryWrapper cw = getCategoryWrapper(cd, keyToCategorizationsMap.get(cd.Key__c), recordId);

				if(cw != null)
				{
					//Add child product updates
					if (!cd.Subcategories__r.isEmpty())
					{
						for (CategorizationDefinition__c ccd : cd.Subcategories__r)
						{
							cw.childCategories.add(getCategoryWrapper(ccd, keyToCategorizationsMap.get(ccd.Key__c), recordId));
						}
					}

					categoryWrappers.add(cw);
				}
			}
		}

		return categoryWrappers;
	}

	private static CategorizationCategoriesListController.CategoryWrapper getCategoryWrapper(CategorizationDefinition__c cd, Categorization__c existingRecord, String recordId)
	{
		CategorizationCategoriesListController.CategoryWrapper cw = null;

		if(existingRecord != null)
		{
			existingRecord.CSATEligible__c = cd.CSATEligible__c;

			//Update existing records to have parent info on save - SYS-1609
			if(cd.ParentCategory__c != null && existingRecord.SubProductUpdate__c == null)
			{
				existingRecord.ProductUpdate__c = cd.ParentCategory__r.Name;
				existingRecord.SubProductUpdate__c = cd.Name;
				existingRecord.ParentDefinitionKey__c = cd.ParentCategory__r.Key__c;
			}

			cw = new CategorizationCategoriesListController.CategoryWrapper(existingRecord, cd, cd.Active__c, !existingRecord.Deleted__c);
		}
		else if(cd.Active__c)
		{
			cw = newProductUpdate(cd, recordId);
		}

		return cw;
	}

	@AuraEnabled
	public static String updateCategorization(List<Categorization__c> catsToSave)
	{
		return CategorizationCategoriesListController.saveCategorization(catsToSave, CATEGORIZATION_PRODUCT_UPDATE_RT_ID);
	}

	private static CategorizationCategoriesListController.CategoryWrapper newProductUpdate(CategorizationDefinition__c cd, String recordId)
	{
		CategorizationCategoriesListController.CategoryWrapper cw = null;
		Categorization__c	cat = new Categorization__c();
		cat.SubProductUpdate__c = cd.ParentCategory__c != null ? cd.Name : null;
		cat.ProductUpdate__c =  cd.ParentCategory__c != null ? cd.ParentCategory__r.Name : cd.Name;
		cat.DefinitionKey__c = cd.Key__c;
		cat.Feedback__c = false;
		cat.Notes__c = '';
		cat.Primary__c = false;
		cat.Sentiment__c = null;
		cat.Subcategory__c = null;
		cat.ParentDefinitionKey__c = cd.ParentCategory__c != null ? cd.ParentCategory__r.Key__c : null;
		cat.RecordTypeId = CATEGORIZATION_PRODUCT_UPDATE_RT_ID;
		cat.CSATEligible__c = cd.CSATEligible__c;

		if (recordId.startsWith('500'))
		{
			Case c = [SELECT Origin FROM Case WHERE Id = :recordId];

			cat.Case__c = recordId;
			cat.Origin__c = c.Origin;
		}
		else if (recordId.startsWith('001'))
		{
			cat.Account__c = recordId;
		}
		else
		{
			Enrollment__c e = [SELECT Account__c FROM Enrollment__c WHERE Id =: recordId];

			cat.Enrollment__c = recordId;
			cat.Feedback__c = false;
			cat.Account__c = e.Account__c;
		}

		cw = new CategorizationCategoriesListController.CategoryWrapper(cat, true);
		cw.catDefinition = cd;

		return cw;
	}
}