metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>L1 category issue - this is where the general area goes.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account / Profile</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Customer Payments</fullName>
                </value>
                <value>
                    <fullName>Delete Account</fullName>
                </value>
                <value>
                    <fullName>Getting Started</fullName>
                </value>
                <value>
                    <fullName>Marketplace Integrity</fullName>
                </value>
                <value>
                    <fullName>Notifications</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Pricing and Payments</fullName>
                </value>
                <value>
                    <fullName>Instant Match</fullName>
                </value>
                <value>
                    <fullName>Quotes</fullName>
                </value>
                <value>
                    <fullName>Quoting Service</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>Requests</fullName>
                </value>
                <value>
                    <fullName>Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DisputeIdHash__c</fullName>
        <description>Placeholder field for solution center front end to pass over the dispute ID hash so we can use that to lookup and set the Dispute__c value.  We do not write a value to this field, only used in VRMO controller.</description>
        <inlineHelpText>Placeholder field for solution center front end to pass over the dispute ID hash so we can use that to lookup and set the Dispute__c value.  We do not write a value to this field, only used in VRMO controller.</inlineHelpText>
        <label>Dispute Id Hash</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dispute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Dispute that the case originated from.</description>
        <label>Dispute</label>
        <referenceTo>Dispute__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HelpCenterVisitSubTopic__c</fullName>
        <description>The sub-topic of the last visited help center article.</description>
        <label>Help Center Visit Sub Topic</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>HelpCenterVisitTopic__c</fullName>
        <description>The topic of the last visited help center article.</description>
        <label>Help Center Visit Topic</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship between Cases and Incidents.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SubCategory__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>App pricing / purchase</fullName>
                </value>
                <value>
                    <fullName>Background check</fullName>
                </value>
                <value>
                    <fullName>Background check (clear)</fullName>
                </value>
                <value>
                    <fullName>Background check (mismatch)</fullName>
                </value>
                <value>
                    <fullName>Background check (not clear)</fullName>
                </value>
                <value>
                    <fullName>Called for customer</fullName>
                </value>
                <value>
                    <fullName>Called for pro</fullName>
                </value>
                <value>
                    <fullName>Called for specific employee</fullName>
                </value>
                <value>
                    <fullName>Canceled request</fullName>
                </value>
                <value>
                    <fullName>Cash refund</fullName>
                </value>
                <value>
                    <fullName>Certification agreement</fullName>
                </value>
                <value>
                    <fullName>Churn</fullName>
                </value>
                <value>
                    <fullName>Competitive report</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Concerning review</fullName>
                </value>
                <value>
                    <fullName>Connection issues - didn&apos;t talk</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - Call back needed</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - CC not provided</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - PA Live</fullName>
                </value>
                <value>
                    <fullName>Customer / other</fullName>
                </value>
                <value>
                    <fullName>Customer contact</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Disconnected (pro or customer)</fullName>
                </value>
                <value>
                    <fullName>Disconnected (specialist)</fullName>
                </value>
                <value>
                    <fullName>Dispute</fullName>
                </value>
                <value>
                    <fullName>DMCA/Copyright</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Duplicate request</fullName>
                </value>
                <value>
                    <fullName>Dynamic pricing</fullName>
                </value>
                <value>
                    <fullName>Incident</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Dispute__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeExperience__c.object
<CustomObject>
    <description>Custom object that will store the Solution Center dispute experience configuration records.</description>
    <label>Dispute Experience</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Experiences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/SolutionCenterUtilityTest.cls
/*
   Copyright (c) 2017 Thumbtack, All rights reserved.

Change List:
------------
Version      Date          Author            Description
========+============+=================+================================================
1.0       3/2/18      pcoleman           Created to test utility functions
========+============+=================+===============================================*/
@IsTest
public with sharing class SolutionCenterUtilityTest
{
    /**
    * @author Paul Coleman
    * @date 2018-03-02
    * @description Inserts a set of four test Accounts.
    */
    @TestSetup
    private static void createTestAccounts()
    {
        TestUtilities.insertFourCoreThumbtackUsers();
        DisputeExperience__c experience = (DisputeExperience__c) JSON.deserialize( DisputeTriggerHandlerTest.DEFAULT_DISPUTE_EXPERIENCE_JSON, DisputeExperience__c.class );
        insert experience;
    }

    /**
    * @author Paul Coleman
    * @date 2018-03-02
    * @description Tests the insert of a Case with related Dispute from Help Center via the caseCreate() VFRMO dml override function.
    */
    @IsTest
    private static void testInsertDisputeCase()
    {
        User initiator; // to be created on the fly
        Dispute__c newDispute;
        System.runAs( TestUtilities.USER_TACK_BOT )
        {
            newDispute = SolutionCenterControllerTest.loadInitiatorDispute(true);
            SolutionCenterControllerTest.insertIncident(newDispute);
        }

        Test.startTest();

            initiator = [SELECT Id FROM User WHERE ContactId = :newDispute.InitiatorContact__c LIMIT 1];
            System.runAs( initiator )
            {
                Map<String, Object> caseFields = new Map<String, Object>{
                        'DisputeIdHash__c' => newDispute.IdHash__c,
                        'OwnerId' => [SELECT Id FROM Group WHERE Name = 'Marketplace Integrity' AND Type = 'Queue'].Id, //mark
                        'Description' => 'Halp.',
                        'Subject' => 'Testing on more time',
                        'Category__c' => 'Marketplace Integrity',
                        'SubCategory__c' => 'Incident',
                        'HelpCenterVisitSubTopic__c' => 'MTS Subtopic 2',
                        'HelpCenterVisitTopic__c' => 'MTS Topic 2',
                        'Origin' => 'Web',
                        'SuppliedEmail' => 'ben@ben.ben',
                        'SuppliedName' => 'Ben Ben',
                        'RecordTypeId' => Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Marketplace Integrity').getRecordTypeId()
                };
                HCControllerRMO.caseCreate( 'Case', caseFields );
            }

        Test.stopTest();

        //assert related offer
        Case[] insertedCase = [SELECT Id, Dispute__c, Incident__c FROM Case WHERE Dispute__c = :newDispute.Id LIMIT 1];
        System.assertEquals( false, insertedCase.isEmpty(), 'Case not created related to Dispute.');
        System.assertEquals( newDispute.MIIncident__c, insertedCase[0].Incident__c, 'Inserted Case not related to Dispute Incident.');

        // Grabbing code coverage for potential Database DML Errors in functions supporting SolutionCenterController
        // functions like createOffer(), createMessage(), updateDisputeDescription() etc:
        try
        {
            SolutionCenterUtility.createRecord(new Dispute__c(Id = newDispute.Id), SolutionCenterUtility.DisputeDML.GET_ID_HASH);
        } catch (SolutionCenterUtility.SolutionCenterException se) {}

        try
        {
            SolutionCenterUtility.updateRecord( new Dispute__c(), SolutionCenterUtility.DisputeDML.GET_ID_HASH );
        } catch (SolutionCenterUtility.SolutionCenterException se) {}
    }

}