metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SuppliedThumbtackID__c</fullName>
        <description>The Thumbtack user ID - data passed in from outside sources - used to match to account/contact.</description>
        <label>Supplied Thumbtack ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>usr_user_id</description>
        <externalId>true</externalId>
        <label>User ID (Unique)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>This record type is used for all thumbtack customers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/ProductFeedback__c.object
<CustomObject>
    <description>Custom object to store feedback records from Thumbtack&apos;s Pros and Customers. Includes product feedback and request form/category feedback.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship between case and product feedback custom object</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Feedbacks</relationshipLabel>
        <relationshipName>Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProductFeedback__c</fullName>
        <description>Product feedback received from customers/pros</description>
        <inlineHelpText>Enter any feedback received from the customer or pro here.</inlineHelpText>
        <label>Product Feedback</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/FeedbackTriggerHandlerTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************    

 Change List:                                                               
 ------------                                                               

 Version    Date     Author            Description                          
 =======+===========+=================+==============================================
 1.0     07-14-2017   Scott Purcell     Created 
 =======+===========+=================+=============================================*/
@isTest
private class FeedbackTriggerHandlerTest {
	public static Id psfRecordTypeId = ProductFeedback__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Pro Services Feedback').getRecordTypeId();
	@isTest static void testCreateFeedback() 
	{

        User testUser = [SELECT id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive=true LIMIT 1];
        System.runAs(testUser) 
        {
            Id caseRTId=Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Customer Support').getRecordTypeId();
            insert new Contact[]{new Contact(LastName='Tester',FirstName='Chester',Email='testerfound@bogus.testing.com',usr_user_id__c=12),new Contact(LastName='Tester2',FirstName='Chester',Email='tester2@bogus.testing.com',usr_user_id__c=13)};
            Test.startTest();

            Case c = new Case(Status='New',RecordTypeId=caseRTId,Origin='Web',SuppliedEmail='tester@bogus.testing.com',SuppliedName='Chester CaseTester',SuppliedThumbtackID__c=120);
            insert c;
            ProductFeedback__c pf = new ProductFeedback__c();
            pf.RecordTypeId = psfRecordTypeId;
            pf.Case__c = c.Id;
            insert pf;
            Test.stopTest();

            Case testCase = [SELECT Id,SuppliedName,ContactId,AccountId,Account.Name,Contact.LastName,Status FROM Case WHERE Id=:c.Id LIMIT 1];
            List<FeedItem> chatFeed = [SELECT  Id, Body, CommentCount, CreatedDate, LikeCount, LinkUrl, ParentId, RelatedRecordId, Title, Type
			FROM FeedItem ];
			system.debug('chatFeed: '+chatFeed);
        }
    } 
	
}