metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Dispute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Dispute that the case originated from.</description>
        <label>Dispute</label>
        <referenceTo>Dispute__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship between Cases and Incidents.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Confidential</fullName>
        <active>true</active>
        <businessProcess>Customer Support</businessProcess>
        <description>Record type used to manage super sensitive and confidential cases (aka no peeky).</description>
        <label>Confidential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Dispute__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeMessage__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeOffer__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <recordTypes>
        <fullName>Confidential</fullName>
        <active>true</active>
        <description>Record type used to manage highly sensitive dispute incidents.  Strict record sharing for this record type.</description>
        <label>Confidential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/MiIncidentHelper.cls
/*
	Copyright (c) [2015 -] 2018 Thumbtack. All rights reserved.

	Version    Date     Author            Description
	=======+===========+=================+=================================
	1.0     2018-02-09  Mendel Guillaume      Created
	========+============+=================+===============================*/

public class MiIncidentHelper
{
	public static final ID DISPUTE_OFFER_CONFIDENTIAL_RECORD_TYPE_ID = DisputeOffer__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Confidential').getRecordTypeId();
	public static final ID DISPUTE_MESSAGE_CONFIDENTIAL_RECORD_TYPE_ID = DisputeMessage__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Confidential').getRecordTypeId();

	public class MiIncidentQueueable implements Queueable
	{
		public Set<Id> confidentialIncidentIds {get;set;}

		public MiIncidentQueueable()
		{
		}

		public void execute(QueueableContext context)
		{
			try
			{
				if(confidentialIncidentIds != null && !confidentialIncidentIds.isEmpty())
				{
					updateRelatedRecordsToConfidential();
				}
			}
			catch(DmlException e)
			{
				system.debug(e);
			}
		}

		private void updateRelatedRecordsToConfidential()
		{
			List<SObject> objects = new List<SObject>();

			for (Case c : [SELECT Id FROM Case WHERE Incident__c IN :confidentialIncidentIds AND RecordTypeId != :CaseHelper.CONFIDENTIAL_RECORD_TYPE_ID])
			{
				c.RecordTypeId = CaseHelper.CONFIDENTIAL_RECORD_TYPE_ID;
				objects.add(c);
			}

			for(Dispute__c d : [SELECT Id FROM Dispute__c WHERE MIIncident__c IN :confidentialIncidentIds AND RecordTypeId != :DisputeTriggerHandler.CONFIDENTIAL_RECORD_TYPE_ID])
			{
				d.RecordTypeId = DisputeTriggerHandler.CONFIDENTIAL_RECORD_TYPE_ID;
				objects.add(d);
			}

			for(DisputeOffer__c d : [SELECT Id FROM DisputeOffer__c WHERE Dispute__r.MIIncident__c IN :confidentialIncidentIds AND RecordTypeId != :DISPUTE_OFFER_CONFIDENTIAL_RECORD_TYPE_ID])
			{
				d.RecordTypeId = DISPUTE_OFFER_CONFIDENTIAL_RECORD_TYPE_ID;
				objects.add(d);
			}

			for(DisputeMessage__c d : [SELECT Id FROM DisputeMessage__c WHERE DisputeOffer__r.Dispute__r.MIIncident__c IN :confidentialIncidentIds AND RecordTypeId != :DISPUTE_MESSAGE_CONFIDENTIAL_RECORD_TYPE_ID])
			{
				d.RecordTypeId = DISPUTE_MESSAGE_CONFIDENTIAL_RECORD_TYPE_ID;
				objects.add(d);
			}

			if(!objects.isEmpty())
			{
				objects.sort();
				Database.update(objects, false);
			}
		}
	}
}