metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Team__c</fullName>
        <description>Text field to indicate the case owner&apos;s assigned team.  Populated via a workflow rule.</description>
        <label>Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/CaseUpdateHistory__c.object
<CustomObject>
    <description>Custom object to store records related to status, ownership, and other property changes on a case.  Used for historical reporting.</description>
    <fields>
        <fullName>CaseOwnerTeam__c</fullName>
        <description>The team that the new case owner was on at the time the case update history record was created.</description>
        <label>Case Owner Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseOwner__c</fullName>
        <description>Tex field to indicate the owner of the case at the time of the Case Update History record being created.</description>
        <label>Case Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CasePreviousOwnerTeam__c</fullName>
        <description>The team that the previous case owner was on at the time the case update history record was created.</description>
        <label>Case Previous Owner Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CasePreviousOwner__c</fullName>
        <description>The previous owner of the case prior to being transferred.</description>
        <inlineHelpText>The previous owner of the case prior to being transferred.</inlineHelpText>
        <label>Case Previous Owner</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseTransferPost__c</fullName>
        <description>The text entered in the Post feature when the Case Transfer took place on the CaseTransfer action.</description>
        <label>Case Transfer Post</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <description>Master-detail relationship with case.</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Update History</relationshipLabel>
        <relationshipName>CaseUpdateHistory</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EscalatedCaseType__c</fullName>
        <description>The type of escalation pertaining to the case escalation transfer.</description>
        <label>Escalated Case Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Live</fullName>
                </value>
                <value>
                    <fullName>Callback</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EscalatedCase__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate if the case was escalated to a manager or MC.</description>
        <label>Escalated Case</label>
        <type>Checkbox</type>
    </fields>
    <label>Case Update History</label>
    <nameField>
        <displayFormat>CH-{000000}</displayFormat>
        <label>Case Update History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Update History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/classes/CaseTransferController.cls
/**
  Copyright (c) 2017 Thumbtack. All rights reserved.

  Version      Date          Author            Description
  ========+============+=================+================================================
  1.0      2017-11-21   Mendel Guillaume       Created
  ========+============+=================+===============================================
 */

public with sharing class CaseTransferController
{
	@AuraEnabled
	public static List<User> getUsersForPersonTransfer()
	{
		return [SELECT Id, Name FROM User WHERE IsActive = true AND AllowCaseTransfer__c IN ('Person', 'Escalation') ORDER BY Name];
	}

	@AuraEnabled
	public static List<User> getUsersForEscalationTransfer()
	{
		return [SELECT Id, Name FROM User WHERE IsActive = true AND AllowCaseTransfer__c = 'Escalation' ORDER BY Name];
	}

	@AuraEnabled
	public static List<Group> getGroupsForTransfer()
	{
		return (List<Group>)Database.query('SELECT Id, Name FROM GROUP WHERE Type = \'Queue\' AND Name IN (' + System.Label.CaseTransferQueueFilter + ') ORDER BY Name');
	}

	@AuraEnabled
	public static Case getCase(String caseId)
	{
		return [SELECT Id, OwnerId, Owner.Name FROM Case WHERE Id = :caseId];
	}

	@AuraEnabled
	public static String assignToMe(String caseId) 
	{
		return assignCase(caseId, UserInfo.getUserId(), null, null);
	}

	@AuraEnabled
	public static String assignCase(String caseId, String ownerId, String comment, String escalationType)
	{
		String result = 'Success';
		Boolean isTeam = ownerId != null && ownerId.startsWith('00G');
		Boolean escalated = String.isNotBlank(escalationType);
		Case c;
		CaseUpdateHistory__c cuh = new CaseUpdateHistory__c(Case__c = caseId, CaseTransferPost__c = comment,
				EscalatedCaseType__c = escalationType,
				RecordTypeId = CaseUpdateHistory__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Case Transfer Update').getRecordTypeId());


		try
		{
			c = [SELECT Id, OwnerId, Owner.Name, Team__c FROM Case WHERE Id = :caseId];

			cuh.EscalatedCase__c = escalated;

			if(isTeam)
			{
				Group ownerGroup = [SELECT Id, Name FROM Group WHERE Id = :ownerId];
				cuh.CaseOwnerTeam__c = ownerGroup.Name;
				cuh.CaseOwner__c = ownerGroup.Name;
			}
			else
			{
				User ownerUser = [SELECT Id, Name, Team__c FROM User WHERE Id = :ownerId];
				cuh.CaseOwner__c = ownerUser.Name;
				cuh.CaseOwnerTeam__c = ownerUser.Team__c;
			}

			if(String.valueOf(c.OwnerId).startsWith('00G'))
			{
				cuh.CasePreviousOwnerTeam__c = c.Owner.Name;
				cuh.CasePreviousOwner__c = c.Owner.Name;
			}
			else
			{
				cuh.CasePreviousOwner__c = c.Owner.Name;
				cuh.CasePreviousOwnerTeam__c = c.Team__c;
			}

			c.OwnerId = ownerId;
			update c;
			insert cuh;

			if(String.isNotBlank(comment))
			{
				CaseController.postMsgWithMentions(caseId, comment);
			}

		}
		catch (Exception ex)
		{
			result = 'Error: ' + ex.getMessage();
		}

		return result;
	}
}