metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Dispute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Dispute that the case originated from.</description>
        <label>Dispute</label>
        <referenceTo>Dispute__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DuplicateOf__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Enter duplicate cade Id.</description>
        <label>Duplicate Of</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Incident__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the relationship between Cases and Incidents.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <recordTypes>
        <fullName>Confidential</fullName>
        <active>true</active>
        <businessProcess>Customer Support</businessProcess>
        <description>Record type used to manage super sensitive and confidential cases (aka no peeky).</description>
        <label>Confidential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Dispute__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeMessage__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeMessages__c.object
<CustomObject>
    <description>Custom Object for Solution Center to capture &apos;Questions&apos;, &apos;Answers&apos;, from a Pro or Customer on an &apos;Offer&apos; related to a &apos;Dispute&apos;.  Also captures &apos;Success Tips&apos; sent to a pro or customer from Thumbtack and file images.</description>
    <fields>
        <fullName>DisputeMessage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a hierarchical look up to the Dispute Message so that we can associate text messages to the corresponding file images.</description>
        <inlineHelpText>This is a hierarchical look up to the Dispute Message so that we can associate text messages to the corresponding file images.</inlineHelpText>
        <label>Dispute Message</label>
        <referenceTo>DisputeMessages__c</referenceTo>
        <relationshipLabel>Dispute Messages</relationshipLabel>
        <relationshipName>DisputeMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DisputeOffer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The dispute offer for which the message was initiated or replied from.</description>
        <inlineHelpText>The dispute offer for which the message was initiated or replied from.</inlineHelpText>
        <label>Dispute Offer</label>
        <referenceTo>DisputeOffer__c</referenceTo>
        <relationshipLabel>Dispute Messages</relationshipLabel>
        <relationshipName>DisputeMessages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dispute Message</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Messages</pluralLabel>
    <recordTypes>
        <fullName>Confidential</fullName>
        <active>true</active>
        <description>Record type used to manage highly sensitive dispute messages. Strict record sharing for this record type.</description>
        <label>Confidential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/DisputeOffer__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <recordTypes>
        <fullName>Confidential</fullName>
        <active>true</active>
        <description>Record type used to manage highly sensitive dispute incidents.  Strict record sharing for this record type.</description>
        <label>Confidential</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/MTSDisputeHelper.cls
/*
   Copyright (c) 2017 Thumbtack, All rights reserved.

Change List:
------------
Version      Date          Author            Description
========+============+=================+================================================
1.0       1/19/18      pcoleman           Created
========+============+=================+===============================================*/
public with sharing class MTSDisputeHelper
{

    // code for MI Trigger Handler to cascader RT change for "Confidential"
    private void cascadeMIConfidential( Map<Id, MIIncident__c> triggerNewMap )
    {
        Id miCondentialRTId = MIIncident__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Confidential').getRecordTypeId();
        Id disputeCondentialRTId = Dispute__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Confidential').getRecordTypeId();
        Id offerCondentialRTId = DisputeOffer__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Confidential').getRecordTypeId();
        Id msgCondentialRTId = DisputeMessage__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Confidential').getRecordTypeId();
        Id caseCondentialRTId = Case.SObjectType.getDescribe().getRecordTypeInfosByName().get('Confidential').getRecordTypeId();
        Set<Id> confidentialRTs = new Set<Id>( new Id[]{ disputeCondentialRTId, offerCondentialRTId, msgCondentialRTId,  caseCondentialRTId } );

        String disputeKeyPrefix = Schema.Dispute__c.sObjectType.getDescribe().getKeyPrefix();
        String offerKeyPrefix = Schema.DisputeOffer__c.sObjectType.getDescribe().getKeyPrefix();
        String msgKeyPrefix = Schema.DisputeMessage__c.sObjectType.getDescribe().getKeyPrefix();
        String caseKeyPrefix = Schema.Case.sObjectType.getDescribe().getKeyPrefix();
        Map<String, Id> prefixRTs = new Map<String, Id>{ disputeKeyPrefix => disputeCondentialRTId, offerKeyPrefix => offerCondentialRTId, msgKeyPrefix => msgCondentialRTId, caseKeyPrefix => caseCondentialRTId };

        Map<Id, SObject> recordsForUpdate = new Map<Id, SObject>();
        Map<Id, SObject> allRecords = new Map<Id, SObject>();
        Map<Id, MIIncident__c> targetIncidents = new Map<Id, MIIncident__c>();
        Set<Id> disputeIds = new Set<Id>();

        for( MIIncident__c mi : [SELECT Id, RecordTypeId, (SELECT Id, RecordTypeId FROM Disputes__r), (SELECT Id, RecordType.Name FROM Cases__r) FROM MIIncident__c WHERE Id IN :triggerNewMap.values() LIMIT :triggerNewMap.size()] )
        {
            if( miCondentialRTId == mi.RecordTypeId )
            {
                targetIncidents.put( mi.Id, mi );
                allRecords.putAll(mi.Disputes__r);
                allRecords.putAll(mi.Cases__r);
                for( Dispute__c d: mi.Disputes__r )
                {
                    disputeIds.add( d.Id );
                }

            }
        }

        for( DisputeOffer__c offer: [SELECT Id, RecordTypeId, (SELECT Id, RecordTypeId FROM DisputeMessages__r) FROM DisputeOffer__c WHERE Dispute__c IN : disputeIds] )
        {
            allRecords.put( offer.Id, offer );
            allRecords.putAll( offer.DisputeMessages__r );
        }

        for( SObject record : allRecords.values() )
        {
            if( !confidentialRTs.contains( (Id)record.get( 'RecordTypeId' ) ) ) {

                String prefix = ((String)record.Id).substring(0,3);
                Id recordTypeId = prefixRTs.get( prefix );
                record.put( 'RecordTypeId', recordTypeId );
                recordsForUpdate.put( record.Id, record );
            }
        }

        if( !recordsForUpdate.isEmpty() )
        {
            QueueableUtility.handleQueueable( new DMLQueueable( recordsForUpdate.values(), DMLQueueable.Operation.UPDATES ) );
        }

    }


}