metadata-classic/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <description>L1 category issue - this is where the general area goes.</description>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Account / Profile</fullName>
                </value>
                <value>
                    <fullName>Chat</fullName>
                </value>
                <value>
                    <fullName>Customer Payments</fullName>
                </value>
                <value>
                    <fullName>Delete Account</fullName>
                </value>
                <value>
                    <fullName>Getting Started</fullName>
                </value>
                <value>
                    <fullName>Marketplace Integrity</fullName>
                </value>
                <value>
                    <fullName>Notifications</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Phone</fullName>
                </value>
                <value>
                    <fullName>Pricing and Payments</fullName>
                </value>
                <value>
                    <fullName>Instant Match</fullName>
                </value>
                <value>
                    <fullName>Quotes</fullName>
                </value>
                <value>
                    <fullName>Quoting Service</fullName>
                </value>
                <value>
                    <fullName>Refunds</fullName>
                </value>
                <value>
                    <fullName>Requests</fullName>
                </value>
                <value>
                    <fullName>Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ManualCaseCreation__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true indicates that the case was created by a manual process.</description>
        <label>Manual Case Creation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SubCategory__c</fullName>
        <label>Sub Category</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Category__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>App pricing / purchase</fullName>
                </value>
                <value>
                    <fullName>Background check</fullName>
                </value>
                <value>
                    <fullName>Background check (clear)</fullName>
                </value>
                <value>
                    <fullName>Background check (mismatch)</fullName>
                </value>
                <value>
                    <fullName>Background check (not clear)</fullName>
                </value>
                <value>
                    <fullName>Called for customer</fullName>
                </value>
                <value>
                    <fullName>Called for pro</fullName>
                </value>
                <value>
                    <fullName>Called for specific employee</fullName>
                </value>
                <value>
                    <fullName>Canceled request</fullName>
                </value>
                <value>
                    <fullName>Cash refund</fullName>
                </value>
                <value>
                    <fullName>Certification agreement</fullName>
                </value>
                <value>
                    <fullName>Churn</fullName>
                </value>
                <value>
                    <fullName>Competitive report</fullName>
                </value>
                <value>
                    <fullName>Competitor</fullName>
                </value>
                <value>
                    <fullName>Concerning review</fullName>
                </value>
                <value>
                    <fullName>Connection issues - didn&apos;t talk</fullName>
                </value>
                <value>
                    <fullName>Credentials</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - Call back needed</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - CC not provided</fullName>
                </value>
                <value>
                    <fullName>CS Assisted - PA Live</fullName>
                </value>
                <value>
                    <fullName>Customer / other</fullName>
                </value>
                <value>
                    <fullName>Customer contact</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Disconnected (pro or customer)</fullName>
                </value>
                <value>
                    <fullName>Disconnected (specialist)</fullName>
                </value>
                <value>
                    <fullName>Dispute</fullName>
                </value>
                <value>
                    <fullName>DMCA/Copyright</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Duplicate request</fullName>
                </value>
                <value>
                    <fullName>Dynamic pricing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <description>Text field to indicate the case owner&apos;s assigned team.  Populated via a workflow rule.</description>
        <label>Team</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/QuickCaseSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>Hardcoded ID or merge field</description>
        <label>Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <description>Hardcoded ID or merge field</description>
        <label>Contact Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Merge fields</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ManualCaseCreation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Case Creation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <description>Hardcoded ID or merge field</description>
        <label>OwnerId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>Record Type Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelateToIncident__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Relate to Incident</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Merge fields</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SuppliedEmail__c</fullName>
        <description>Hardcoded email or merge field</description>
        <label>Web Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quick Case Setting</label>
    <pluralLabel>Quick Case Settings</pluralLabel>
</CustomObject>

metadata-classic/classes/QuickCaseController.cls
/**
  Copyright (c) 2017 Thumbtack. All rights reserved.

  Version      Date          Author            Description
  ========+============+=================+================================================
  1.0      2017-12-01   Mendel Guillaume       Created
  ========+============+=================+===============================================
 */

public with sharing class QuickCaseController
{
	@AuraEnabled
	public static Case getDefaultCase()
	{
		QuickCaseSetting__mdt setting = [SELECT Id, MasterLabel, DeveloperName, AccountId__c, Category__c, ContactId__c,
				Description__c, ManualCaseCreation__c, Origin__c, OwnerId__c, Priority__c, RecordTypeId__c, RelateToIncident__c,
				Status__c, Subcategory__c, Subject__c, Team__c, SuppliedEmail__c
				FROM  QuickCaseSetting__mdt WHERE DeveloperName = 'GenericQuickCaseSetting'];
		Case c = new Case();

		c.Priority = setting.Priority__c;
		c.RecordTypeId = setting.RecordTypeId__c;
		c.Status = setting.Status__c;
		c.Origin = setting.Origin__c;
		c.Subject = setting.Subject__c;
		c.OwnerId = setting.OwnerId__c == '{$User.Id}' ? UserInfo.getUserId() : setting.OwnerId__c;

		if(setting.RecordTypeId__c != null)
		{
			c.RecordTypeId = setting.RecordTypeId__c;
		}

		c.ManualCaseCreation__c = setting.ManualCaseCreation__c;
		c.Description = setting.Description__c != null ? setting.Description__c.left(32000) : '';

		return c;
	}

	@AuraEnabled
	public static List<String> getCaseOrigins()
	{
		return System.Label.QuickCaseAvailableOrigins.replaceAll(', ', ',').split(',');
	}

	@AuraEnabled
	public static QuickCaseResult submitCase(Case c)
	{
		String result;

		try
		{
			insert c;

			result = 'Success';

			c = [SELECT Id, CaseNumber FROM Case WHERE Id = :c.Id];
		}
		catch (Exception ex)
		{
			result = ex.getMessage();
		}

		return new QuickCaseResult(c, result);
	}

	public class QuickCaseResult
	{
		@AuraEnabled
		public String result {get;set;}

		@AuraEnabled
		public Case caseRecord {get;set;}

		public QuickCaseResult(Case c, String result)
		{
			this.caseRecord = c;
			this.result = result;
		}
	}
}