metadata-classic/objects/CategorizationDefinition__c.object
<CustomObject>
    <description>Metadata object - the records from this object define what Categorization options are available for a given record.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not this Categorization Definition is currently available for use.</description>
        <inlineHelpText>Whether or not this Categorization Definition is currently available for use.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Available On Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnCase__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, this definition is available on the Case object.</description>
        <inlineHelpText>If true, this definition is available on the Case object.</inlineHelpText>
        <label>Available On Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnEnrollment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If checked, this definition is available on the Enrollment Object.</description>
        <inlineHelpText>If checked, this definition is available on the Enrollment Object.</inlineHelpText>
        <label>Available On Enrollment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CategoryType__c</fullName>
        <description>Category or Subcategory?</description>
        <inlineHelpText>Category or Subcategory?</inlineHelpText>
        <label>Category Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>Subcategory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this category available for Customers?</description>
        <label>Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Functional__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this a functional category?</description>
        <label>Functional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Key__c</fullName>
        <description>The unique key of this Categorization Definition</description>
        <displayFormat>{YYYY}{MM}-{000000}</displayFormat>
        <externalId>true</externalId>
        <inlineHelpText>The unique key of this Categorization Definition.</inlineHelpText>
        <label>Key</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>ParentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Category for use with Subcategories.</description>
        <inlineHelpText>The parent Category for use with Subcategories.</inlineHelpText>
        <label>Parent Category</label>
        <referenceTo>CategorizationDefinition__c</referenceTo>
        <relationshipLabel>Subcategories</relationshipLabel>
        <relationshipName>Subcategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this category available for Pros?</description>
        <label>Pro</label>
        <type>Checkbox</type>
    </fields>
    <label>Categorization Definition</label>
    <nameField>
        <label>Categorization Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorization Definitions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/CategorizationSearchController.cls
/*
   Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+================================================
   1.0      2017-10-25   Mendel Guillaume       Created
   ========+============+=================+===============================================
*/

public with sharing class CategorizationSearchController
{
	@AuraEnabled
	public static List<CategorizationDefinition__c> getCategorizationDefinitions(String searchText, String recordId)
	{
		searchText = '%' + searchText + '%';

		return Database.query('SELECT Id, Name, Key__c, ParentCategory__c, ParentCategory__r.Name, ParentCategory__r.Key__c, Pro__c, Customer__c, Functional__c ' +
				'FROM CategorizationDefinition__c ' +
				'WHERE Active__c = true AND ParentCategory__r.Active__c = true AND CategoryType__c = \'Subcategory\' AND ParentCategory__c != null ' +
						'AND (Name LIKE :searchText OR ParentCategory__r.Name LIKE :searchText) AND ' +
						(recordId != null && recordId.startsWith('500') ? 'AvailableOnCase__c = true ' : (recordId != null && recordId.startsWith('001') ? 'AvailableOnAccount__c = true ' : 'AvailableOnEnrollment__c = true ')) +
				'ORDER BY ParentCategory__r.Name, Name ' +
				'LIMIT 500');
	}
}