metadata-classic/objects/CategorizationSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>User settings for categorization page</description>
    <fields>
        <fullName>ShowCategoryTree__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Show Category Tree</label>
        <type>Checkbox</type>
    </fields>
    <label>Categorization Settings</label>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/CategorizationContainerController.cls
/*
   Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+================================================
   1.0      2017-11-14   Mendel Guillaume       Created
   ========+============+=================+===============================================
*/

public with sharing class CategorizationContainerController
{
	@AuraEnabled
	public static CategorizationSettings__c getUserSettings()
	{
		return CategorizationSettings__c.getInstance();
	}

	@AuraEnabled
	public static void toggleTreeSetting()
	{
		CategorizationSettings__c cs = CategorizationSettings__c.getInstance();

		cs.ShowCategoryTree__c = !cs.ShowCategoryTree__c;

		upsert cs;
	}
}