metadata-classic/objects/CategorizationDefinition__c.object
<CustomObject>
    <description>Metadata object - the records from this object define what Categorization options are available for a given record.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Whether or not this Categorization Definition is currently available for use.</description>
        <inlineHelpText>Whether or not this Categorization Definition is currently available for use.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AvailableOnCase__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If true, this definition is available on the Case object.</description>
        <inlineHelpText>If true, this definition is available on the Case object.</inlineHelpText>
        <label>Available On Case</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSATEligible__c</fullName>
        <description>The CSAT eligibility of this Definition</description>
        <inlineHelpText>The CSAT eligibility of this Definition</inlineHelpText>
        <label>CSAT Eligible</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Eligible</fullName>
                    <default>true</default>
                    <label>Eligible</label>
                </value>
                <value>
                    <fullName>Ineligible</fullName>
                </value>
                <value>
                    <fullName>Always Eligible</fullName>
                    <isActive>false</isActive>
                    <label>Always Eligible</label>
                </value>
                <value>
                    <fullName>Always Ineligible</fullName>
                    <isActive>false</isActive>
                    <label>Always Ineligible</label>
                </value>
                <value>
                    <fullName>Ineligible if Primary</fullName>
                    <isActive>false</isActive>
                    <label>Ineligible if Primary</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CategoryType__c</fullName>
        <description>Category or Subcategory?</description>
        <inlineHelpText>Category or Subcategory?</inlineHelpText>
        <label>Category Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Category</fullName>
                </value>
                <value>
                    <fullName>Subcategory</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this category available for Customers?</description>
        <label>Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Functional__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this a functional category?</description>
        <label>Functional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ParentCategory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The parent Category for use with Subcategories.</description>
        <inlineHelpText>The parent Category for use with Subcategories.</inlineHelpText>
        <label>Parent Category</label>
        <referenceTo>CategorizationDefinition__c</referenceTo>
        <relationshipLabel>Subcategories</relationshipLabel>
        <relationshipName>Subcategories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Pro__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UI organization bucket - is this category available for Pros?</description>
        <label>Pro</label>
        <type>Checkbox</type>
    </fields>
    <label>Categorization Definition</label>
    <nameField>
        <label>Categorization Definition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categorization Definitions</pluralLabel>
    <recordTypes>
        <fullName>Category</fullName>
        <active>true</active>
        <description>Category/Subcategory</description>
        <label>Category</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/CategorizationSearchControllerTest.cls
/*
   Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+================================================
   1.0      2017-11-01   Mendel Guillaume       Created
   ========+============+=================+===============================================
*/

@IsTest
private class CategorizationSearchControllerTest
{
	@TestSetup
	static void createData()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			List<CategorizationDefinition__c> categories = new List<CategorizationDefinition__c>();
			categories.add(new CategorizationDefinition__c(Name = 'Parent 1', Active__c = true, AvailableOnCase__c = true, Pro__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Parent 2', Active__c = true, AvailableOnCase__c = true, Customer__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Parent 3', Active__c = true, AvailableOnCase__c = true, Functional__c = true,
					CategoryType__c = 'Category', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			insert categories;

			categories.add(new CategorizationDefinition__c(Name = 'Child 1a', Active__c = true, AvailableOnCase__c = true,
					Pro__c = true, ParentCategory__c = categories[0].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Child 2a', Active__c = true, AvailableOnCase__c = true,
					Pro__c = true, ParentCategory__c = categories[0].Id, CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Child 1b', Active__c = true, AvailableOnCase__c = true,
					Customer__c = true, ParentCategory__c = categories[1].Id,  CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));
			categories.add(new CategorizationDefinition__c(Name = 'Child 1c', Active__c = true, AvailableOnCase__c = true,
					Functional__c = true, ParentCategory__c = categories[2].Id,  CSATEligible__c = 'Eligible',
					CategoryType__c = 'Subcategory', RecordTypeId = CategorizationCategoriesPanelController.CATEGORIZATION_DEFINITION_CATEGORY_RT_ID));

			upsert categories;
		}
	}

	@IsTest
	static void testSearch()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();
			List<CategorizationDefinition__c> cds = CategorizationSearchController.getCategorizationDefinitions('x', '500');
			System.assertEquals(0, cds.size());

			cds = CategorizationSearchController.getCategorizationDefinitions('Child', '500');
			System.assertEquals(4, cds.size());

			cds = CategorizationSearchController.getCategorizationDefinitions('Parent 1', '500');
			System.assertEquals(2, cds.size());

			cds = CategorizationSearchController.getCategorizationDefinitions('Parent 2', '500');
			System.assertEquals(1, cds.size());
			Test.stopTest();
		}
	}
}