metadata-classic/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Customer</fullName>
        <active>true</active>
        <description>This record type is used for all thumbtack customers</description>
        <label>Customer</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/Dispute__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeContent__c.object
<CustomObject>
    <description>Custom object to store meta data definitions of the content templates (e.g., tips, messages) used for the Solution Center.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist whose values indicate the overall publication status of the Dispute Content record.</description>
        <inlineHelpText>Picklist whose values indicate the overall publication status of the Dispute Content record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Needs approval</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Field whose values describe the type of success tip content.</description>
        <inlineHelpText>Field whose values describe the type of success tip content.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automated tip</fullName>
                </value>
                <value>
                    <fullName>Manual tip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dispute Content</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Content</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/DisputeExperience__c.object
<CustomObject>
    <description>Custom object that will store the Solution Center dispute experience configuration records.</description>
    <fields>
        <fullName>DefaultExperience__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate if the record is used as the default dispute experience.</description>
        <inlineHelpText>Indicates if this dispute experience is the default experience for the Solution Center.</inlineHelpText>
        <label>Default Experience</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResolutionOptions__c</fullName>
        <description>The available resolution options for an agent to select from when creating a dispute.  Used in lightning component.</description>
        <inlineHelpText>The available resolution options for an agent to select from when creating a dispute.</inlineHelpText>
        <label>Resolution Options (Agent facing)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete or redo the work</fullName>
                </value>
                <value>
                    <fullName>Complete or redo the work and refund</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist whose values indicate the overall publication status of the Dispute Experience.</description>
        <inlineHelpText>Publication status of the dispute experience.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Needs approval</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dispute Experience</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Experiences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/DisputeMessage__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeOffer__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the contact record for the customer associated with the incident.</description>
        <label>Customer Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the contact record for the pro associated to the incident.</description>
        <label>Pro Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bid_id__c</fullName>
        <description>External bid/quote ID from the the TT database.</description>
        <externalId>true</externalId>
        <label>bid_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/SCConfigDisputeOffer__c.object
<CustomObject>
    <description>Custom Object for Solution Center to capture &apos;Resolution&apos; related to a Dispute with information on Resolution Type, Status and other information</description>
    <fields>
        <fullName>Dispute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dispute</label>
        <referenceTo>Dispute__c</referenceTo>
        <relationshipLabel>Dispute Offers</relationshipLabel>
        <relationshipName>DisputeOffers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RespondingAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The pro or customer that needs to respond to the dispute offer.</description>
        <label>Responding Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Dispute Offers</relationshipLabel>
        <relationshipName>DisputeOffers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RespondingContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The pro or customer contact that is the responding party to the dispute offer.</description>
        <label>Responding Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Dispute Offers</relationshipLabel>
        <relationshipName>DisputeOffers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete the work</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Complete the work and refund</fullName>
                </value>
                <value>
                    <fullName>Suggest a different completion date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dispute Offer</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Offers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/QuickTipControllerTest.cls
/**
 * Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+===============================================
   1.0      2018-01-17   Mendel Guillaume       Created
   ========+============+=================+===============================================
 */

@IsTest
private class QuickTipControllerTest
{
	@TestSetup
	static void createData()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
			Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
			insert new List<Account>{customer, pro};

			Contact customerContact = new Contact(LastName = 'Customer', AccountId = customer.Id, RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
			Contact proContact = new Contact(LastName = 'Pro', AccountId = pro.Id, RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
			insert new List<Contact>{customerContact, proContact};

			MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id,
					bid_id__c = '123456', CustomerContact__c = customerContact.Id, ProContact__c = proContact.Id);
			insert incident;

			DisputeExperience__c defaultExp = new DisputeExperience__c (DefaultExperience__c = true, Status__c = 'Published',
					Name = 'Default', ResolutionOptions__c = 'Refund;Complete Work');

			insert defaultExp;

			Dispute__c d = new Dispute__c(Name = 'Test Dispute', InitiatorContact__c = customerContact.Id, InitiatorAccount__c = customer.Id,
				ResponderContact__c = proContact.Id, ResponderAccount__c = pro.Id, MIIncident__c = incident.Id, DisputeExperience__c = defaultExp.Id);
			insert d;

			DisputeOffer__c offer = new DisputeOffer__c(Name = 'Test offer', Dispute__c = d.Id);
			insert offer;

			DisputeContent__c successTip = new DisputeContent__c(Name = 'Test', Status__c = 'Published', Type__c = 'Automated tip',
					RecordTypeId = Schema.SObjectType.DisputeContent__c.getRecordTypeInfosByName().get('Content Template').getRecordTypeId());
			insert successTip;

			User newUser = new User();
			newUser.alias = 'custTest';
			newUser.email = 'zzzz@test.com';
			newUser.emailencodingkey = 'UTF-8';
			newUser.firstname = 'Contact';
			newUser.lastname = 'Customer';
			newUser.languagelocalekey = 'en_US';
			newUser.localesidkey = 'en_US';
			newUser.timezonesidkey = 'America/Los_Angeles';
			newUser.username = 'dsfkl@dslngsdn.omf';
			newUser.Country = 'United States';
			newUser.ProfileId = [SELECT id FROM Profile WHERE Name = 'Thumbtack User' LIMIT 1].Id;
			newUser.contactId = customerContact.Id;

			insert newUser;
		}
	}

	@IsTest
	static void testGetDispute()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Dispute__c dispute = [SELECT Id FROM Dispute__c];

			Test.startTest();

			System.assertEquals(dispute.Id, QuickTipController.getDispute(dispute.Id).Id);

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetUserId()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Contact customer = [SELECT Id FROM Contact WHERE LastName = 'Customer'];

			Test.startTest();

			System.assertNotEquals(null, QuickTipController.getUserId(customer.Id));

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetSuccessTips()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assert(!QuickTipController.getSuccessTips().isEmpty());

			Test.stopTest();
		}
	}

	@IsTest
	static void testSaveMessage()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Dispute__c dispute = [SELECT Id, (Select Id FROM DisputeOffers__r) FROM Dispute__c];
			Contact customer = [SELECT Id FROM Contact WHERE LastName = 'Customer'];
			DisputeMessage__c dm = new DisputeMessage__c(Message__c = 'Testing', DisputeOffer__c = dispute.DisputeOffers__r[0].Id, ContactSharedWith__c = customer.Id);

			Test.startTest();

			System.assertEquals('Success', QuickTipController.saveMessage(dm, null));

			Test.stopTest();
		}
	}

	@IsTest
	static void testSaveMessageError()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Dispute__c dispute = [SELECT Id, (Select Id FROM DisputeOffers__r) FROM Dispute__c];
			Contact customer = [SELECT Id FROM Contact WHERE LastName = 'Customer'];
			DisputeMessage__c dm = new DisputeMessage__c(Message__c = 'Testing', DisputeOffer__c = dispute.DisputeOffers__r[0].Id, ContactSharedWith__c = customer.Id);
			delete new DisputeOffer__c(Id = dispute.DisputeOffers__r[0].Id);

			Test.startTest();

			System.assertNotEquals('Success', QuickTipController.saveMessage(dm, null));

			Test.stopTest();
		}
	}
}