metadata-classic/objects/Dispute__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeContent__c.object
<CustomObject>
    <description>Custom object to store meta data definitions of the content templates (e.g., tips, messages) used for the Solution Center.</description>
    <fields>
        <fullName>MessageTemplate__c</fullName>
        <description>The template text of a success tip or message that will be created for the initiator or responder of a solution center dispute.</description>
        <inlineHelpText>The template text of a success tip or message that will be created for the initiator or responder of a solution center dispute.</inlineHelpText>
        <label>Message Template</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist whose values indicate the overall publication status of the Dispute Content record.</description>
        <inlineHelpText>Picklist whose values indicate the overall publication status of the Dispute Content record.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Needs approval</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Field whose values describe the type of success tip content.</description>
        <inlineHelpText>Field whose values describe the type of success tip content.</inlineHelpText>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Automated tip</fullName>
                </value>
                <value>
                    <fullName>Manual tip</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dispute Content</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Content</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/DisputeMessage__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeOffer__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/SCConfigDisputeOffer__c.object
<CustomObject>
    <description>Custom Object for Solution Center to capture &apos;Resolution&apos; related to a Dispute with information on Resolution Type, Status and other information</description>
    <fields>
        <fullName>Dispute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Dispute</label>
        <referenceTo>Dispute__c</referenceTo>
        <relationshipLabel>Dispute Offers</relationshipLabel>
        <relationshipName>DisputeOffers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Complete the work</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Complete the work and refund</fullName>
                </value>
                <value>
                    <fullName>Suggest a different completion date</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dispute Offer</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Offers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/QuickTipController.cls
/**
 * Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+===============================================
   1.0      2018-01-17   Mendel Guillaume       Created
   ========+============+=================+===============================================
 */

public with sharing class QuickTipController
{
	@AuraEnabled
	public static Dispute__c getDispute(String disputeId)
	{
		return [SELECT Id, InitiatorContact__c, InitiatorContact__r.Name, ResponderContact__c, ResponderContact__r.Name,
				InternalLinkInitiator__c, InternalLinkResponder__c,
				(SELECT Id FROM DisputeOffers__r ORDER BY CreatedDate DESC LIMIT 1)
				FROM Dispute__c WHERE Id = :disputeId];
	}

	@AuraEnabled
	public static List<DisputeContentWrapper> getSuccessTips()
	{
		List<DisputeContentWrapper> dcs = new List<QuickTipController.DisputeContentWrapper>();

		for(DisputeContent__c dc : [SELECT Id, Name, MessageTemplate__c, Type__c
				FROM DisputeContent__c
				WHERE Status__c = 'Published' AND Type__c IN ('Automated tip', 'Manual tip') AND RecordType.Name = 'Content Template'])
		{
			dcs.add(new DisputeContentWrapper(dc));
		}

		return dcs;
	}

	@AuraEnabled
	public static Id getUserId(String contactId)
	{
		Id userId = null;

		if(String.isNotBlank(contactId))
		{
			List<User> users = [SELECT Id FROM User WHERE ContactId = :contactId];

			if(!users.isEmpty())
			{
				userId = users[0].Id;
			}
		}

		return userId;
	}

	@AuraEnabled
	public static String saveMessage(DisputeMessage__c message, String cloneId)
	{
		String success = 'Success';
		List<DisputeMessage__c> messages = new List<DisputeMessage__c>();
		List<DisputeOffer__c> offers = [SELECT Id FROM DisputeOffer__c
										WHERE Dispute__c = :message.Dispute__c
										ORDER BY CreatedDate DESC
										LIMIT 1];

		try
		{
			if(!offers.isEmpty() && offers[0].Id != message.DisputeOffer__c)
			{
				message.DisputeOffer__c = offers[0].Id;
			}

			message.RecordTypeId = DisputeMessage__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Success Tip').getRecordTypeId();
			messages.add(message);

			if(String.isNotBlank(cloneId))
			{
				DisputeMessage__c mClone = message.clone();
				mClone.ContactSharedWith__c = cloneId;
				messages.add(mClone);
			}

			insert messages;
		}
		catch (Exception ex)
		{
			success = ex.getMessage();
		}

		return success;
	}

	public class DisputeContentWrapper
	{
		@AuraEnabled
		public String template {get{return this.record != null && this.record.MessageTemplate__c != null ? this.record.MessageTemplate__c.stripHtmlTags() : '';}}

		@AuraEnabled
		public DisputeContent__c record{get;set;}

		public DisputeContentWrapper(DisputeContent__c dc)
		{
			this.record = dc;
		}
	}
}