metadata-classic/objects/Dispute__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeExperience__c.object
<CustomObject>
    <description>Custom object that will store the Solution Center dispute experience configuration records.</description>
    <fields>
        <fullName>DefaultExperience__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate if the record is used as the default dispute experience.</description>
        <inlineHelpText>Indicates if this dispute experience is the default experience for the Solution Center.</inlineHelpText>
        <label>Default Experience</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResolutionOptions__c</fullName>
        <description>The available resolution options for an agent to select from when creating a dispute.  Used in lightning component.</description>
        <inlineHelpText>The available resolution options for an agent to select from when creating a dispute.</inlineHelpText>
        <label>Resolution Options (Agent facing)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete or redo the work</fullName>
                </value>
                <value>
                    <fullName>Complete or redo the work and refund</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist whose values indicate the overall publication status of the Dispute Experience.</description>
        <inlineHelpText>Publication status of the dispute experience.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Needs approval</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dispute Experience</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Experiences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bid_id__c</fullName>
        <description>External bid/quote ID from the the TT database.</description>
        <externalId>true</externalId>
        <label>bid_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>request_category__c</fullName>
        <description>The category of the request related to the bid_id of the incident; used in workflows and populated via SF Connect.</description>
        <label>request_category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/DisputeStartStopControllerTest.cls
/**
 * Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+===============================================
   1.0      2018-02-22   Mendel Guillaume       Created
   ========+============+=================+===============================================
 */
@IsTest
private class DisputeStartStopControllerTest
{
	@TestSetup
	static void createData()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
			insert customer;

			Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
			insert pro;

			MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id, bid_id__c = '123456');
			insert incident;

			DisputeExperience__c defaultExp = new DisputeExperience__c (DefaultExperience__c = true, Status__c = 'Published',
					Name = 'Default', ResolutionOptions__c = 'Refund;Complete Work');

			insert defaultExp;

			Dispute__c d = new Dispute__c(MIIncident__c = incident.Id, Status__c = 'Awaiting', Stage__c = 'Initiator confirmation needed',
					DisputeExperience__c = defaultExp.Id, request_category__c = 'Test Category',
					request_city__c = 'Salt Lake City', request_state__c = 'UT', request_zip__c = '84044');

			insert d;
		}
	}

	@IsTest
	static void testGetStatuses()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assert(DisputeStartStopController.getStatuses().size() > 0, 'No statuses');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetStatusesMap()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assert(DisputeStartStopController.getStatusMap().size() > 0, 'No statuses');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetAndSaveDispute()
	{
		Dispute__c d = [SELECT Id FROM Dispute__c];

		Test.startTest();

		d = DisputeStartStopController.getDispute(d.Id);
		d.Status__c = 'Under review';

		String result = DisputeStartStopController.saveDispute(d);

		Test.stopTest();

		System.assertEquals('Success', result, 'Dispute not saved');
	}
}