metadata-classic/objects/Dispute__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/DisputeExperience__c.object
<CustomObject>
    <description>Custom object that will store the Solution Center dispute experience configuration records.</description>
    <fields>
        <fullName>DefaultExperience__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checkbox to indicate if the record is used as the default dispute experience.</description>
        <inlineHelpText>Indicates if this dispute experience is the default experience for the Solution Center.</inlineHelpText>
        <label>Default Experience</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ResolutionOptions__c</fullName>
        <description>The available resolution options for an agent to select from when creating a dispute.  Used in lightning component.</description>
        <inlineHelpText>The available resolution options for an agent to select from when creating a dispute.</inlineHelpText>
        <label>Resolution Options (Agent facing)</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Complete or redo the work</fullName>
                </value>
                <value>
                    <fullName>Complete or redo the work and refund</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist whose values indicate the overall publication status of the Dispute Experience.</description>
        <inlineHelpText>Publication status of the dispute experience.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                </value>
                <value>
                    <fullName>Needs approval</fullName>
                </value>
                <value>
                    <fullName>Published</fullName>
                </value>
                <value>
                    <fullName>Archived</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Dispute Experience</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dispute Experiences</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>bid_id__c</fullName>
        <description>External bid/quote ID from the the TT database.</description>
        <externalId>true</externalId>
        <label>bid_id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/DisputeControllerTest.cls
/**
 * Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+===============================================
   1.0      2018-01-16   Mendel Guillaume       Created
   ========+============+=================+===============================================
 */

@IsTest
private class DisputeControllerTest
{
	@TestSetup
	static void createData()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
			insert customer;

			Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
			insert pro;

			MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id, bid_id__c = '123456');
			insert incident;

			DisputeExperience__c defaultExp = new DisputeExperience__c (DefaultExperience__c = true, Status__c = 'Published',
					Name = 'Default', ResolutionOptions__c = 'Refund;Complete Work');
			DisputeExperience__c de1 = new DisputeExperience__c (DefaultExperience__c = false, Status__c = 'Published',
					Name = 'Dex 1', ResolutionOptions__c = 'Option 1');

			insert new List<DisputeExperience__c>{defaultExp, de1};
		}
	}

	@IsTest
	static void testGetIncident()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];

			Test.startTest();

			System.assertEquals(incident.Id, DisputeController.getIncident(incident.Id).Id);

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetResolutionOptions()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			List<DisputeExperience__c> des = [SELECT Id FROM DisputeExperience__c ORDER BY Name];

			Test.startTest();

			System.assertEquals(2, DisputeController.getResolutions(des[0].Id).size());
			System.assertEquals(1, DisputeController.getResolutions(des[1].Id).size());

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetAndSaveDispute()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];
			DisputeExperience__c defaultExp = [SELECT Id FROM DisputeExperience__c WHERE DefaultExperience__c = true];
			Dispute__c d = DisputeController.getNewDispute(incident.Id);

			Test.startTest();

			System.assertEquals(defaultExp.Id, d.DisputeExperience__c);
			System.assertEquals('Success', DisputeController.saveDispute(d));

			Test.stopTest();
		}
	}

	@IsTest
	static void testSaveDisputeError()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];
			Dispute__c d = DisputeController.getNewDispute(incident.Id);
			delete incident;

			Test.startTest();

			System.assertNotEquals('Success', DisputeController.saveDispute(d));

			Test.stopTest();
		}
	}
}