metadata-classic/objects/Enrollment__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/EnrollmentAction__c.object
<CustomObject>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <referenceTo>Enrollment__c</referenceTo>
        <relationshipLabel>Enrollment Action</relationshipLabel>
        <relationshipName>EnrollmentSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OutreachDisposition__c</fullName>
        <label>Outreach Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentOutreachDisposition</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuleId__c</fullName>
        <label>Rule ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentActionType</valueSetName>
        </valueSet>
    </fields>
    <label>Enrollment Action</label>
    <nameField>
        <label>Enrollment Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/EnrollmentRule__c.object
<CustomObject>
    <description>Customer rule that shows what has been completed on the related enrollment.</description>
    <fields>
        <fullName>EnrollmentActionType__c</fullName>
        <label>Enrollment Action Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentActionType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentFunnelStep__c</fullName>
        <label>Enrollment Funnel Step</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentFunnelStep</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentOutreachDisposition__c</fullName>
        <label>Enrollment Outreach Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentOutreachDisposition</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentOutreachType__c</fullName>
        <label>Enrollment Outreach Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OutreachType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SetEnrollmentFunnelStepTo__c</fullName>
        <label>Set Enrollment Funnel Step to</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentFunnelStep</valueSetName>
        </valueSet>
    </fields>
    <label>Enrollment Rule</label>
    <nameField>
        <label>Enrollment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Market__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/RequestCategory__c.object
<CustomObject>
    <description>All available category.</description>
    <label>Request Category</label>
    <nameField>
        <label>Request Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/ProFeedControllerTest.cls
@isTest
private class ProFeedControllerTest {
	
	@isTest static void getFeedItems_test() {
		
		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account acc = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(acc.Id, true);

		EnrollmentRule__c rule = new EnrollmentRule__c (
			Name = 'test rule',
			EnrollmentActionType__c = 'Outreach Attempt',
			EnrollmentOutreachType__c = 'Early_enrollment',
			EnrollmentFunnelStep__c = 'Ready',
			EnrollmentOutreachDisposition__c = 'No Attempt Necessary',
			IsActive__c = true,
			SetEnrollmentFunnelStepTo__c = 'Attempted'
		);
		insert rule;

		EnrollmentAction__c action = new EnrollmentAction__c (
			Name = rule.Name,
			Enrollment__c = enrollment.Id,
			RuleId__c = String.valueOf(rule.Id),
			Type__c = 'Outreach Attempt',
			OutreachDisposition__c = 'No Attempt Necessary'
		);
		EnrollmentActionManagerController.createEnrollmentAction(action, null, null, null);

		Test.startTest();

		List<EnrollmentAction__c> result = ProFeedController.getFeedItems(acc.Id, 'Outreach Attempt', enrollment.Id);

		Test.stopTest();

		System.assertEquals(action.Id, result[0].Id);

	}

	@isTest static void getTaskFeedItems_test() {

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account acc = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(acc.Id, true);

		Task t = new Task (
			CallType = 'Outbound',
			WhatId = enrollment.Id
		);
		insert t;

		Test.startTest();

		List<Map<String, SObject>> result = ProFeedController.getTaskFeedItems(acc.Id, enrollment.Id);

		Test.stopTest();

		System.assertEquals(enrollment.Id, result[0].get('Enrollment__r').Id);
		System.assertEquals(t.Id, result[0].get('Task').Id);

	}
	
}