metadata-classic/objects/Enrollment__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/EnrollmentAction__c.object
<CustomObject>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <referenceTo>Enrollment__c</referenceTo>
        <relationshipLabel>Enrollment Action</relationshipLabel>
        <relationshipName>EnrollmentSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EventLogField__c</fullName>
        <label>Event Log Field</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>EventLogObject__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>EventLogField</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventLogObject__c</fullName>
        <label>Event Log Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EventLogObject</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuleId__c</fullName>
        <label>Rule ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentActionType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>outreach_type__c</fullName>
        <label>Outreach Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OutreachType</valueSetName>
        </valueSet>
    </fields>
    <label>Enrollment Action</label>
    <nameField>
        <label>Enrollment Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/EnrollmentRule__c.object
<CustomObject>
    <description>Customer rule that shows what has been completed on the related enrollment.</description>
    <fields>
        <fullName>EnrollmentActionType__c</fullName>
        <label>Enrollment Action Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentActionType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentFunnelStep__c</fullName>
        <label>Enrollment Funnel Step</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentFunnelStep</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentOutreachGroup__c</fullName>
        <label>Enrollment Outreach Group</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentOutreachGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentOutreachType__c</fullName>
        <label>Enrollment Outreach Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OutreachType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventLogField__c</fullName>
        <label>Event Log Field</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>EventLogObject__c</controllingField>
            <restricted>true</restricted>
            <valueSetName>EventLogField</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventLogObjectEnrollmentRelationship__c</fullName>
        <label>Event Log Object Enrollment Relationship</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>EventLogObject__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Id</fullName>
                    <label>Self</label>
                </value>
                <value>
                    <fullName>Market__r.RequestCategory__c</fullName>
                    <label>Enrollment&apos;s Request Category</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EventLogObject__c</fullName>
        <label>Event Log Object</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EventLogObject</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SetEnrollmentFunnelStepTo__c</fullName>
        <label>Set Enrollment Funnel Step to</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentFunnelStep</valueSetName>
        </valueSet>
    </fields>
    <label>Enrollment Rule</label>
    <nameField>
        <label>Enrollment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Market__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/RequestCategory__c.object
<CustomObject>
    <description>All available category.</description>
    <fields>
        <fullName>outreach_type__c</fullName>
        <label>Outreach Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OutreachType</valueSetName>
        </valueSet>
    </fields>
    <label>Request Category</label>
    <nameField>
        <label>Request Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/EnrollmentEventLogUtilityTest.cls
@isTest
private class EnrollmentEventLogUtilityTest {
	
	@isTest static void handleObjectChanges_skipSteps_test() {
		
		EnrollmentRule__c eventRule = new EnrollmentRule__c (
			Name = 'test rule',
			EnrollmentActionType__c = 'Event Log',
			EventLogObject__c = 'Enrollment__c',
			EventLogField__c = 'FunnelStep__c',
			EventLogObjectEnrollmentRelationship__c = 'Id',
			IsActive__c = true
		);
		insert eventRule;

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account acc = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(acc.Id, true);

		EnrollmentRule__c rule = new EnrollmentRule__c (
			Name = 'test rule',
			EnrollmentActionType__c = 'Onboarding Step',
			EnrollmentOutreachType__c = 'Early_enrollment',
			EnrollmentOutreachGroup__c = '1_VIP',
			EnrollmentFunnelStep__c = 'Ready',
			IsActive__c = true,
			SetEnrollmentFunnelStepTo__c = 'Interested'
		);
		insert rule;

		EnrollmentAction__c action = new EnrollmentAction__c (
			Name = rule.Name,
			Enrollment__c = enrollment.Id,
			RuleId__c = String.valueOf(rule.Id),
			Type__c = 'Onboarding Step'
		);
		EnrollmentActionManagerController.createEnrollmentAction(action, null, null, null);

		Test.startTest();

		EnrollmentActionManagerController.handleEnrollmentUpdate(enrollment.Id, 'Early_enrollment', '1_VIP');

		Test.stopTest();

		List<EnrollmentAction__c> result = [Select Id From EnrollmentAction__c Where Type__c = 'Event Log'];

		System.assertEquals(3, result.size());

	}

	@isTest static void handleObjectChanges_reverse_test() {
		
		EnrollmentRule__c eventRule = new EnrollmentRule__c (
			Name = 'test rule',
			EnrollmentActionType__c = 'Event Log',
			EventLogObject__c = 'Enrollment__c',
			EventLogField__c = 'FunnelStep__c',
			EventLogObjectEnrollmentRelationship__c = 'Id',
			IsActive__c = true
		);
		insert eventRule;

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account acc = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(acc.Id, true);

		EnrollmentRule__c rule = new EnrollmentRule__c (
			Name = 'test rule',
			EnrollmentActionType__c = 'Onboarding Step',
			EnrollmentOutreachType__c = 'Early_enrollment',
			EnrollmentOutreachGroup__c = '1_VIP',
			EnrollmentFunnelStep__c = 'Ready',
			IsActive__c = true,
			SetEnrollmentFunnelStepTo__c = 'Interested'
		);
		insert rule;

		EnrollmentAction__c action = new EnrollmentAction__c (
			Name = rule.Name,
			Enrollment__c = enrollment.Id,
			RuleId__c = String.valueOf(rule.Id),
			Type__c = 'Onboarding Step'
		);
		EnrollmentActionManagerController.createEnrollmentAction(action, null, null, null);

		Test.startTest();

		EnrollmentActionManagerController.handleEnrollmentUpdate(enrollment.Id, 'Early_enrollment', '1_VIP');

		List<EnrollmentAction__c> result = [Select Id From EnrollmentAction__c Where Type__c = 'Event Log'];

		//System.assertEquals(3, result.size());

		delete action;

		EnrollmentActionManagerController.handleEnrollmentUpdate(enrollment.Id, 'Early_enrollment', '1_VIP');

		Test.stopTest();

		result = [Select Id From EnrollmentAction__c Where Type__c = 'Event Log'];

		System.assertEquals(6, result.size());

	}

	@isTest static void handleObjectChanges_outreachTypeChange_test() {
		
		EnrollmentRule__c eventRule = new EnrollmentRule__c (
			Name = 'test rule',
			EnrollmentActionType__c = 'Event Log',
			EventLogObject__c = 'RequestCategory__c',
			EventLogField__c = 'outreach_type__c',
			EventLogObjectEnrollmentRelationship__c = 'Market__r.RequestCategory__c',
			IsActive__c = true
		);
		insert eventRule;

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account acc = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(acc.Id, true);

		Test.startTest();

		cat.outreach_type__c = 'Product_enabled';
		update cat;

		Test.stopTest();

		List<EnrollmentAction__c> result = [Select Id From EnrollmentAction__c Where Type__c = 'Event Log'];

		System.assertEquals(1, result.size());

	}
	
}