metadata-classic/objects/Enrollment__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/EnrollmentAction__c.object
<CustomObject>
    <fields>
        <fullName>CompletedBy__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Completed By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>EnrollmentAction</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Enrollment__c</fullName>
        <label>Enrollment</label>
        <referenceTo>Enrollment__c</referenceTo>
        <relationshipLabel>Enrollment Action</relationshipLabel>
        <relationshipName>EnrollmentSteps</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>OutreachDisposition__c</fullName>
        <label>Outreach Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentOutreachDisposition</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>RuleId__c</fullName>
        <label>Rule ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentActionType</valueSetName>
        </valueSet>
    </fields>
    <label>Enrollment Action</label>
    <nameField>
        <label>Enrollment Step Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Action</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/objects/EnrollmentRule__c.object
<CustomObject>
    <description>Customer rule that shows what has been completed on the related enrollment.</description>
    <fields>
        <fullName>EnrollmentActionType__c</fullName>
        <label>Enrollment Action Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentActionType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentFunnelStep__c</fullName>
        <label>Enrollment Funnel Step</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentFunnelStep</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentOutreachDisposition__c</fullName>
        <label>Enrollment Outreach Disposition</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentOutreachDisposition</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentOutreachGroup__c</fullName>
        <label>Enrollment Outreach Group</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentOutreachGroup</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>EnrollmentOutreachType__c</fullName>
        <label>Enrollment Outreach Type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OutreachType</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SetEnrollmentFunnelStepTo__c</fullName>
        <label>Set Enrollment Funnel Step to</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>EnrollmentFunnelStep</valueSetName>
        </valueSet>
    </fields>
    <label>Enrollment Rule</label>
    <nameField>
        <label>Enrollment Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Enrollment Rules</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Market__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/RequestCategory__c.object
<CustomObject>
    <description>All available category.</description>
    <label>Request Category</label>
    <nameField>
        <label>Request Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/ProEnrollmentManagerControllerTest.cls
@isTest
private class ProEnrollmentManagerControllerTest {

	@isTest static void getAllEnrollments_test() {

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account a = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(a.Id, false);
		Enrollment__c enrollment2 = EAPTestUtility.createEnrollment(a.Id, false);
		enrollment2.enrollment_id__c = '2';
		insert new List<Enrollment__c> {enrollment, enrollment2};

		Test.startTest();

		List<Enrollment__c> result = ProEnrollmentManagerController.getAllEnrollments(enrollment.Id);

		Test.stopTest();

		System.assertEquals(2, result.size());

	}

	@isTest static void getEnrollment_test() {

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account a = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(a.Id, true);

		Test.startTest();

		Enrollment__c result = ProEnrollmentManagerController.getEnrollment(enrollment.Id);

		Test.stopTest();

		System.assertEquals(enrollment.Id, result.Id);

	}

	@isTest static void createEnrollmentActions_test() {

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account a = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(a.Id, true);

		EnrollmentRule__c rule = new EnrollmentRule__c (
			Name = 'test rule',
			EnrollmentActionType__c = 'Outreach Attempt',
			EnrollmentOutreachType__c = 'Early_enrollment',
			EnrollmentFunnelStep__c = 'Ready',
			EnrollmentOutreachDisposition__c = 'No Attempt Necessary',
			IsActive__c = true,
			SetEnrollmentFunnelStepTo__c = 'Attempted'
		);
		insert rule;

		EnrollmentAction__c action = new EnrollmentAction__c (
			Name = rule.Name,
			Enrollment__c = enrollment.Id,
			RuleId__c = String.valueOf(rule.Id),
			Type__c = 'Outreach Attempt',
			OutreachDisposition__c = 'No Attempt Necessary'
		);

		Test.startTest();

		List<EnrollmentAction__c> result = ProEnrollmentManagerController.createEnrollmentActions(new List<EnrollmentAction__c> {action});

		Test.stopTest();

		System.assertEquals(UserInfo.getUserId(), result[0].CompletedBy__c);

	}

	@isTest static void handleEnrollmentUpdates_test() {

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account a = EAPTestUtility.createAccount(true);

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(a.Id, true);

		EnrollmentRule__c rule = new EnrollmentRule__c (
			Name = 'test rule',
			EnrollmentActionType__c = 'Outreach Attempt',
			EnrollmentOutreachType__c = 'Early_enrollment',
			EnrollmentOutreachGroup__c = '1_VIP',
			EnrollmentFunnelStep__c = 'Ready',
			EnrollmentOutreachDisposition__c = 'No Attempt Necessary',
			IsActive__c = true,
			SetEnrollmentFunnelStepTo__c = 'Attempted'
		);
		insert rule;

		EnrollmentAction__c action = new EnrollmentAction__c (
			Name = rule.Name,
			Enrollment__c = enrollment.Id,
			RuleId__c = String.valueOf(rule.Id),
			Type__c = 'Outreach Attempt',
			OutreachDisposition__c = 'No Attempt Necessary'
		);
		ProEnrollmentManagerController.createEnrollmentActions(new List<EnrollmentAction__c> {action});

		Test.startTest();

		List<Enrollment__c> result = ProEnrollmentManagerController.handleEnrollmentUpdates(new List<Id> {enrollment.Id});

		Test.stopTest();

		System.assertEquals(enrollment.Id, result[0].Id);
		System.assertEquals('Attempted', result[0].FunnelStep__c);

	}

	@isTest static void assignToMe_test() {

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account a = EAPTestUtility.createAccount(true);

		Test.startTest();

		Boolean result = ProEnrollmentManagerController.assignToMe(a.Id, false);

		Test.stopTest();

		System.assert(result);

		a = [Select EnrollmentAssignedTo__c From Account Where Id = :a.Id];

		System.assertEquals(UserInfo.getUserId(), a.EnrollmentAssignedTo__c);

	}
    
	@isTest static void assignToAgent_test() {
        
		User testUser = [SELECT Id, Name, UserRoleId, UserRole.DeveloperName FROM User WHERE UserRole.DeveloperName = 'ProServicesManaging_User' and IsActive = true LIMIT 1];
        
		RequestCategory__c catg = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(catg.Id, true);

		Account a = EAPTestUtility.createAccount(true);   	
    
    	Id agId = testUser.Id;

		Test.startTest();

		Boolean result = ProEnrollmentManagerController.assignToAgent(a.Id, agId);

		Test.stopTest();

		System.assert(result);

		a = [Select EnrollmentAssignedTo__c From Account Where Id = :a.Id];

		System.assertEquals(agId, a.EnrollmentAssignedTo__c);

	}
    
    @isTest static void searchUsers_test() {
		
		UserRole role = [Select Id From UserRole Where DeveloperName = 'SAM_Frontline_User'];
		User testUser = [SELECT Id,Name, UserRoleId FROM User WHERE Profile.Name = 'System Administrator' And Id != :UserInfo.getUserId() AND IsActive=true LIMIT 1];
		testUser.UserRoleId = role.Id;
		update testUser;

		Test.startTest();

		List<User> result = ProEnrollmentManagerController.searchUsers(testUser.Name);

		Test.stopTest();

		System.assert(!result.isEmpty());

	}
    
	@isTest static void enrollAPro_test() {

		RequestCategory__c cat = EAPTestUtility.createRequestCategory(true);

		Market__c market = EAPTestUtility.createMarket(cat.Id, true);

		Account a = EAPTestUtility.createAccount(false);
		a.EnrollmentAssignedTo__c = UserInfo.getUserId();
		Account a2 = EAPTestUtility.createAccount(false);
		a2.usr_user_id__c = 2;
		insert new List<Account> {a, a2};

		Enrollment__c enrollment = EAPTestUtility.createEnrollment(a2.Id, true);

		EnrollAProController.testCallbackEnrollments = new List<Enrollment__c> ();
		EnrollAProController.testEnrollments = new List<Enrollment__c> {enrollment};

		Test.startTest();

		Id result = ProEnrollmentManagerController.enrollAPro(a.Id);

		Test.stopTest();

		a = [Select EnrollmentAssignedTo__c From Account Where Id = :a.Id];
		System.assertEquals(null, a.EnrollmentAssignedTo__c);
		System.assertEquals(enrollment.Id, result);

	}

	@isTest static void getUserInfo_test() {

		Test.startTest();

		User result = ProEnrollmentManagerController.getUserInfo();

		Test.stopTest();

		System.assertEquals(UserInfo.getUserId(), result.Id);

	}
	
}