metadata-classic/objects/Market__c.object
<CustomObject>
</CustomObject>

metadata-classic/objects/RequestCategory__c.object
<CustomObject>
    <description>All available category.</description>
    <fields>
        <fullName>EnrollAProEnabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Enroll A Pro Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OutreachTypeChanged__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Outreach Type Changed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>outreach_type__c</fullName>
        <label>Outreach Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>OutreachType</valueSetName>
        </valueSet>
    </fields>
    <label>Request Category</label>
    <nameField>
        <label>Request Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Request Categories</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/RequestCategoryTriggerHandler.cls
public class RequestCategoryTriggerHandler {

	public static void handleUpdate(List<RequestCategory__c> newRecords, Map<Id, RequestCategory__c> oldMap) {

		Boolean shouldExecuteOutreachTypeBatchJob = false;
		List<RequestCategory__c> catsEnabled = new List<RequestCategory__c> ();
		for (RequestCategory__c cat : newRecords) {

			RequestCategory__c oldCat = oldMap.get(cat.Id);
			if (cat.outreach_type__c != oldCat.outreach_type__c && String.isNotBlank(cat.outreach_type__c)) {

				cat.OutreachTypeChanged__c = true;
				shouldExecuteOutreachTypeBatchJob = true;

			}
			if (cat.outreach_type__c != oldCat.outreach_type__c && cat.outreach_type__c == 'product_enabled') {

				catsEnabled.add(cat);

			}

		}
		if (shouldExecuteOutreachTypeBatchJob) {

			Database.executeBatch(new RequestCategoryOutreachTypeBatch());

		}
		if (!catsEnabled.isEmpty()) {

			disableMarkets(catsEnabled);

		}

	}

	private static void disableMarkets(List<RequestCategory__c> newRecords) {

		if (!newRecords.isEmpty()) {

			Map<Id, RequestCategory__c> catMap = new Map<Id, RequestCategory__c> (newRecords);
			List<Market__c> markets = [SELECT Id, EnrollAProEnabled__c FROM Market__c Where RequestCategory__c IN :catMap.keySet()];
            for (Market__c market : markets) {

				market.EnrollAProEnabled__c = false;

			}
			update markets;

		}

	}

}