metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <description>Field for who approved the comp</description>
        <label>Approved By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ashley Powell</fullName>
                </value>
                <value>
                    <fullName>Jody Kershaw</fullName>
                </value>
                <value>
                    <fullName>Jonathan Bushnell</fullName>
                </value>
                <value>
                    <fullName>Lindsay Harrop</fullName>
                </value>
                <value>
                    <fullName>Robyn Jeserick</fullName>
                </value>
                <value>
                    <fullName>Simon Fullerton</fullName>
                </value>
                <value>
                    <fullName>Tyler Bailey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The dollar amount of the action (i.e., amount charged to card, amount to collect, amount to payout).</description>
        <inlineHelpText>The dollar amount of the action (i.e., amount charged to card, amount to collect, amount to payout).</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ApprovedBy__c</fullName>
        <description>Picklist to indicate which manager approved the payout.</description>
        <label>Approved By</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ashley Powell</fullName>
                </value>
                <value>
                    <fullName>Jody Kershaw</fullName>
                </value>
                <value>
                    <fullName>Jonathan Bushnell</fullName>
                </value>
                <value>
                    <fullName>Lindsay Harrop</fullName>
                </value>
                <value>
                    <fullName>Robyn Jeserick</fullName>
                </value>
                <value>
                    <fullName>Simon Fullerton</fullName>
                </value>
                <value>
                    <fullName>Tyler Bailey</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The overall status of the incident action.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Soft decline</fullName>
                </value>
                <value>
                    <fullName>Hard decline</fullName>
                </value>
                <value>
                    <fullName>No charge possible</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pre-adjuster resolution process</fullName>
                </value>
                <value>
                    <fullName>Claim sent to adjuster</fullName>
                </value>
                <value>
                    <fullName>Claim in process</fullName>
                </value>
                <value>
                    <fullName>Paid (under Property Damage Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Money Back Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Satisfaction)</fullName>
                </value>
                <value>
                    <fullName>Not paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Payment sent</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent for approval</fullName>
                </value>
                <value>
                    <fullName>No card on file</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Picklist whose values indicate the type of incident action.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit card charge payout</fullName>
                </value>
                <value>
                    <fullName>Arbitration only</fullName>
                </value>
                <value>
                    <fullName>Arbitration with chat</fullName>
                </value>
                <value>
                    <fullName>Chat only</fullName>
                </value>
                <value>
                    <fullName>Money Back Guarantee (above $500)</fullName>
                </value>
                <value>
                    <fullName>Property damage (above $500)</fullName>
                </value>
                <value>
                    <fullName>Satisfaction payout (above $1000)</fullName>
                </value>
                <value>
                    <fullName>Collections on customer&apos;s behalf (above $1000)</fullName>
                </value>
                <value>
                    <fullName>Customer satisfaction</fullName>
                </value>
                <value>
                    <fullName>Customer satisfaction - low dollar</fullName>
                </value>
                <value>
                    <fullName>Property damage guarantee</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Successful card charge</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
                <value>
                    <fullName>High dollar</fullName>
                </value>
                <value>
                    <fullName>MI concern</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Money back guarantee</fullName>
                    <isActive>false</isActive>
                    <label>Money back guarantee</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <recordTypes>
        <fullName>Guarantee</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with the TT property damage or money back guarantees.</description>
        <label>Guarantee</label>
    </recordTypes>
    <recordTypes>
        <fullName>Payout</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with the MI Incident compensation payouts.</description>
        <label>Payout</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentPayoutRequestManagerController.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-08-16   Mendel Guillaume       Created
1.1      2017-12-20   Kristin Hasna          Added new value to Type__c options
========+============+=================+===============================================*/

public with sharing class IncidentPayoutRequestManagerController
{
    @AuraEnabled
    public static String save(MIIncidentAction__c request)
    {
        String response = 'Success';

        try
        {
            request.RecordTypeId = MiIncidentActionTriggerHandler.PayoutRTId;
            upsert request;

        }
        catch(Exception ex)
        {
            response = ex.getMessage() + ' - ' + ex.getStackTraceString();
        }

        return response;
    }

    @AuraEnabled
    public static List<IncidentChargeCardManagerController.Option> getStatuses()
    {
        List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
        //TODO: use custom metadata type for list?

        options.add(new IncidentChargeCardManagerController.Option('Open', 'Open'));
        options.add(new IncidentChargeCardManagerController.Option('Approved', 'Approved'));
        options.add(new IncidentChargeCardManagerController.Option('Payment sent', 'Payment sent'));
        options.add(new IncidentChargeCardManagerController.Option('Pending', 'Pending'));
        options.add(new IncidentChargeCardManagerController.Option('Rejected', 'Rejected'));
        options.add(new IncidentChargeCardManagerController.Option('Sent for approval', 'Sent for approval'));

        return options;
    }

    @AuraEnabled
    public static List<IncidentChargeCardManagerController.Option> getTypes()
    {
        List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
        //TODO: use custom metadata type for list?

        options.add(new IncidentChargeCardManagerController.Option('Credit card charge payout', 'Credit card charge payout'));
        options.add(new IncidentChargeCardManagerController.Option('Customer satisfaction', 'Customer satisfaction'));
        options.add(new IncidentChargeCardManagerController.Option('Customer satisfaction - low dollar', 'Customer satisfaction - low dollar'));
        //options.add(new IncidentChargeCardManagerController.Option('Money back guarantee', 'Money back guarantee'));
        options.add(new IncidentChargeCardManagerController.Option('Property damage guarantee', 'Property damage guarantee'));
        options.add(new IncidentChargeCardManagerController.Option('Settlement', 'Settlement'));
        //options.add(new IncidentChargeCardManagerController.Option('Successful card charge', 'Successful card charge'));

        return options;
    }

    @AuraEnabled
    public static List<IncidentChargeCardManagerController.Option> getApprovedByOptions()
    {
        List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
        List<Schema.PicklistEntry> ples = MIIncident__c.ApprovedBy__c.getDescribe().getPicklistValues();

        for(Schema.PicklistEntry p : ples)
        {
            options.add(new IncidentChargeCardManagerController.Option(p.getLabel(), p.getValue()));
        }

        return options;
    }

    @AuraEnabled
    public static List<MIIncidentAction__c> getPayoutRequests(String incidentId)
    {
        return [SELECT Id, Name, Status__c, LastModifiedBy.Name, LastModifiedDate, Amount__c, Type__c FROM MIIncidentAction__c
                WHERE RecordTypeId =: MiIncidentActionTriggerHandler.PayoutRTId AND MIIncident__c =: incidentId
                ORDER BY LastModifiedDate DESC];
    }
}