metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The dollar amount of the action (i.e., amount charged to card, amount to collect, amount to payout).</description>
        <inlineHelpText>The dollar amount of the action (i.e., amount charged to card, amount to collect, amount to payout).</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/classes/IncidentPayoutRequestManagerCtrlTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-09-04   Mendel Guillaume       Created
========+============+=================+===============================================*/

@IsTest
private class IncidentPayoutRequestManagerCtrlTest
{
	@TestSetup
	static void createData()
	{
		Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
		insert customer;

		Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
		insert pro;

		MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id);
		insert incident;

		MIIncidentAction__c action = new MIIncidentAction__c(MIIncident__c = incident.Id, Amount__c = 0, RecordTypeId = MiIncidentActionTriggerHandler.PayoutRTId);
		insert action;
	}

	static testMethod void testSave()
	{
		MIIncidentAction__c action = [SELECT Id, Amount__c FROM MIIncidentAction__c];

		System.assertEquals(0, action.Amount__c);

		action.Amount__c = 100;
		System.assertEquals('Success', IncidentPayoutRequestManagerController.save(action));

		action = [SELECT Id, Amount__c FROM MIIncidentAction__c];

		System.assertEquals(100, action.Amount__c);
	}

	static testMethod void testGetStatuses()
	{
		System.assertNotEquals(0, IncidentPayoutRequestManagerController.getStatuses().size());
	}

	static testMethod void testGetApprovedBy()
	{
		System.assertNotEquals(0, IncidentPayoutRequestManagerController.getApprovedByOptions().size());
	}

	static testMethod void testGetTypes()
	{
		System.assertNotEquals(0, IncidentPayoutRequestManagerController.getTypes().size());
	}

	static testMethod void testGetPayoutRequests()
	{
		MIIncident__c incident = [SELECT Id FROM MIIncident__c];

		System.assertEquals(1, IncidentPayoutRequestManagerController.getPayoutRequests(incident.Id).size());
	}
}