metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CustomerPhone__c</fullName>
        <description>The phone number of the related customer; populated on incident creation via external data source, however editable by MI agent during incident resolution; if edited on incident it does not update the customer&apos;s account phone number in admin.</description>
        <label>Customer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProPhone__c</fullName>
        <description>The phone number of the related pro; populated on incident creation via external data source, however editable by MI agent during incident resolution; if edited on incident it does not update the pro&apos;s account phone number in admin.</description>
        <label>Pro Phone</label>
        <type>Phone</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentManagerControllerExtensionTest.cls
/**
 * Created by SentientGrey on 10/31/17.
 */

@IsTest
private class IncidentManagerControllerExtensionTest
{
	@TestSetup
	static void createData()
	{
		User testUser = [SELECT id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];
		System.runAs(testUser)
		{
			Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
			insert customer;

			Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
			insert pro;

			MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id);
			insert incident;
		}
	}

	static testMethod void testRefresh()
	{
		User testUser = [SELECT id FROM User WHERE Profile.Name = 'System Administrator' AND IsActive = true LIMIT 1];
		System.runAs(testUser)
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];
			IncidentManagerControllerExtension ctrl = new IncidentManagerControllerExtension(new ApexPages.StandardController(incident));

			System.assertEquals(null, ctrl.incident.ProPhone__c);
			System.assertEquals(null, ctrl.incident.CustomerPhone__c);

			incident.ProPhone__c = '555-555-5555';
			incident.CustomerPhone__c = '555-555-5556';
			update incident;

			ctrl.refresh();
			System.assertEquals(incident.ProPhone__c, ctrl.incident.ProPhone__c);
			System.assertEquals(incident.CustomerPhone__c, ctrl.incident.CustomerPhone__c);
		}
	}
}