metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>If this is a PDG Incident, add any relevant notes here.</inlineHelpText>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>DueDate__c</fullName>
        <description>The date the action is due.</description>
        <label>Due Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Open text area to store notes about the action.</description>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The overall status of the incident action.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Soft decline</fullName>
                </value>
                <value>
                    <fullName>Hard decline</fullName>
                </value>
                <value>
                    <fullName>No charge possible</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pre-adjuster resolution process</fullName>
                </value>
                <value>
                    <fullName>Claim sent to adjuster</fullName>
                </value>
                <value>
                    <fullName>Claim in process</fullName>
                </value>
                <value>
                    <fullName>Paid (under Property Damage Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Money Back Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Satisfaction)</fullName>
                </value>
                <value>
                    <fullName>Not paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Payment sent</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent for approval</fullName>
                </value>
                <value>
                    <fullName>No card on file</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Picklist whose values indicate the type of incident action.</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Credit card charge payout</fullName>
                </value>
                <value>
                    <fullName>Arbitration only</fullName>
                </value>
                <value>
                    <fullName>Arbitration with chat</fullName>
                </value>
                <value>
                    <fullName>Chat only</fullName>
                </value>
                <value>
                    <fullName>Money Back Guarantee (above $500)</fullName>
                </value>
                <value>
                    <fullName>Property damage (above $500)</fullName>
                </value>
                <value>
                    <fullName>Satisfaction payout (above $1000)</fullName>
                </value>
                <value>
                    <fullName>Collections on customer&apos;s behalf (above $1000)</fullName>
                </value>
                <value>
                    <fullName>Customer satisfaction</fullName>
                </value>
                <value>
                    <fullName>Customer satisfaction - low dollar</fullName>
                </value>
                <value>
                    <fullName>Property damage guarantee</fullName>
                </value>
                <value>
                    <fullName>Settlement</fullName>
                </value>
                <value>
                    <fullName>Successful card charge</fullName>
                </value>
                <value>
                    <fullName>Follow-up</fullName>
                </value>
                <value>
                    <fullName>Note</fullName>
                </value>
                <value>
                    <fullName>High dollar</fullName>
                </value>
                <value>
                    <fullName>MI concern</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Money back guarantee</fullName>
                    <isActive>false</isActive>
                    <label>Money back guarantee</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <recordTypes>
        <fullName>Task</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with follow-up tasks.</description>
        <label>Task</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-classic/classes/IncidentActionController.cls
public class IncidentActionController {

	@AuraEnabled
	public static List<MIIncidentAction__c> getActions(Id incidentId, String status) {

		List<MIIncidentAction__c> result = new List<MIIncidentAction__c> ();
		if (incidentId != null) {

			String statusFilter = '';
			if (String.isNotBlank(status)) {

				statusFilter = 'And Status__c = :status ';

			}
			result = (List<MIIncidentAction__c>) Database.query(
					'Select ' + String.join(MIUtility.miIncidentActionFields, ', ') + ' From MIIncidentAction__c '
							+ 'Where MIIncident__c = :incidentId '
							+ statusFilter
							+ 'And RecordType.DeveloperName = \'Task\' '
							+ 'And Type__c = \'Follow-up\' '
							+ 'order by DueDate__c '
			);

		}
		return result;

	}

	@AuraEnabled
	public static List<NoteWrapper> getNotes(Id incidentId)
	{
		List<NoteWrapper> notes = new List<NoteWrapper>();
		List<MIIncidentAction__c> result = new List<MIIncidentAction__c>();

		if (incidentId != null)
		{
			result = (List<MIIncidentAction__c>) Database.query(
					'Select ' + String.join(MIUtility.miIncidentActionFields, ', ') + ' From MIIncidentAction__c '
							+ 'Where MIIncident__c = :incidentId '
							+ 'And Type__c = \'Note\' '
							+ 'And RecordType.DeveloperName = \'Task\' '
							+ 'order by CreatedDate desc '
			);

			if(!result.isEmpty())
			{
				for(MIIncidentAction__c r : result)
				{
					notes.add(new NoteWrapper(r));
				}
			}
		}

		return notes;
	}

	@AuraEnabled
	public static MIIncidentAction__c upsertAction(MIIncidentAction__c incidentAction, String dueDate) {

		System.debug(dueDate);
		if (String.isNotBlank(dueDate)) {

			/*List<String> dateArray = dueDate.split('/');
			incidentAction.DueDate__c = Date.newInstance(
				Integer.valueOf(dateArray[2]),
				Integer.valueOf(dateArray[0]),
				Integer.valueOf(dateArray[1])*
			);*/
			Date due = Date.valueOf(dueDate);

			incidentAction.DueDate__c = DateTime.newInstance(due.year(), due.month(), due.day());

		}
		if (incidentAction.RecordTypeId == null) {

			incidentAction.RecordTypeId = MIIncidentAction__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Task').getRecordTypeId();

		}
		upsert incidentAction;
		return incidentAction;

	}

	@AuraEnabled
	public static void deleteAction(Id actionId) {

		delete new MIIncidentAction__c (Id = actionId);

	}

	public class NoteWrapper
	{
		@AuraEnabled
		public Boolean isLongNote{get{return this.record != null && this.record.Notes__c != null && this.record.Notes__c.length() > 300;}}

		@AuraEnabled
		public String partialNote{get{return this.isLongNote ? (this.record.Notes__c.substring(0, 250) + '...') : null;}}

		@AuraEnabled
		public MIIncidentAction__c record{get;set;}

		public NoteWrapper(MIIncidentAction__c action)
		{
			this.record = action;
		}

	}

}