metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>AdjusterStatus__c</fullName>
        <description>Picklist to indicate the status of the 3rd party insurance adjuster process.</description>
        <label>Adjuster Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Completed report</fullName>
                </value>
                <value>
                    <fullName>Waiting for approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied/Further review needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <recordTypes>
        <fullName>Guarantee</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with the TT property damage or money back guarantees.</description>
        <label>Guarantee</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentGuaranteeControllerTest.cls
/**
   Copyright (c) 2017 Thumbtack. All rights reserved.

   Version      Date          Author            Description
   ========+============+=================+================================================
   1.0      2017-08-18   Mendel Guillaume       Created
   1.1      2018-01-03   Mendel Guillaume  Updated to follow template/guidelines
   ========+============+=================+===============================================
*/

@IsTest
private class IncidentGuaranteeControllerTest
{
	@TestSetup
	static void createData()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Account customer = new Account(Name = 'Customer Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Customer').getRecordTypeId());
			insert customer;

			Account pro = new Account(Name = 'Pro Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Thumbtack Pro').getRecordTypeId());
			insert pro;

			MIIncident__c incident = new MIIncident__c(CustomerAccount__c = customer.Id, ProAccount__c = pro.Id);
			insert incident;
		}
	}

	@IsTest
	static void testSave()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];
			MIIncidentAction__c request = new MIIncidentAction__c(MIIncident__c = incident.Id, Name = 'Request');

			Test.startTest();

			System.assertEquals('Success', IncidentGuaranteeController.save(request, incident), 'Save failed');

			Test.stopTest();

			System.assertEquals(MiIncidentActionTriggerHandler.GuaranteeRTId, request.RecordTypeId, 'Invalid record type');
		}
	}

	@IsTest
	static void testSaveError()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];

			Test.startTest();

			System.assertNotEquals('Success', IncidentGuaranteeController.save(null, incident), 'Save successful');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetStatuses()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assertNotEquals(0, IncidentGuaranteeController.getStatuses().size(), 'No Statuses');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetAdjusterStatuses()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assertNotEquals(0, IncidentGuaranteeController.getAdjusterStatuses().size(), 'No Adjuster Statuses');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetGuaranteeTypes()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assertNotEquals(0, IncidentGuaranteeController.getGuaranteeTypes().size(), 'No Guarantee Types');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetGuaranteeMap()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assertNotEquals(0, IncidentGuaranteeController.getGuaranteeMap().size(), 'No Guarantee Types Map');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetEligibilityFactors()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Test.startTest();

			System.assertNotEquals(0, IncidentGuaranteeController.getEligibilityFactors().size(), 'No Eligibility Factors');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetRequests()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];
			MIIncidentAction__c request = new MIIncidentAction__c(MIIncident__c = incident.Id, Name = 'Request',
					RecordTypeId = MiIncidentActionTriggerHandler.GuaranteeRTId);

			Test.startTest();

			insert request;

			Test.stopTest();

			System.assertEquals(request.Id, IncidentGuaranteeController.getRequest(incident.Id).Id, 'Request not found');
		}
	}

	@IsTest
	static void testGetIncident()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			MIIncident__c incident = [SELECT Id FROM MIIncident__c];

			Test.startTest();

			System.assertEquals(incident.Id, IncidentGuaranteeController.getIncident(incident.Id).Id, 'Incident not found');

			Test.stopTest();
		}
	}

	@IsTest
	static void testGetIncidentActionFieldsAccess()
	{
		System.runAs(TestUtilities.USER_TACK_BOT)
		{
			Map<String, String> fieldsAccess = IncidentGuaranteeController.getIncidentActionFieldsAccess();

			Test.startTest();
			Schema.DescribeFieldResult dfr = MIIncidentAction__c.AdjusterStatus__c.getDescribe();

			if (dfr.isUpdateable())
			{
				System.assertEquals('edit', fieldsAccess.get('AdjusterStatus__c'));
			}
			else if (dfr.isAccessible())
			{
				System.assertEquals('read', fieldsAccess.get('AdjusterStatus__c'));
			}
			else
			{
				System.assertEquals('none', fieldsAccess.get('AdjusterStatus__c'));
			}
			Test.stopTest();
		}
	}
}