metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerPhone__c</fullName>
        <description>The phone number of the related customer; populated on incident creation via external data source, however editable by MI agent during incident resolution; if edited on incident it does not update the customer&apos;s account phone number in admin.</description>
        <label>Customer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>ProPhone__c</fullName>
        <description>The phone number of the related pro; populated on incident creation via external data source, however editable by MI agent during incident resolution; if edited on incident it does not update the pro&apos;s account phone number in admin.</description>
        <label>Pro Phone</label>
        <type>Phone</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/IncidentManagerControllerExtension.cls
/**
 * Created by SentientGrey on 10/31/17.
 */

public with sharing class IncidentManagerControllerExtension
{
	public MIIncident__c incident{get;set;}
	public Id incidentId {get;set;}

	public IncidentManagerControllerExtension(ApexPages.StandardController stdController)
	{
		this.incidentId = stdController.getId();
		loadRecord();
	}

	private void loadRecord()
	{
		if(this.incidentId != null)
		{
			this.incident = [SELECT Id, ProPhone__c, CustomerPhone__c FROM MIIncident__c WHERE Id = :this.incidentId];
		}
	}

	public void refresh()
	{
		loadRecord();
	}
}