metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>The dollar amount of the action (i.e., amount charged to card, amount to collect, amount to payout).</description>
        <inlineHelpText>The dollar amount of the action (i.e., amount charged to card, amount to collect, amount to payout).</inlineHelpText>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The overall status of the incident action.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Soft decline</fullName>
                </value>
                <value>
                    <fullName>Hard decline</fullName>
                </value>
                <value>
                    <fullName>No charge possible</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pre-adjuster resolution process</fullName>
                </value>
                <value>
                    <fullName>Claim sent to adjuster</fullName>
                </value>
                <value>
                    <fullName>Claim in process</fullName>
                </value>
                <value>
                    <fullName>Paid (under Property Damage Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Money Back Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Satisfaction)</fullName>
                </value>
                <value>
                    <fullName>Not paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Payment sent</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent for approval</fullName>
                </value>
                <value>
                    <fullName>No card on file</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentChargeCardManagerController.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-08-15   Mendel Guillaume       Created
========+============+=================+===============================================*/

public with sharing class IncidentChargeCardManagerController
{
	@AuraEnabled
	public static String save(MIIncidentAction__c request)
	{
		String response = 'Success';

		try
		{
			System.debug(request);
			request.RecordTypeId = MiIncidentActionTriggerHandler.ChargeRTId;
			upsert request;

		}
		catch(Exception ex)
		{
			response = ex.getMessage() + ' - ' + ex.getStackTraceString();
		}

		return response;
	}

	@AuraEnabled
	public static List<Option> getStatuses()
	{
		List<Option> options = new List<IncidentChargeCardManagerController.Option>();
		//TODO: use custom metadata type for list of statuses

		options.add(new Option('Open', 'Open'));
		options.add(new Option('Soft decline', 'Soft decline'));
		options.add(new Option('Hard decline', 'Hard decline'));
		options.add(new Option('No charge possible', 'No charge possible'));
		options.add(new Option('Successful', 'Successful'));
		options.add(new Option('Refunded', 'Refunded'));

		return options;
	}

	@AuraEnabled
	public static List<MIIncidentAction__c> getChargeCardRequests(String incidentId)
	{
		return [SELECT Id, Name, Status__c, LastModifiedBy.Name, LastModifiedDate, Amount__c FROM MIIncidentAction__c
				WHERE RecordTypeId =: MiIncidentActionTriggerHandler.ChargeRTId AND MIIncident__c =: incidentId
				ORDER BY LastModifiedDate DESC];
	}

	public class Option
	{
		@AuraEnabled
		public String label{get;set;}

		@AuraEnabled
		public String value{get;set;}

		public Option(String l, String v)
		{
			this.label = l;
			this.value = v;
		}
	}
}