metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>ElapsedHiredTimeDays__c</fullName>
        <formula>IF(NOT ISBLANK(hired_time__c), FLOOR(hired_time__c - request_create_time__c),
NULL)</formula>
        <label>Elapsed Hired Time (Days)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <inlineHelpText>If this is a PDG Incident, add any relevant notes here.</inlineHelpText>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PDGEligibility__c</fullName>
        <description>Formula field to indicate if the incident may be eligible for the Property Damage Guarantee</description>
        <formula>IF(OR(ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Not Marked as Hired&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Damage is to Excluded Property&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Excluded Category&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Not Physical Damage&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Damage was not Accidental/Unintentional&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Damage Not Caused by Thumbtack Pro&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Not Damage from Original Project Requested&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Theft&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Other - Not Eligible (Leave Notes)&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Other (Leave Notes)&quot;)),
&quot;Not Eligible&quot;,
IF(OR(
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Meets all Criteria&quot;),
ISPICKVAL(AdditionalEligibilityFactors__c, &quot;Other - Eligible (Leave Notes)&quot;)),
&quot;Eligible&quot;, 
IF( AND( quotes_hired__c = True, 
ElapsedReportedTimeHours__c &lt;= 72, 
DATETIMEVALUE(requests_create_time__c) &gt;= DATETIMEVALUE( &apos;2016-07-11 12:00:00&apos; )), 
&quot;May Be Eligible&quot;,
&quot; Not Eligible &quot; 
)))</formula>
        <inlineHelpText>The incident may be eligible for the Property Damage Guarantee if a) there is property damage, b) the project request was made on or after 7/11/16,  c) pro was marked as hired, and d) the property damage was reported within 72 hours of damage occurrence.</inlineHelpText>
        <label>PDG Eligibility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecognizedDamageDate__c</fullName>
        <description>The date the damage/incident was recognized.</description>
        <inlineHelpText>The date the damage or other incident was recognized.</inlineHelpText>
        <label>Date Damage Recognized</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ReportedDate__c</fullName>
        <label>Reported Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>hired_time__c</fullName>
        <description>Populated via external object reference; used in formula fields to calculate time duration.</description>
        <label>hired_time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>request_create_time__c</fullName>
        <label>request_create_time</label>
        <type>DateTime</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/MIIncidentAction__c.object
<CustomObject>
    <description>Custom object used to store records pertaining to actions taken for the resolution of an MI dispute / incident between pro and customer.</description>
    <fields>
        <fullName>AdjusterStatus__c</fullName>
        <description>Picklist to indicate the status of the 3rd party insurance adjuster process.</description>
        <label>Adjuster Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Completed report</fullName>
                </value>
                <value>
                    <fullName>Waiting for approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied/Further review needed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EligibilityFactors__c</fullName>
        <description>Picklist whose values describe why a property damage or money back guarantee were not eligible.</description>
        <label>Eligibility Factors</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>GuaranteeType__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Meets all criteria</fullName>
                </value>
                <value>
                    <fullName>60 day documentation overdue</fullName>
                </value>
                <value>
                    <fullName>Contract terms met, customer still dissatisfied</fullName>
                </value>
                <value>
                    <fullName>Damage is to excluded property</fullName>
                </value>
                <value>
                    <fullName>Damage not caused by Thumbtack Pro</fullName>
                </value>
                <value>
                    <fullName>Damage was not accidental/unintentional</fullName>
                </value>
                <value>
                    <fullName>Insufficient documentation</fullName>
                </value>
                <value>
                    <fullName>Job not requested on TT</fullName>
                </value>
                <value>
                    <fullName>No damage from original project request</fullName>
                </value>
                <value>
                    <fullName>No proof of hire</fullName>
                </value>
                <value>
                    <fullName>Not covered in TOU</fullName>
                </value>
                <value>
                    <fullName>Not physical damage</fullName>
                </value>
                <value>
                    <fullName>Not reported within timeline (14 days)</fullName>
                </value>
                <value>
                    <fullName>Other (leave notes)</fullName>
                </value>
                <value>
                    <fullName>Other - Eligible (leave notes)</fullName>
                </value>
                <value>
                    <fullName>Other - Not eligible (leave notes)</fullName>
                </value>
                <value>
                    <fullName>Outside 6 month reporting time</fullName>
                </value>
                <value>
                    <fullName>Proof of hire not established within 30 days of request</fullName>
                </value>
                <value>
                    <fullName>Request made before Guarantee effective date</fullName>
                </value>
                <value>
                    <fullName>Request was made prior to MBG program start date</fullName>
                </value>
                <value>
                    <fullName>Theft</fullName>
                </value>
                <value>
                    <fullName>Unresponsive Customer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GuaranteeType__c</fullName>
        <label>Guarantee Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Property damage guarantee</fullName>
                </value>
                <value>
                    <fullName>Money back guarantee</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>MIIncident__c</fullName>
        <description>Lookup to the parent MI Incident record.</description>
        <label>MI Incident</label>
        <referenceTo>MIIncident__c</referenceTo>
        <relationshipName>MIIncidentActions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Notes__c</fullName>
        <description>Open text area to store notes about the action.</description>
        <label>Notes</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PDGEligibility__c</fullName>
        <description>Formula field to calculate the eligibility of the property damage guarantee.</description>
        <formula>IF(OR(
ISPICKVAL(EligibilityFactors__c, &quot;Contract terms met, customer still dissatisfied&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;Damage is to excluded property&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Damage not caused by Thumbtack Pro&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Damage was not accidental/unintentional&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Excluded category&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Insufficient documentation&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;Job not requested on TT&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;No proof of hire&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;Not damage from original project requested&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Not covered in TOU&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;Not marked as hired&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Not physical damage&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Not reported within timeline (14 days)&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;Not reported within timeframe&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Other - Not eligible (leave notes)&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Other (leave notes)&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Outside 6 month reporting time&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;Proof of hire not established within 30 days of request&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;Request made before Guarantee effective date&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;Theft&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Unresponsive Customer&quot;),
ISPICKVAL(EligibilityFactors__c, &quot;60 day documentation overdue&quot;)
 ),&quot;Not Eligible&quot;, 

IF(OR( 
ISPICKVAL(EligibilityFactors__c, &quot;Meets all criteria&quot;), 
ISPICKVAL(EligibilityFactors__c, &quot;Other - Eligible (leave notes)&quot;) 
),&quot;Eligible&quot;, 

IF(AND(
MIIncident__r.quotes_hired__c = True, 
MIIncident__r.ElapsedReportedTimeDays__c &lt;= 72, 
DATETIMEVALUE(MIIncident__r.request_create_time__c) &gt;= DATETIMEVALUE( &apos;2016-07-11 12:00:00&apos; ) 
),&quot;May Be Eligible&quot;, 

&quot; Not Eligible &quot; 
)))</formula>
        <label>Eligibility</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The overall status of the incident action.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Open</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
                <value>
                    <fullName>In progress</fullName>
                </value>
                <value>
                    <fullName>Soft decline</fullName>
                </value>
                <value>
                    <fullName>Hard decline</fullName>
                </value>
                <value>
                    <fullName>No charge possible</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
                <value>
                    <fullName>Refunded</fullName>
                </value>
                <value>
                    <fullName>Pre-adjuster resolution process</fullName>
                </value>
                <value>
                    <fullName>Claim sent to adjuster</fullName>
                </value>
                <value>
                    <fullName>Claim in process</fullName>
                </value>
                <value>
                    <fullName>Paid (under Property Damage Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Money Back Guarantee)</fullName>
                </value>
                <value>
                    <fullName>Paid (under Satisfaction)</fullName>
                </value>
                <value>
                    <fullName>Not paid</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Payment sent</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Rejected</fullName>
                </value>
                <value>
                    <fullName>Sent for approval</fullName>
                </value>
                <value>
                    <fullName>No card on file</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident Action</label>
    <nameField>
        <label>Record Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incident Actions</pluralLabel>
    <recordTypes>
        <fullName>Guarantee</fullName>
        <active>true</active>
        <description>Record type used to manage the actions associated with the TT property damage or money back guarantees.</description>
        <label>Guarantee</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/IncidentGuaranteeController.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-08-17   Mendel Guillaume       Created
1.1      2017-11-16   Kristin Hasna          Added 60 day documentation overdue option 
                                             to Eligiblity Factors
========+============+=================+===============================================*/

public with sharing class IncidentGuaranteeController
{
	@AuraEnabled
	public static List<IncidentChargeCardManagerController.Option> getStatuses()
	{
		List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
		//TODO: use custom metadata type for list?

		options.add(new IncidentChargeCardManagerController.Option('Open', 'Open'));
		//options.add(new IncidentChargeCardManagerController.Option('Completed', 'Completed'));
		options.add(new IncidentChargeCardManagerController.Option('Pre-adjuster resolution process', 'Pre-adjuster resolution process'));
		options.add(new IncidentChargeCardManagerController.Option('Claim sent to adjuster', 'Claim sent to adjuster'));
		options.add(new IncidentChargeCardManagerController.Option('Claim in process', 'Claim in process'));
		options.add(new IncidentChargeCardManagerController.Option('Paid (under Property Damage Guarantee)', 'Paid (under Property Damage Guarantee)'));
		options.add(new IncidentChargeCardManagerController.Option('Paid (under Money Back Guarantee)', 'Paid (under Money Back Guarantee)'));
		options.add(new IncidentChargeCardManagerController.Option('Paid (under Satisfaction)', 'Paid (under Satisfaction)'));
		options.add(new IncidentChargeCardManagerController.Option('Not paid', 'Not paid'));

		return options;
	}

	@AuraEnabled
	public static List<IncidentChargeCardManagerController.Option> getAdjusterStatuses()
	{
		List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
		List<Schema.PicklistEntry> ples = MIIncidentAction__c.AdjusterStatus__c.getDescribe().getPicklistValues();

		for(Schema.PicklistEntry p : ples)
		{
			options.add(new IncidentChargeCardManagerController.Option(p.getLabel(), p.getValue()));
		}

		return options;
	}

	@AuraEnabled
	public static List<IncidentChargeCardManagerController.Option> getEligibilityFactors()
	{
		List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
		List<Schema.PicklistEntry> ples = MIIncidentAction__c.EligibilityFactors__c.getDescribe().getPicklistValues();

		for(Schema.PicklistEntry p : ples)
		{
			options.add(new IncidentChargeCardManagerController.Option(p.getLabel(), p.getValue()));
		}

		return options;
	}

	@AuraEnabled
	public static List<IncidentChargeCardManagerController.Option> getGuaranteeTypes()
	{
		List<IncidentChargeCardManagerController.Option> options = new List<IncidentChargeCardManagerController.Option>();
		List<Schema.PicklistEntry> ples = MIIncidentAction__c.GuaranteeType__c.getDescribe().getPicklistValues();

		for(Schema.PicklistEntry p : ples)
		{
			options.add(new IncidentChargeCardManagerController.Option(p.getLabel(), p.getValue()));
		}

		return options;
	}

	@AuraEnabled
	public static Map<String, List<IncidentChargeCardManagerController.Option>> getGuaranteeMap()
	{
		Map<String, List<IncidentChargeCardManagerController.Option>> optionsMap = new Map<String, List<IncidentChargeCardManagerController.Option>>();
		Map<String, List<String>> dependencies = UtilityDependentPicklist.GetDependentOptions('MIIncidentAction__c', 'GuaranteeType__c', 'EligibilityFactors__c');

		for(String key : dependencies.keySet())
		{
			if(String.isNotBlank(key))
			{
				List<IncidentChargeCardManagerController.Option> opts = optionsMap.get(key);

				if (opts == null)
				{
					opts = new List<IncidentChargeCardManagerController.Option>();
					optionsMap.put(key, opts);
				}

				for (String d : dependencies.get(key))
				{
					opts.add(new IncidentChargeCardManagerController.Option(d, d));
				}
			}
		}

		return optionsMap;
	}

	@AuraEnabled
	public static String save(MIIncidentAction__c request, MIIncident__c incident)
	{
		String response = 'Success';
		Savepoint sp = null;

		try
		{
			System.debug('Apex save');
			sp = Database.setSavepoint();
			update incident;

			//make sure a new guarantee is not created
			if(request.Id == null)
			{
				MIIncidentAction__c temp = getRequest(request.MIIncident__c);

				if(temp.Id != null)
				{
					request.Id = temp.Id;
				}
				else
				{
					request.RecordTypeId = MiIncidentActionTriggerHandler.GuaranteeRTId;
				}
			}

			upsert request;
		}
		catch(Exception ex)
		{
			if(sp != null)
			{
				Database.rollback(sp);
			}

			response = ex.getMessage() + ' - ' + ex.getStackTraceString();
		}

		return response;
	}

	@AuraEnabled
	public static MIIncidentAction__c getRequest(String incidentId)
	{
		MIIncidentAction__c request = new MIIncidentAction__c(RecordTypeId = MiIncidentActionTriggerHandler.GuaranteeRTId);
		List<MIIncidentAction__c> reqs = [SELECT Id, Name, Status__c, EligibilityFactors__c, PDGEligibility__c,
												AdjusterStatus__c, Notes__c, GuaranteeType__c
											FROM MIIncidentAction__c
											WHERE RecordTypeId =: MiIncidentActionTriggerHandler.GuaranteeRTId AND MIIncident__c =: incidentId
											ORDER BY LastModifiedDate DESC];

		if(!reqs.isEmpty())
		{
			request = reqs[0];
		}

		return request;
	}

	@AuraEnabled
	public static MIIncident__c getIncident(String incidentId)
	{
		return [SELECT Id, Name, request_create_time__c, hired_time__c, ElapsedHiredTimeDays__c, RecognizedDamageDate__c, 
					ReportedDate__c, ElapsedReportedTimeDays__c
				FROM MIIncident__c
				WHERE Id =: incidentId];

	}

	@AuraEnabled
	public static Map<String, String> getIncidentActionFieldsAccess()
	{
		List<String> queryFields = new List<String>{'Name', 'Status__c', 'EligibilityFactors__c', 'PDGEligibility__c', 'AdjusterStatus__c', 'Notes__c'};
		Map<String,Schema.SObjectField> fields = Schema.SObjectType.MIIncidentAction__c.fields.getMap();
		Map<String, String> fieldsAccess = new Map<String, String>();

		for(String qf : queryFields)
		{
			String access = 'none';
			Schema.DescribeFieldResult dfr = fields.get(qf).getDescribe();

			if(dfr.isAccessible())
			{
				access = 'read';

				if(dfr.isUpdateable())
				{
					access = 'edit';
				}
			}

			fieldsAccess.put(qf, access);
		}

		return fieldsAccess;
	}
}