metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>pro_user_id__c</fullName>
        <description>The id of the pro related to the bid_id of the incident.</description>
        <label>pro_user_id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/QuickCaseSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Quick Case Setting</label>
    <pluralLabel>Quick Case Settings</pluralLabel>
</CustomObject>

metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Outcome__c</fullName>
        <label>Outcome</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Quote credits refunded</fullName>
                </value>
                <value>
                    <fullName>Disable and added to Caveo</fullName>
                </value>
                <value>
                    <fullName>Approve</fullName>
                </value>
                <value>
                    <fullName>Reject</fullName>
                </value>
                <value>
                    <fullName>No Warning Sent: Previous Concerning Review Warning</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
                <value>
                    <fullName>Warn and Flag</fullName>
                </value>
                <value>
                    <fullName>Immediate MI Action Needed</fullName>
                </value>
                <value>
                    <fullName>Warned and Flagged</fullName>
                </value>
                <value>
                    <fullName>Sent to MI</fullName>
                </value>
                <value>
                    <fullName>No Warning Sent: Due to Open MI Case</fullName>
                </value>
                <value>
                    <fullName>No action taken</fullName>
                </value>
                <value>
                    <fullName>Accurate - Actioned</fullName>
                </value>
                <value>
                    <fullName>Accurate - No action</fullName>
                </value>
                <value>
                    <fullName>Inaccurate</fullName>
                </value>
                <value>
                    <fullName>Duplicate</fullName>
                </value>
                <value>
                    <fullName>Dispute Accepted and Refunded</fullName>
                </value>
                <value>
                    <fullName>Dispute Rejected</fullName>
                </value>
                <value>
                    <fullName>Pro removed</fullName>
                </value>
                <value>
                    <fullName>Warned</fullName>
                </value>
                <value>
                    <fullName>Removed - Payback option</fullName>
                </value>
                <value>
                    <fullName>Removed - Final</fullName>
                </value>
                <value>
                    <fullName>Accurate - Sexual Request</fullName>
                </value>
                <value>
                    <fullName>Accurate - Offensive Language</fullName>
                </value>
                <value>
                    <fullName>Accurate - Spammy Message</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Related to an Open MTS Incident</fullName>
                </value>
                <value>
                    <fullName>Email sent to customer</fullName>
                </value>
                <value>
                    <fullName>Case sent to MTS</fullName>
                </value>
                <value>
                    <fullName>Accurate - Inappropriate Language</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Work Items (Pro Account)</relationshipLabel>
        <relationshipName>Work_Items1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ReviewAudit__c</fullName>
        <label>Review Audit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concerning behavior</fullName>
                </value>
                <value>
                    <fullName>Deposit no-show</fullName>
                </value>
                <value>
                    <fullName>General dissatisfaction</fullName>
                </value>
                <value>
                    <fullName>Inappropriate physical contact</fullName>
                </value>
                <value>
                    <fullName>Insufficient info</fullName>
                </value>
                <value>
                    <fullName>No-show (unpaid)</fullName>
                </value>
                <value>
                    <fullName>Pricing concerns</fullName>
                </value>
                <value>
                    <fullName>Property damage</fullName>
                </value>
                <value>
                    <fullName>Stolen property</fullName>
                </value>
                <value>
                    <fullName>Text &amp; rating don’t match</fullName>
                </value>
                <value>
                    <fullName>Threats of or actual physical harm</fullName>
                </value>
                <value>
                    <fullName>Unprofessional</fullName>
                </value>
                <value>
                    <fullName>Unresolved unsatisfactory work</fullName>
                </value>
                <value>
                    <fullName>Work not complete</fullName>
                </value>
                <value>
                    <fullName>Open MTS Incident</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for work item</description>
        <inlineHelpText>Status for work item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banned Pro Re-entry</fullName>
                </value>
                <value>
                    <fullName>BGC Identity Mismatch</fullName>
                </value>
                <value>
                    <fullName>Chargeback Removal</fullName>
                </value>
                <value>
                    <fullName>Chargeback Warning</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Customer Payment Review</fullName>
                </value>
                <value>
                    <fullName>In Product Fraud Report</fullName>
                </value>
                <value>
                    <fullName>Low Quality to Remove</fullName>
                </value>
                <value>
                    <fullName>Messaging Verification</fullName>
                </value>
                <value>
                    <fullName>PA Request a Call Error</fullName>
                </value>
                <value>
                    <fullName>Review Message</fullName>
                </value>
                <value>
                    <fullName>Review Message for Spam</fullName>
                </value>
                <value>
                    <fullName>Verified Fake Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>customer_email__c</fullName>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>customer_first_name__c</fullName>
        <label>Customer First Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>customer_last_name__c</fullName>
        <label>Customer Last Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>pro_email__c</fullName>
        <label>Pro Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>pro_first_name__c</fullName>
        <label>Pro First Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>pro_last_name__c</fullName>
        <label>Pro Last Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>rev_rating__c</fullName>
        <label>Review Rating</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rev_usr_user_id_reviewed__c</fullName>
        <label>User Id Reviewed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>rev_usr_user_id_reviewer__c</fullName>
        <label>User Id Reviewer</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>External user ID field used for syncing done with Becquerel.</description>
        <externalId>true</externalId>
        <label>User ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/WorkItemRouter__mdt.object
<CustomObject>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>BGC Identity Mismatch</fullName>
                    <default>true</default>
                    <label>BGC Identity Mismatch</label>
                </value>
                <value>
                    <fullName>Banned Pro Re-entry</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Verification</fullName>
                </value>
                <value>
                    <fullName>Customer Payment Review</fullName>
                </value>
                <value>
                    <fullName>Review Message</fullName>
                </value>
                <value>
                    <fullName>Messaging Verification</fullName>
                </value>
                <value>
                    <fullName>Blacklisted Number</fullName>
                </value>
                <value>
                    <fullName>PA Request a call error</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Low quality to remove</fullName>
                </value>
                <value>
                    <fullName>Chargeback warning</fullName>
                </value>
                <value>
                    <fullName>Chargeback removal</fullName>
                </value>
                <value>
                    <fullName>Review Message for Spam</fullName>
                </value>
                <value>
                    <fullName>In Product Fraud Report</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Item Router</label>
    <pluralLabel>Work Item Routers</pluralLabel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/WorkItemTriggerHandlerTest.cls
/*

Change List:                                                               
------------                                                               

Version    Date     Author            Description                          
=======+===========+=================+=================================
1.3     2016-12-19  Scott Purcell     Created
1.4     2017-07-05  Travis Oliver     Added testRouteWorkItem
1.5     2017-10-18  Jared Kennington  Cleaned up and used TestUtilities class
1.6     2017-12-13  Jared Kennington  Added testAutoCaseCreation
=======+===========+=================+=================================
*/
@isTest
private class WorkItemTriggerHandlerTest {
    private static final String testProEmail = 'protester@t.est';
    private static final String testCustomerEmail = 'customertester@t.est';
    private static final Decimal testProUserId = 12345;
    private static final String testProUserIdString = String.valueOf(testProUserId);
    private static final Decimal testCustomerUserId = 123456;
    private static final String actionNeededStr = 'Warn and Flag';
    private static final String immediateMiActionNeededStr = 'Immediate MI Action Needed';
    private static final String actionNeededOutcomeStr = 'Warned and Flagged';
    private static final String noActionOutcomeStr = 'No Action Taken';
    private static final String warningFlagExplanationStr = 'Automated flag: Concerning Review';
    private static final User testUser = TestUtilities.getTestUserByProfile('*Marketplace Integrity');

    @TestSetup
    private static void setupTestData()
    {
        TestUtilities.insertFourCoreThumbtackUsers();
    }

    /*@IsTest
    private static void testReviewTriggerPhases1And2() {

        System.runAs(testUser) {

            WorkItem__c r = new WorkItem__c(customer_last_name__c='cust last',rev_rating__c = 1,customer_first_name__c = 'cusfirst',pro_first_name__c='first',pro_last_name__c = 'last',Name='Test Review', rev_usr_user_id_reviewed__c=testProUserId, rev_usr_user_id_reviewer__c=testCustomerUserId, pro_email__c=testProEmail,customer_email__c=testProEmail);
            insert r;

            System.assert(null!=[SELECT ProAccount__c FROM WorkItem__c WHERE Id=:r.Id LIMIT 1].ProAccount__c, 'Trigger Failed to set WorkItem__c.ProAccount__c to account corresponding to usr_user_id__c = '+String.valueOf(testProUserId));
            Test.startTest();

            //Phase 1 simple outcome text set
            r.ReviewAudit__c = 'No Action Needed';
            update r;
            System.assert(noActionOutcomeStr==[SELECT Outcome__c FROM WorkItem__c WHERE Id=:r.Id LIMIT 1].Outcome__c, 'Trigger failed to set Outcome__c to ' + noActionOutcomeStr);

            //Phase 2, insert asynchronous records
            r.ReviewAudit__c = actionNeededStr;
            r.Outcome__c = null;
            update r;
            System.assert(actionNeededOutcomeStr==[SELECT Outcome__c FROM WorkItem__c WHERE Id=:r.Id LIMIT 1].Outcome__c, 'Trigger failed to set Outcome__c to ' + actionNeededOutcomeStr);

            Test.stopTest();

            Account tAcc = [SELECT Id FROM Account WHERE usr_user_id__c=:testProUserId LIMIT 1];
            System.assert(1==[SELECT count() FROM CustomerSuccessGuidance__c WHERE Account__c = :tAcc.Id],'No CustomerSuccessGuidance__c inserted after ReviewAudit__c update to '+actionNeededStr);

        }
    }
    @IsTest
    private static void testReviewTriggerPhases3And4() {

        System.runAs(testUser) {

            Account tAcc = [SELECT Id FROM Account WHERE usr_user_id__c=:testProUserId LIMIT 1];
            WorkItem__c r = new WorkItem__c(Name='Test Review', rev_usr_user_id_reviewed__c=testProUserId, rev_usr_user_id_reviewer__c=testCustomerUserId, pro_email__c=testProEmail,customer_email__c=testProEmail);
            insert r;
            update r; //create guidance (will be async)
            //insert phase two result, existing guidance record, to ensure one exists for the scenario three case and mi inserts
            insert new CustomerSuccessGuidance__c (
                    Account__c = tAcc.Id,
                    MIFlagType__c = 'Concerning Review',
                    Name = warningFlagExplanationStr,
                    FlagExplanation__c = warningFlagExplanationStr
            );

            Test.startTest();

            //Phase 3, insert asynchronous records with existing Guidance record
            r.ReviewAudit__c = actionNeededStr;
            r.Outcome__c = null;
            update r;

            Test.stopTest();

            system.debug('workitem r:'+r);
            system.assertEquals('Warn and Flag',r.ReviewAudit__c);
            update r; //code covarge for scenario 4
        }
    }

    //test MiAction flow
    @IsTest
    private static void testReviewTriggerScenario5() {

        System.runAs(testUser) {

            WorkItem__c r = new WorkItem__c(Name='Test Review', rev_usr_user_id_reviewed__c=testProUserId, rev_usr_user_id_reviewer__c=testCustomerUserId, pro_email__c=testProEmail,customer_email__c=testProEmail);
            insert r;
            Test.startTest();

            //phase five
            r.ReviewAudit__c = immediateMiActionNeededStr;
            update r;
            //System.assert(immediateMiActionOutcomeStr==[SELECT Outcome__c FROM WorkItem__c WHERE Id=:r.Id LIMIT 1].Outcome__c, 'Trigger failed to set ' + immediateMiActionOutcomeStr);
            Test.stopTest();
            system.assertEquals('Immediate MI Action Needed',r.ReviewAudit__c);
            Account tAcc = [SELECT Id FROM Account WHERE usr_user_id__c=:testProUserId LIMIT 1];

            List<MiIncident__c> miRecs = [SELECT Id from MiIncident__c WHERE pro_user_id__c = :testProUserIdString];
            System.assert(!miRecs.isEmpty(),'No MI Incident inserted after ReviewAudit__c update to '+immediateMiActionNeededStr);
        }
    }*/
    @IsTest
    private static void testRouteWorkItem()
    {
        System.runAs(testUser) {

            WorkItem__c w = new WorkItem__c
                    (
                            type__c = 'Review Message',
                            name = 'Test Name',
                            details__c = 'Test Details',
                            rev_usr_user_id_reviewed__c = 1236548,
                            pro_first_name__c = 'Test',
                            pro_last_name__c = 'Pro'
                    );

            Test.startTest();
            insert w;
            Test.stopTest();
            WorkItem__c wTest = [SELECT Id, Type__c, Status__c, Priority__c, RecordTypeId, OwnerId, Details__c FROM WorkItem__c WHERE Type__c = 'Review Message' LIMIT 1][0];
            Map<String, WorkItemRouter__mdt> wirMap = new Map<String,WorkItemRouter__mdt>();
            for(WorkItemRouter__mdt wir : [SELECT MasterLabel, OwnerId__c, Priority__c, RecordtypeId__c, Status__c From WorkItemRouter__mdt WHERE IsActive__c = true])
            {
                wirMap.put(wir.MasterLabel, wir);
            }
            System.assert(wTest.status__c == wirMap.get(w.type__c).status__c,'Status not equal to Custom Setting Status');
            System.assert(wTest.priority__c == wirMap.get(w.type__c).priority__c,'Priority not equal to Custom Setting Priority');
            System.assert(wTest.recordtypeid == wirMap.get(w.type__c).recordtypeid__c,'RecordTypeId not equal to Custom Setting RecordTypeId');
            System.assert(wTest.ownerid == wirMap.get(w.type__c).ownerid__c,'OwnerId not equal to Custom Setting OwnerId');
        }
    }

    @isTest
    private static void testAutoCaseCreation()
    {
        System.runAs(testUser)
        {
            QuickCaseSetting__mdt[] qcs = [SELECT Id, WorkItemReportOutcome__c, WorkItemType__c, FeedPost__c, Category__c, OwnerId__c FROM QuickCaseSetting__mdt WHERE AssignedApp__c = 'WorkItem' AND IsActive__c = true LIMIT 1];


            WorkItem__c w = new WorkItem__c
                    (
                        Type__c = qcs[0].WorkItemType__c,
                        name='Test WI',
                        details__c = 'Test Case Creation'
                    );

            Test.startTest();
            insert w;
            w.ReportOutcome__c = qcs[0].WorkItemReportOutcome__c;
            update w;
            Test.stopTest();

            Case[] casesCreated = [SELECT Id, WorkItemId__c, OwnerId, Category__c FROM Case WHERE WorkItemId__c = :w.Id];
            CaseFeed[] feedItemsCreated = casesCreated.isEmpty() ? null : [SELECT Id FROM CaseFeed WHERE ParentId = :casesCreated[0].Id];

            //Case creation
            System.assert(casesCreated.size() > 0, 'Did not create a case');
            System.assert((casesCreated.size() > 0 && casesCreated.size() == 1), 'Created more than one case');

            //Feed Item creation
            System.assert((!feedItemsCreated.isEmpty() && feedItemsCreated.size() > 0), 'Did not create a feed item');
            System.assert((!feedItemsCreated.isEmpty() && feedItemsCreated.size() > 0 && feedItemsCreated.size() == 1), 'Created more than one feed item');

            //Values check
            System.assert(casesCreated[0].OwnerId == qcs[0].OwnerId__c, 'Values did not populate correctly on Case' );
        }
    }

}