metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>Origin__c</fullName>
        <description>The contact channel or method in which the incident originated.</description>
        <label>Origin</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>App Integration</fullName>
                </value>
                <value>
                    <fullName>Concerning review</fullName>
                </value>
                <value>
                    <fullName>Directly Question</fullName>
                </value>
                <value>
                    <fullName>Dispute form</fullName>
                </value>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Inbound Phone</fullName>
                </value>
                <value>
                    <fullName>In-Product</fullName>
                </value>
                <value>
                    <fullName>Live Chat</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Outbound Phone</fullName>
                </value>
                <value>
                    <fullName>Social Media</fullName>
                </value>
                <value>
                    <fullName>Solution Center</fullName>
                </value>
                <value>
                    <fullName>Text Message</fullName>
                </value>
                <value>
                    <fullName>Voicemail</fullName>
                </value>
                <value>
                    <fullName>Web</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <description>The priority or urgency of the incident.</description>
        <inlineHelpText>Tier 1: Amount less than 15k, no high-risk factors, no urgent time-restraints, GSRs
Tier 2: Amount more than 15k, time sensitive,high profile
Tier 3: Sensitive or urgent, bodily harm, serious threats, anything that should be address immediately
Tier 4:</inlineHelpText>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tier 1</fullName>
                </value>
                <value>
                    <fullName>Tier 2</fullName>
                </value>
                <value>
                    <fullName>Tier 3</fullName>
                </value>
                <value>
                    <fullName>Tier 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/QuickCaseSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <description>Hardcoded ID or merge field</description>
        <label>Account Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <description>Hardcoded ID or merge field</description>
        <label>Contact Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Merge fields</description>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>FeedPost__c</fullName>
        <label>Feed Post</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ManualCaseCreation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Manual Case Creation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Origin__c</fullName>
        <label>Origin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginalQueue__c</fullName>
        <description>Mapped to Case.OriginalQueue__c, and used to track the original case owner.</description>
        <label>Original Queue</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OwnerId__c</fullName>
        <description>Hardcoded ID or merge field</description>
        <label>OwnerId</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordTypeId__c</fullName>
        <label>Record Type Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelateToIncident__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Relate to Incident</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subcategory__c</fullName>
        <label>Subcategory</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <description>Merge fields</description>
        <label>Subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SuppliedEmail__c</fullName>
        <description>Hardcoded email or merge field</description>
        <label>Web Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Team__c</fullName>
        <label>Team</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Quick Case Setting</label>
    <pluralLabel>Quick Case Settings</pluralLabel>
</CustomObject>

metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for work item</description>
        <inlineHelpText>Status for work item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/UtilityQuickCaseSetting.cls
/*
Copyright (c) [2015 -] 2017 Thumbtack. All rights reserved.

Change List:
------------
Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-09-05   Mendel Guillaume       Created
1.1		 2017-12-07	  Jared Kennington		 Updated functionality so this can be utilized by WorkItem
========+============+=================+===============================================*/

public class UtilityQuickCaseSetting
{
	public Map<String, String> mergeFieldValues{get;set;}
	public QuickCaseSetting__mdt setting {get;set;}

	public UtilityQuickCaseSetting()
	{
		mergeFieldValues = new Map<String, String>();
	}

	public String replaceMergeField(String text)
	{
		if (text != null && text.contains('{!'))
		{
			for (String key : mergeFieldValues.keySet())
			{
				String value = mergeFieldValues.get(key);

				if(value == null)
				{
					value = '';
				}

				text = text.replace(key, value);
			}
		}

		return text;
	}

	public static UtilityQuickCaseSetting getQuickCaseSetting(ID recordId, ID settingId, sObjectType objectType)
	{
		UtilityQuickCaseSetting uqcs = new UtilityQuickCaseSetting();
		List<QuickCaseSetting__mdt> settings = [SELECT Id, MasterLabel, OriginalQueue__c,DeveloperName, AccountId__c, Category__c, ContactId__c,
						Description__c, ManualCaseCreation__c, Origin__c, OwnerId__c, Priority__c, RecordTypeId__c, RelateToIncident__c,
						Status__c, Subcategory__c, Subject__c, Team__c, SuppliedEmail__c, FeedPost__c
						FROM  QuickCaseSetting__mdt WHERE Id =: settingId];

		if(!settings.isEmpty() && null != recordId)
		{
			Map<String, String> mergeFields = new Map<String, String>();
			Pattern regex = Pattern.compile('\\{!([^}]*)\\}');
			Matcher match = null;

			if(settings[0].AccountId__c != null && settings[0].AccountId__c.contains('{!'))
			{
				getMergeFields(regex, settings[0].AccountId__c, mergeFields);
			}

			if(settings[0].ContactId__c != null && settings[0].ContactId__c.contains('{!'))
			{
				getMergeFields(regex, settings[0].ContactId__c, mergeFields);
			}

			if(settings[0].Description__c != null && settings[0].Description__c.contains('{!'))
			{
				getMergeFields(regex, settings[0].Description__c, mergeFields);
			}

			if(settings[0].OwnerId__c != null && settings[0].OwnerId__c.contains('{!'))
			{
				getMergeFields(regex, settings[0].OwnerId__c, mergeFields);
			}

			if(settings[0].Subject__c != null && settings[0].Subject__c.contains('{!'))
			{
				getMergeFields(regex, settings[0].Subject__c, mergeFields);
			}

			if(settings[0].SuppliedEmail__c != null && settings[0].SuppliedEmail__c.contains('{!'))
			{
				getMergeFields(regex, settings[0].SuppliedEmail__c, mergeFields);
			}

			if(settings[0].FeedPost__c != null && settings[0].FeedPost__c.contains('{!'))
			{
				getMergeFields(regex, settings[0].FeedPost__c, mergeFields);
			}

			if(!mergeFields.isEmpty())
			{
				String query = 'SELECT Id';

				for(String field : mergeFields.values())
				{
					query += ', ' + field;
				}

				if(null != objectType && objectType.getDescribe().getName() == 'MIIncident__c')
				{
					query += ' FROM MIIncident__c WHERE Id = :recordId';
				}
				else if(null != objectType && objectType.getDescribe().getName() == 'WorkItem__c')
				{
					query += ' FROM WorkItem__c WHERE Id = :recordId';
				}

                List<sObject> records = new List<sObject>();
				try{  records = (List<sObject>) Database.query(query); } catch (Exception ex) { System.debug(LoggingLevel.Error, ex.getMessage() + ' - ' + ex.getStackTraceString()); }

				if(records.size() > 0)
				{
					uqcs.setting = settings[0];

					for(String key : mergeFields.keySet())
					{
						String fieldName = mergeFields.get(key);
						String value =  null;

						if(fieldName.contains('.'))
						{
							System.debug(fieldName);
							List<String> fields = fieldName.split('\\.');
							System.debug(fields);
							sObject o = records[0].getSObject(fields[0]);

							fields.remove(0);

							for(Integer i = 0; i < fields.size() - 1; i++)
							{
								if(o != null)
								{
									o = o.getSObject(fields[i]);
								}
							}

							if(o != null)
							{
								value = String.valueOf(o.get(fields[fields.size() - 1]));
							}
						}
						else
						{
							value = String.valueOf(records[0].get(fieldName));
						}

						uqcs.mergeFieldValues.put(key, value);
					}
				}
			}
		}

		return uqcs;
	}

	private static void getMergeFields(Pattern regex, String text, Map<String, String> mergeFields)
	{
		Matcher match = regex.matcher(text);

		while(match.find())
		{
			String token = match.group();
			String fieldName = token.replace('{!MIIncident__c.','').replace('{!WorkItem__c.','').replace('}','');

			mergeFields.put(token, fieldName);
		}
	}
}