metadata-classic/objects/MIIncident__c.object
<CustomObject>
    <description>Custom object to store data about customer/pro incidents handled by our Marketplace Integrity team.  Stores information about what the incident type is, how it was resolved, and if the Thumbtack Guarantee was used.</description>
    <fields>
        <fullName>CustomerAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Account object, used to indicate the customer involved in the MI Incident</description>
        <label>Customer Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Customer)</relationshipLabel>
        <relationshipName>MIIncidentsCustomer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IncidentNumber__c</fullName>
        <description>Number to easily identify the MI Incident.</description>
        <displayFormat>MI-{00000}</displayFormat>
        <label>Incident Number</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>MICategory__c</fullName>
        <description>Marketplace Integrity Incident categories.</description>
        <label>MI Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concern about user</fullName>
                </value>
                <value>
                    <fullName>Deposit no show</fullName>
                </value>
                <value>
                    <fullName>Payment issues</fullName>
                </value>
                <value>
                    <fullName>Physical harm / Inappropriate contact</fullName>
                </value>
                <value>
                    <fullName>Property damage</fullName>
                </value>
                <value>
                    <fullName>Theft</fullName>
                </value>
                <value>
                    <fullName>Unprofessional behavior</fullName>
                </value>
                <value>
                    <fullName>Unsatisfactory work</fullName>
                </value>
                <value>
                    <fullName>Work not complete</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to account - indicates the pro involved in the MI incident.</description>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>MI Incidents (Pro Account)</relationshipLabel>
        <relationshipName>MIIncidentsPro</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Marketplace Integrity Incident status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Closed</fullName>
                </value>
                <value>
                    <fullName>Reopened</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>MI Incident</label>
    <nameField>
        <label>Incident Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>MI Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/IncidentPreviousListController.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2017 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:

Version      Date          Author            Description
========+============+=================+================================================
1.0      2017-08-28   Mendel Guillaume       Created
========+============+=================+===============================================*/

public with sharing class IncidentPreviousListController
{
	@AuraEnabled
	public static List<MIIncident__c> getProIncidents(String accountId, String incidentId)
	{
		return [SELECT Id, Name, IncidentNumber__c, MICategory__c, Status__c, CreatedDate, Owner.Name
		FROM MIIncident__c WHERE ProAccount__c =:accountId AND Id != :incidentId AND ProAccount__c != null ORDER BY CreatedDate DESC];
	}

	@AuraEnabled
	public static List<MIIncident__c> getCustomerIncidents(String accountId, String incidentId)
	{
		return [SELECT Id, Name, IncidentNumber__c, MICategory__c, Status__c, CreatedDate, Owner.Name
		FROM MIIncident__c WHERE CustomerAccount__c =:accountId AND Id != :incidentId AND CustomerAccount__c != null ORDER BY CreatedDate DESC];
	}
}