metadata-classic/objects/ProductFeedback__c.object
<CustomObject>
    <description>Custom object to store feedback records from Thumbtack&apos;s Pros and Customers. Includes product feedback and request form/category feedback.</description>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relationship between case and product feedback custom object</description>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Feedbacks</relationshipLabel>
        <relationshipName>Feedbacks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FeedbackOwnerName__c</fullName>
        <label>Feedback Owner Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProductFeedback__c</fullName>
        <description>Product feedback received from customers/pros</description>
        <inlineHelpText>Enter any feedback received from the customer or pro here.</inlineHelpText>
        <label>Product Feedback</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>A-{000000}</displayFormat>
        <label>Feedback Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/FeedbackTriggerHandler.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:
------------
Version    Date     Author            Description
=======+===========+=================+================================================
1.0     06-01-2017  Scott Purcell      Created
=======+===========+=================+================================================
*/                                                                                       
public with sharing class FeedbackTriggerHandler 
{
	public static Id psfRecordTypeId = ProductFeedback__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Pro Services Feedback').getRecordTypeId();
	public static void isAfterInsert(List<ProductFeedback__c> feedbacks,Map<Id,ProductFeedback__c>feedbackMap) 
	{
		for(ProductFeedback__c feedback:feedbacks)
		{
			if(feedback.RecordTypeId == psfRecordTypeId && feedback.Case__c != null)
			{
				try
				{
					system.debug('feedback.Case__r.Id: '+feedback.Case__c);
					String response = ' PA Feedback submitted by '+feedback.FeedbackOwnerName__c + ', https://thumbtack.my.salesforce.com/console#%2F'+feedback.Id;
					system.debug('Response: '+response);
					ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedback.Case__c, ConnectApi.FeedElementType.FeedItem, response);
				}
				catch(Exception e){system.debug(e);}
			} 
		}
		
	}
	//public static void isBeforeUpdate(List<ProductFeedback__c> feedbacks,List<ProductFeedback__c> oldFeedbacks,Map<Id,ProductFeedback__c>feedbackMap,Map<Id,ProductFeedback__c>oldFeedbackMap) 
	//{
		
	//}
}