metadata-classic/objects/RelatedListSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <label>Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderFieldAPIName__c</fullName>
        <label>Order Field API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentObjectAPIName__c</fullName>
        <label>Parent Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentRefrenceFieldAPIName__c</fullName>
        <label>Parent Refrence Field API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueryFieldSetName__c</fullName>
        <label>Query Field Set Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordsPerPage__c</fullName>
        <label>Records Per Page</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RelationshipFieldAPIName__c</fullName>
        <label>Relationship Field API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortDirection__c</fullName>
        <label>Sort Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASC</fullName>
                    <default>true</default>
                    <label>ASC</label>
                </value>
                <value>
                    <fullName>DESC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TableName__c</fullName>
        <label>Table Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Related List Setting</label>
    <pluralLabel>Related List Settings</pluralLabel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/RelatedListSetting.cls
public class RelatedListSetting {

	@AuraEnabled
	public String tableName {get; set;}
	@AuraEnabled
	public String objectName {get; set;}
	@AuraEnabled
	public String queryFieldSetName {get; set;}
	@AuraEnabled
	public String relationshipFieldName {get; set;}
	@AuraEnabled
	public String orderFieldName {get; set;}
	@AuraEnabled
	public String sortDirection {get; set;}
	@AuraEnabled
	public Integer recordsPerPage {get; set;}
	@AuraEnabled
	public String parentObjectName {get; set;}
	@AuraEnabled
	public String parentReferenceFieldName {get; set;}
	@AuraEnabled
	public String referenceId {get; set;}
	@AuraEnabled
	public List<Map<String, String>> fields {get; set;}

	public RelatedListSetting() {}

	public RelatedListSetting(RelatedListSetting__mdt setting) {
		
		tableName = setting.TableName__c;
		objectName = setting.ObjectAPIName__c;
		orderFieldName = setting.OrderFieldAPIName__c;
		queryFieldSetName = setting.QueryFieldSetName__c;
		recordsPerPage = Integer.valueOf(setting.RecordsPerPage__c);
		relationshipFieldName = setting.RelationshipFieldAPIName__c;
		sortDirection = setting.SortDirection__c;
		parentObjectName = setting.ParentObjectAPIName__c;
		parentReferenceFieldName = setting.ParentRefrenceFieldAPIName__c;

	}

}