metadata-classic/objects/RelatedListSetting__mdt.object
<CustomObject>
    <fields>
        <fullName>ObjectAPIName__c</fullName>
        <label>Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OrderFieldAPIName__c</fullName>
        <label>Order Field API Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentObjectAPIName__c</fullName>
        <label>Parent Object API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentRefrenceFieldAPIName__c</fullName>
        <label>Parent Refrence Field API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QueryFieldSetName__c</fullName>
        <label>Query Field Set Name</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordsPerPage__c</fullName>
        <label>Records Per Page</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RelatedListSectionName__c</fullName>
        <label>Related List Section Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RelationshipFieldAPIName__c</fullName>
        <label>Relationship Field API Name</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SortDirection__c</fullName>
        <label>Sort Direction</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>ASC</fullName>
                    <default>true</default>
                    <label>ASC</label>
                </value>
                <value>
                    <fullName>DESC</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>TableDisplayOrder__c</fullName>
        <label>Table Display Order</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TableName__c</fullName>
        <label>Table Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Related List Setting</label>
    <pluralLabel>Related List Settings</pluralLabel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/RelatedListController.cls
public class RelatedListController {

	@AuraEnabled
	public static List<RelatedListSetting> getRelatedListsForPageName(String sectionName) {

		List<RelatedListSetting> result = new List<RelatedListSetting> ();
		if (String.isNotBlank(sectionName)) {

			for (RelatedListSetting__mdt setting : [Select ObjectAPIName__c, OrderFieldAPIName__c, TableName__c, ParentObjectAPIName__c, ParentRefrenceFieldAPIName__c,
													QueryFieldSetName__c, RecordsPerPage__c, RelationshipFieldAPIName__c, SortDirection__c
													From RelatedListSetting__mdt
													Where RelatedListSectionName__c = :sectionName
													order by TableDisplayOrder__c]) {

				result.add(new RelatedListSetting (setting));

			}

		}
		return result;

	}

	@AuraEnabled
	public static RelatedListSetting getRelatedListInfo(String parentObjectName, String parentReferenceFieldName, Id recordId, String objectName, String fieldSetName) {

		RelatedListSetting result = new RelatedListSetting ();
		result.referenceId = getParentReferenceId(parentObjectName, parentReferenceFieldName, recordId);
		result.fields = getFieldsFromFieldSet(objectName, fieldSetName);
		return result;

	}

	private static String getParentReferenceId(String parentObjectName, String parentReferenceFieldName, Id recordId) {

		String result;
		if (String.isNotBlank(parentObjectName) && String.isNotBlank(parentReferenceFieldName)) {

			SObject record = Database.query(
				'Select ' + parentReferenceFieldName + ' From ' + parentObjectName + ' Where Id = :recordId '
			);
			result = (String) record.get(parentReferenceFieldName);

		}
		return result;

	}
	
	private static List<Map<String, String>> getFieldsFromFieldSet(String objectName, String fieldSetName) {

		List<Map<String, String>> result = new List<Map<String, String>> ();
		if (String.isNotBlank(objectName) && String.isNotBlank(fieldSetName)) {

			Schema.DescribeSObjectResult[] describeResults = Schema.describeSObjects(new String[] {objectName});
            List<Schema.FieldSetMember> members = describeResults[0].fieldSets.getMap().get(fieldSetName).getFields();
            Map<String, Schema.SObjectField> fieldMap = describeResults[0].fields.getMap();
            for (Schema.FieldSetMember member : members) {

            	String fieldName = member.getFieldPath();
            	Schema.DisplayType displayType = fieldMap.get(fieldName).getDescribe().getType();
            	String dataType = 'non-date';
            	if (displayType == Schema.DisplayType.Date) {

            		dataType = 'date';

            	} else if (displayType == Schema.DisplayType.DateTime) {

            		dataType = 'datetime';

            	}
            	result.add(new Map<String, String> {
            		'name' => fieldName,
            		'label' => member.getLabel(),
            		'dataType' => dataType
            	});

            }

		}
		return result;

	}

	@AuraEnabled
	public static List<sObject> getRecords(String objectName, String relationshipFieldName, String referenceId, List<String> queryFields, String orderField, String sortDirection, Integer recordsPerPage, Integer pageNumber) {

		List<sObject> result = new List<sObject> ();
		if (String.isNotBlank(objectName) && String.isNotBlank(relationshipFieldName) && String.isNotBlank(referenceId) && queryFields != null && !queryFields.isEmpty()) {

			String query = 'Select ' + String.join(queryFields, ', ') + ' From ' + objectName + ' ';
			query += 'Where ' + relationshipFieldName + ' = :referenceId ';
			if (String.isNotBlank(orderField)) {

				query += 'order by ' + orderField + ' ';
				if (String.isNotBlank(sortDirection)) {

					query += sortDirection + ' ';

				}

			}
			Integer i_recordsPerPage = Integer.valueOf(recordsPerPage);
			if (i_recordsPerPage != null && i_recordsPerPage > 0) {

				query += 'limit ' + i_recordsPerPage + ' ';
				Integer i_pageNumber = Integer.valueOf(pageNumber);
				Integer offset = i_recordsPerPage * i_pageNumber;
				if (i_pageNumber != null && i_pageNumber > 0) {

					query += 'offset ' + offset + ' ';

				}

			}
			result = Database.query(query);

		}
		return result;

	}

}