metadata-classic/objects/Request__c.object
<CustomObject>
    <description>Custom object to store records pertaining to quoting service requests.  Records store parsed email data from the request email sent to the professional enrolled in quoting service.</description>
    <fields>
        <fullName>BalanceState__c</fullName>
        <description>1 = Payment on pros account is in good standing, 2 = Payment on pros account is not in good standing and/or no longer valid. This field is a formula that pulls the current balance state from the related account. The Request trigger handler uses this field to auto update the status.</description>
        <formula>IF( 
ISPICKVAL(Service__r.ProAccount__r.BillingType__c, &apos;PPC - Manual Invoicing&apos;), 1,
IF( 
ISPICKVAL(Service__r.ProAccount__r.BillingType__c, &apos;Pay Per Appointment&apos;), 1,
IF(
NOT(ISBLANK(Service__c)), Service__r.ProAccount__r.uct_balance_state__c, 
NULL 
)))</formula>
        <inlineHelpText>1 = Payment on pros account is in good standing, 2 = Payment on pros account is not in good standing and/or no longer valid. Accounts where Billing Type = PPC - Manual Invoicing or Pay Per Appointment will NOT auto pass requests.</inlineHelpText>
        <label>Balance State</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>EmailHTMLBodyLong__c</fullName>
        <label>Email HTML Body Long</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EmailSendQuoteLinkPart1__c</fullName>
        <label>Email Send Quote Link Part 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EmailSendQuoteLink__c</fullName>
        <description>The &quot;Send Quote&quot; URL link as stored in the incoming email body.</description>
        <label>Email &quot;Send Quote&quot; Link</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EncodedRequestID__c</fullName>
        <label>Encoded Request ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EncodedServiceID__c</fullName>
        <description>The encoded serviced ID parsed from the html email body.</description>
        <label>Encoded Service ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LastSyncedWithDataPlatform__c</fullName>
        <label>LastSyncedWithDataPlatform</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PurchasedBalance__c</fullName>
        <formula>IF( 
NOT(ISBLANK(Service__c)),  Service__r.ProAccount__r.TotalThumbtackBalance__c, 
NULL 
)</formula>
        <label>Purchased Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuotingServiceStatus__c</fullName>
        <description>Formula field to bring over the quoting service status onto the Request record.  Used in list views and for process builder.</description>
        <formula>TEXT(Service__r.QuotingServiceStatus__c)</formula>
        <label>Quoting Service Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Pro Assistant Profile (aka Service) record.</description>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist whose values indicate the status of the request record.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Forward (Sent to Pro)</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
                <value>
                    <fullName>Pro Already Quoted</fullName>
                </value>
                <value>
                    <fullName>Pricing Calculator Error</fullName>
                </value>
                <value>
                    <fullName>Pro Paused</fullName>
                </value>
                <value>
                    <fullName>Max Contact Reached</fullName>
                </value>
                <value>
                    <fullName>DNQ In Pricing Calculator</fullName>
                </value>
                <value>
                    <fullName>No PC Template For Category</fullName>
                </value>
                <value>
                    <fullName>Expired/Inactive Request</fullName>
                </value>
                <value>
                    <fullName>No Credits - Cant Quote</fullName>
                </value>
                <value>
                    <fullName>No Balance - Cant Quote</fullName>
                </value>
                <value>
                    <fullName>Weekly Budget Limit Hit - Passed</fullName>
                </value>
                <value>
                    <fullName>Other - Passed</fullName>
                </value>
                <value>
                    <fullName>Negative Balance</fullName>
                </value>
                <value>
                    <fullName>No Related Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>UrlParms__c</fullName>
        <description>A debug field holding JSON version of Pro Request URL query string parms</description>
        <label>Url Parms</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Service__c.object
<CustomObject>
    <description>Custom object to store records pertaining to the Pro Assistant, Quoting Service, or Instant Quote Service profiles (e.g., is the Pro active in Quoting service).</description>
    <fields>
        <fullName>EncodedServiceID__c</fullName>
        <description>The encoded serviced ID is found in admin on the service in the &apos;Legacy ID:&apos; field.</description>
        <inlineHelpText>The encoded serviced ID is found in admin on the service in the &apos;Legacy ID:&apos; field.</inlineHelpText>
        <label>Service Legacy ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Pro business/name the service is related to.</description>
        <inlineHelpText>The Pro business/name the service is related to.</inlineHelpText>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QuotingServiceStatus__c</fullName>
        <label>Quoting Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ON</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/RequestTriggerHandler.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
******************************************************************************** 
Change List:
------------
Version    Date     Author            Description
=======+===========+=================+==============================================
1.0     2016-12-06   Scott Purcell      Created
1.1.    04/10/2017   Scott Purcell      Added Bequerel code that will need to be uncommmented
1.2.    07/14/2017   Paul Coleman       refactored getEncodedServiceId logic to use common untility
                                        function ProRequestsEmailService.getServiceDetails()
=======+===========+=================+=============================================*/
public with sharing class RequestTriggerHandler
{

    private static final Id PRO_ASSIST_RECORD_TYPE_ID = Request__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Pro Assistance Request').getRecordTypeId();
    private static final Id DID_NOT_QUOTE_Q_ID = [Select Id, QueueId From QueueSobject Where SobjectType = 'Request__c' And Queue.Name = 'Did Not Quote' LIMIT 1].QueueId;

    public static void OnBeforeInsert(List<Request__c> newRequests)
    {
        Map<String, List<Request__c>> reqsByServiceIdMap = new Map<String, List<Request__c>>();
        for (Request__c request : newRequests)
        {
            if (request.QuotingServiceStatus__c == 'Off')
            {
                request.Status__c = 'Pro Paused';
            }
            if (request.PurchasedBalance__c < 0 && request.BalanceState__c == 2)
            {
                request.Status__c = 'No Balance - Cant Quote';
                request.OwnerId = DID_NOT_QUOTE_Q_ID;
            }
            if (request.RecordTypeId == PRO_ASSIST_RECORD_TYPE_ID)
            {
                //PBC 2014-07-14: only do Encoded id parse and service lookup if they are non-null
                if ( String.isEmpty( request.EncodedServiceID__c )  ||  String.isEmpty( request.EncodedRequestID__c ) || String.isEmpty(request.EmailSendQuoteLink__c) )
                {
                    doRequestInfoParse(request, reqsByServiceIdMap);
                }
            }
        }
        List<Id> ids = new List<Id>();
        List<String> accIds = new List<String>();
        List<Decimal> userIDs = new List<Decimal>();
        for (Request__c r : newRequests)
        {
            ids.add(r.Service__c);
            r.LastSyncedWithDataPlatform__c = DateTime.now();


        }
        //system.debug('ids: '+ids);
        List<Service__c> servs = [Select Id,ProAccount__r.ContactBudget__c,ProAccount__r.usr_user_id__c FROM Service__c Where Id in:ids];
        system.debug('servs: ' + servs);
        //***************************************************************
        for (Service__c serv : servs)
        {
            accIds.add(serv.ProAccount__c);
            userIDs.add(serv.ProAccount__r.usr_user_id__c);
        }
        associateRequestToServiceByEncodedId(reqsByServiceIdMap);
    }

    public static void OnBeforeUpdate(Map<Id, Request__c> oldRequests, List<Request__c> updatedRequests)
    {
        List<String> accIds = new List<String>();
        system.debug('old: ' + oldRequests + ' // new: ' + updatedRequests);
        List<Decimal> userIds = new List<Decimal>();
        Map<String, List<Request__c>> reqsByServiceIdMap = new Map<String, List<Request__c>>();
        //*************** Added 4-6-2017-Scott Purcell-to include becky services
        List<Id> ids = new List<Id>();
        for (Request__c r : updatedRequests)
        {
            ids.add(r.Service__c);
            r.LastSyncedWithDataPlatform__c = DateTime.now();

        }

        List<Service__c> servs = [Select Id,ProAccount__r.ContactBudget__c,ProAccount__r.usr_user_id__c FROM Service__c Where Id in:ids];
        //***************************************************************
        for (Service__c serv : servs)
        {
            userIds.add(serv.ProAccount__r.usr_user_id__c);
        }
        //***************************************************************
        for (Request__c request : updatedRequests)
        {
            for (Service__c serv : servs)
            {
                if (serv.Id == request.Service__c)
                {
                    Request__c oldRequest = oldRequests.get(request.Id);
                    if (request.QuotingServiceStatus__c == 'Off')
                    {
                        request.Status__c = 'Pro Paused';
                    }
                    if (request.RecordTypeId == PRO_ASSIST_RECORD_TYPE_ID && request.EncodedServiceID__c != oldRequest.EncodedServiceID__c)
                    {
                        //PBC 2017-07-14, only do Encoded id parse and service lookup if they are non-null
                        if ( String.isEmpty( request.EncodedServiceID__c )  ||  String.isEmpty( request.EncodedRequestID__c ) || String.isEmpty(request.EmailSendQuoteLink__c) )
                        {
                            doRequestInfoParse(request, reqsByServiceIdMap);
                        }
                    }
                }
            }
        }
        for (Service__c serv : servs)
        {
            accIds.add(serv.ProAccount__c);
            userIDs.add(serv.ProAccount__r.usr_user_id__c);
        }
        associateRequestToServiceByEncodedId(reqsByServiceIdMap);
    }

    //PBC 2017-07-17, added to bind ProRequestsEmailService dependency (not re-invent the wheel)
    public static ProRequestsEmailService.TTServiceInfo doRequestInfoParse(Request__c request, Map<String, List<Request__c>> requestMap)
    {

        ProRequestsEmailService.TTServiceInfo serviceInfo;
        if (null != request && null != request.EmailHTMLBodyLong__c)
        {
            serviceInfo = ProRequestsEmailService.getServiceDetails(request.EmailHTMLBodyLong__c);
            if (null != serviceInfo)
            {
                request.EncodedServiceID__c = serviceInfo.encodedServiceId;
                request.EmailSendQuoteLinkPart1__c = serviceInfo.serviceUrl;
                request.EncodedRequestID__c = serviceInfo.requestId;
                request.EmailSendQuoteLink__c = serviceInfo.serviceUrl;
                request.UrlParms__c = serviceInfo.parmJSON;

                if (null == request.Service__c && String.isNotBlank(request.EncodedServiceID__c) && null != requestMap)
                {
                    List<Request__c> reqs = requestMap.get(request.EncodedServiceID__c);
                    reqs = (reqs == null) ? new List<Request__c>() : reqs;
                    reqs.add(request);
                    requestMap.put(request.EncodedServiceID__c, reqs);
                }
            }
        }
        return null == serviceInfo ? new ProRequestsEmailService.TTServiceInfo(NULL, NULL, NULL, NULL) : serviceInfo;
    }

    private static void associateRequestToServiceByEncodedId(Map<String, List<Request__c>> reqsByServiceIdMap)
    {
        //PBC 2017-07-16: created more null pointer exception resistance
        if (!reqsByServiceIdMap.isEmpty())
        {
            //loop services and requests accessible from reqByServiceIdMap, if any
            for (Service__c serv : [Select Id, EncodedServiceID__c From Service__c Where EncodedServiceID__c IN :reqsByServiceIdMap.keySet()])
            {
                //get child request from encoded Id map, if any
                List<Request__c> reqs = reqsByServiceIdMap.get(serv.EncodedServiceID__c);
                if (null != reqs)
                {
                    for (Request__c req : reqs)
                    {
                        // if each request matches the service's encoded service id and is not already set, 
                        // assign service parent id to request
                        if (null != req && null != req.Service__c)
                        {
                            req.Service__c = serv.Id;
                        }
                    }
                }
            }
        }
    }

}