metadata-classic/objects/Request__c.object
<CustomObject>
    <description>Custom object to store records pertaining to quoting service requests.  Records store parsed email data from the request email sent to the professional enrolled in quoting service.</description>
    <fields>
        <fullName>CreditBalance__c</fullName>
        <formula>IF(
NOT(ISBLANK(Service__c)), Service__r.ProAccount__r.CreditBalance__c,
NULL
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Credit Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>QuotingServiceStatus__c</fullName>
        <description>Formula field to bring over the quoting service status onto the Request record.  Used in list views and for process builder.</description>
        <formula>TEXT(Service__r.QuotingServiceStatus__c)</formula>
        <label>Quoting Service Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the Pro Assistant Profile (aka Service) record.</description>
        <label>Service</label>
        <referenceTo>Service__c</referenceTo>
        <relationshipLabel>Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Picklist whose values indicate the status of the request record.</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                    <default>true</default>
                    <label>New</label>
                </value>
                <value>
                    <fullName>Quoted</fullName>
                </value>
                <value>
                    <fullName>Passed</fullName>
                </value>
                <value>
                    <fullName>Forward (Sent to Pro)</fullName>
                </value>
                <value>
                    <fullName>No Action Needed</fullName>
                </value>
                <value>
                    <fullName>Pro Already Quoted</fullName>
                </value>
                <value>
                    <fullName>Pricing Calculator Error</fullName>
                </value>
                <value>
                    <fullName>Pro Paused</fullName>
                </value>
                <value>
                    <fullName>Max Contact Reached</fullName>
                </value>
                <value>
                    <fullName>DNQ In Pricing Calculator</fullName>
                </value>
                <value>
                    <fullName>No PC Template For Category</fullName>
                </value>
                <value>
                    <fullName>Expired/Inactive Request</fullName>
                </value>
                <value>
                    <fullName>No Credits - Cant Quote</fullName>
                </value>
                <value>
                    <fullName>No Balance - Cant Quote</fullName>
                </value>
                <value>
                    <fullName>Weekly Budget Limit Hit - Passed</fullName>
                </value>
                <value>
                    <fullName>Other - Passed</fullName>
                </value>
                <value>
                    <fullName>Negative Balance</fullName>
                </value>
                <value>
                    <fullName>No Related Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Request</label>
    <nameField>
        <label>Request Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/objects/Service__c.object
<CustomObject>
    <description>Custom object to store records pertaining to the Pro Assistant, Quoting Service, or Instant Quote Service profiles (e.g., is the Pro active in Quoting service).</description>
    <fields>
        <fullName>ProAccount__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Pro business/name the service is related to.</description>
        <inlineHelpText>The Pro business/name the service is related to.</inlineHelpText>
        <label>Pro Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Services</relationshipLabel>
        <relationshipName>Services</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAssistantSubscriptionType__c</fullName>
        <description>The subscription type the Pro has enrolled in.</description>
        <inlineHelpText>The subscription type the Pro has enrolled in.</inlineHelpText>
        <label>Subscription Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Instant Match</fullName>
                </value>
                <value>
                    <fullName>Instant Match and Quoting Service</fullName>
                </value>
                <value>
                    <fullName>Instant Match Early Enrollment</fullName>
                </value>
                <value>
                    <fullName>Quoting Service</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>QuotingServiceStatus__c</fullName>
        <label>Quoting Service Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ON</fullName>
                </value>
                <value>
                    <fullName>OFF</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date that the pro enrolled in the Pro Assistant program.</description>
        <inlineHelpText>Date that the pro enrolled in the Pro Assistant program.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>usr_email__c</fullName>
        <label>User Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>usr_first_name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>usr_last_name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Service</label>
    <nameField>
        <label>Service Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Services</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/RequestTriggerHandlerTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
******************************************************************************** 
https://thumbtack--dev.cs17.my.salesforce.com
  

Change List:
------------
Version    Date     Author            Description
=======+===========+=================+=================================
1.0     2016-12-06  Scott Purcell     Created
=======+===========+=================+=================================*/
@istest
public  class RequestTriggerHandlerTest {
    public static Account acc {get;set;}
    public static Service__c service {get;set;}
    public static Request__c request {get;set;}
    
    static testMethod void OnBeforeInsert()
    {
        User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        acc = new Account(
            Name='Chester Tester',
            Phone='8018675309',
            usr_first_name__c = 'Chester',
            usr_last_name__c = 'Tester',
            usr_email__c = 'chester@bogus.thumbtack.com',
            usr_user_id__c = -2,
            ContactsUsed__c = 850,
            ContactBudget__c = 10,
            CreditBalance__c = 2
            );
        insert acc;
        service = new Service__c(
            Name= 'test Service',
            ProAccount__c = acc.Id
            );
        insert service;
        request = new Request__c(
            Name ='Test Request',
            Status__c = 'New',
            Service__c = service.Id
            );
        System.runAs(testUser) 
        {
            Test.startTest();
                insert request;
            Test.stopTest();
        }
        Request__c r = [Select Id,Status__c From Request__c Where ID =:request.Id LIMIT 1];
        System.assertEquals('New',r.Status__c);
        system.debug('status: '+r.Status__c);
    }
   

    static testMethod void OnBeforeInsertNoCredits()
    {
        User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        acc = new Account(
            Name='Chester Tester',
            Phone='8018675309',
            usr_first_name__c = 'Chester',
            usr_last_name__c = 'Tester',
            usr_email__c = 'chester@bogus.thumbtack.com',
            usr_user_id__c = -2,
            ContactsUsed__c = 5,
            ContactBudget__c = 10,
            CreditBalance__c = -1
            );
        insert acc;
        service = new Service__c(
            Name= 'test Service',
            ProAccount__c = acc.Id,
            StartDate__c = Date.today().addDays(-16),
            ProAssistantSubscriptionType__c = 'Quoting Service'
            );
        insert service;
        request = new Request__c(
            Name ='Test Request',
            Status__c = 'New',
            Service__c = service.Id
            );
        System.runAs(testUser) 
        {
            Test.startTest();
                insert request;
            Test.stopTest();
        }
        Request__c r = [Select Id,Status__c From Request__c Where ID =:request.Id LIMIT 1];
        System.assertEquals('New',r.Status__c);
        system.debug('status: '+r.Status__c);
    }

    static testMethod void OnBeforeInsertProPAused()
    {
        User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        acc = new Account(
            Name='Chester Tester',
            Phone='8018675309',
            usr_first_name__c = 'Chester',
            usr_last_name__c = 'Tester',
            usr_email__c = 'chester@bogus.thumbtack.com',
            usr_user_id__c = -2,
            ContactsUsed__c = 850,
            ContactBudget__c = 10,
            CreditBalance__c = 0
            );
        insert acc;
        service = new Service__c(
            Name= 'test Service',
            ProAccount__c = acc.Id,
            QuotingServiceStatus__c = 'Off',
            StartDate__c = Date.today().addDays(-16)
            );
        insert service;
        request = new Request__c(
            Name ='Test Request',
            Status__c = 'New',
            Service__c = service.Id
            );
        System.runAs(testUser) 
        {
            Test.startTest();
                insert request;
            Test.stopTest();
        }
        Request__c r = [Select Id,Status__c From Request__c Where ID =:request.Id LIMIT 1];
        System.assertEquals('Pro Paused',r.Status__c);
        system.debug('status: '+r.Status__c);
    }


    static testMethod void OnBeforeUpdate()
    {
          User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        acc = new Account(
            Name='Chester Tester',
            Phone='8018675309',
            usr_first_name__c = 'Chester',
            usr_last_name__c = 'Tester',
            usr_email__c = 'chester@bogus.thumbtack.com',
            usr_user_id__c = -2,
            ContactsUsed__c = 850,
            ContactBudget__c = 10,
            CreditBalance__c = 2
            );
        insert acc;
        service = new Service__c(
            Name= 'test Service',
            ProAccount__c = acc.Id
            );
        insert service;
        request = new Request__c(
            Name ='Test Request',
            Service__c = service.Id,
            Status__c = 'New'
            );
        System.runAs(testUser) 
        {
            Test.startTest();
                insert request;
                update request;
            Test.stopTest();
        }

        List<Request__c> rs = [Select Id,Status__c From Request__c];
        
        for(Request__c s:rs)
        {
            system.debug('status: '+s.Status__c);
            System.assertEquals('New',s.Status__c);
        }
        
    }
    static testMethod void OnBeforeUpdateProPaused()
    {
          User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        acc = new Account(
            Name='Chester Tester',
            Phone='8018675309',
            usr_first_name__c = 'Chester',
            usr_last_name__c = 'Tester',
            usr_email__c = 'chester@bogus.thumbtack.com',
            usr_user_id__c = -2
            );
        insert acc;
        service = new Service__c(
            Name= 'test Service',

            ProAccount__c = acc.Id
            );
        insert service;
        request = new Request__c(
            Name ='Test Request',
            Service__c = service.Id,
            Status__c = 'New'
            );
        System.runAs(testUser) 
        {
            Test.startTest();
                insert request;
                acc.ContactsUsed__c = 850;
                acc.ContactBudget__c = 10;
                acc.CreditBalance__c = 2;
                service.QuotingServiceStatus__c = 'Off';
                update service;
                update acc;
                update request;
            Test.stopTest();
        }
        
        List<Request__c> rs = [Select Id,Status__c From Request__c];
        
        for(Request__c s:rs)
        {
            system.debug('status: '+s.Status__c);
        }
        
    }

}