metadata-classic/objects/RoutingProfile__c.object
<CustomObject>
    <description>Custom object that stores exceptional data for smart routing purposes (e.g., Top Pro goes to the front of the phone queue).</description>
    <fields>
        <fullName>CreditFisher__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Credit Fisher</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enterprise__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enterprise Sales</description>
        <label>Enterprise</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Experiment__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For experimental routing</description>
        <label>Experiment</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FrequentCaller__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Frequent Caller</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Routing Profiles</relationshipLabel>
        <relationshipName>RoutingProfiles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ProAssistOnboarding__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Instant Match Onboarding</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ThumbtackID__c</fullName>
        <description>The Thumbtack User ID of the pro/customer.</description>
        <externalId>true</externalId>
        <label>Thumbtack ID</label>
        <precision>11</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>TopPro__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Top Pro</label>
        <type>Checkbox</type>
    </fields>
    <label>Routing Profile</label>
    <nameField>
        <label>Routing Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Routing Profiles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/RoutingProfileTriggerHandler.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
********************************************************************************
Change List:
------------
Version    Date     Author            Description
=======+===========+=================+================================================
1.0     02-21-2017  Scott Purcell      Created-To replace Bug Report Update History process builder
1.1		3-23-2017   Scott Purcell      Created delete component for profiles that are all marked false
=======+===========+=================+================================================
*/
public with sharing class RoutingProfileTriggerHandler 
{
	public static void BeforeUpdate(List<RoutingProfile__c> profiles,List<RoutingProfile__c> oldProfiles,map<id,RoutingProfile__c> profilesMap)
	{
		List<Lead> leads = new List<Lead>();
		List<String> ids = new List<String>();
		for(RoutingProfile__c rp: profiles)
		{
            system.debug('rp.Lead__c: '+rp.Lead__c);
			if(rp.Lead__c != null)ids.add(rp.Lead__c);
		}
		system.debug('ids: '+ids);
		if(ids.size()>0)leads = [Select Id,ThumbtackID__c From Lead Where Id in :ids];
		system.debug('leads: '+leads);
		for(RoutingProfile__c profile : profiles)
		{
			for(Lead l:leads)
			{
				if(profile.Lead__c == l.Id && l.ThumbtackID__c != null)
				{
					profile.ThumbtackID__c = l.ThumbtackID__c;
					profile.updated__c = true;
				}
			}
			system.debug('profile: '+profile);
		}
	}
	public static void AfterUpdate(List<RoutingProfile__c> profiles) 
	{
		List<String>profilesToDelete = new List<String>();//Added 3/23/2107 -Scott Purcell
		for(RoutingProfile__c p : profiles)
		{
			if(p.CreditFisher__c == false && p.CustomerContact__c == false && p.Enterprise__c == false && p.Experiment__c == false && p.FrequentCaller__c == false && p.ProAssistant__c == false && p.ProAssistOnboarding__c == false && p.QuotingService__c == false && p.TopPro__c == false)
			{
				profilesToDelete.add(p.Id);
			}
		}
		delete [Select Id From RoutingProfile__c Where id IN :profilesToDelete];
	}
	
}