metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for work item</description>
        <inlineHelpText>Status for work item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banned Pro Re-entry</fullName>
                </value>
                <value>
                    <fullName>BGC Identity Mismatch</fullName>
                </value>
                <value>
                    <fullName>Chargeback Removal</fullName>
                </value>
                <value>
                    <fullName>Chargeback Warning</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Customer Payment Review</fullName>
                </value>
                <value>
                    <fullName>In Product Fraud Report</fullName>
                </value>
                <value>
                    <fullName>Low Quality to Remove</fullName>
                </value>
                <value>
                    <fullName>Messaging Verification</fullName>
                </value>
                <value>
                    <fullName>PA Request a Call Error</fullName>
                </value>
                <value>
                    <fullName>Review Message</fullName>
                </value>
                <value>
                    <fullName>Review Message for Spam</fullName>
                </value>
                <value>
                    <fullName>Verified Fake Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/WorkItemTransferControllerTest.cls
/*
  Copyright (c) 2017 Thumbtack. All rights reserved.

  Version      Date          Author            Description
  ========+============+=================+================================================
  1.0      2017-10-07   Mendel Guillaume       Created
  ========+============+=================+===============================================
*/

@IsTest
private class WorkItemTransferControllerTest
{
	@TestSetup
	static void createData()
	{
		User testUser = [SELECT Id FROM User WHERE Profile.Name = '*Customer Success - TSL' AND IsActive = true LIMIT 1];
		System.runAs(testUser)
		{
			Group lowIntent = [SELECT Id FROM Group WHERE Name = 'Low Intent Disputes' LIMIT 1];
			WorkItem__c item = new WorkItem__c(Type__c = 'BGC Identity Mismatch', Name = 'Wi1', Status__c = 'New',
					OwnerId = lowIntent.Id, RecordTypeId = WorkItemHelper.STANDARD_WORK_ITEM_RECORD_TYPE_ID);
			WorkItem__c item1 = new WorkItem__c(Name = 'Wi2', Status__c = 'New', OwnerId = lowIntent.Id,
					RecordTypeId = WorkItemHelper.BLACKLISTED_NUMBER_RECORD_TYPE_ID);
			insert new List<WorkItem__c>{item, item1};
		}
	}

	@IsTest
	static void testGetItems()
	{
		User testUser = [SELECT Id FROM User WHERE Profile.Name = '*Customer Success - TSL' AND IsActive = true LIMIT 1];
		System.runAs(testUser)
		{
			List<WorkItemTransferController.WorkItemGroup> groups = WorkItemTransferController.getWorkItemsByType();

			for (WorkItemTransferController.WorkItemGroup g : groups)
			{
				if (g.name == 'BGC Identity Mismatch')
				{
					System.assertEquals(1, g.count);
				}
				else
				{
					System.assertEquals(0, g.count);
				}
			}
		}
	}

	@IsTest
	static void testTakeItem()
	{
		User testUser = [SELECT Id FROM User WHERE Profile.Name = '*Customer Success - TSL' AND IsActive = true LIMIT 1];
		System.runAs(testUser)
		{
			WorkItem__c item = WorkItemTransferController.takeWorkItem('BGC Identity Mismatch');

			System.assertNotEquals(null, item);
		}
	}

	@IsTest
	static void testGetItemsRT()
	{
		User testUser = [SELECT Id FROM User WHERE Profile.Name = '*Customer Success - TSL' AND IsActive = true LIMIT 1];
		System.runAs(testUser)
		{
			List<WorkItemTransferController.WorkItemGroup> groups = WorkItemTransferController.getWorkItemsByRecordType();

			for (WorkItemTransferController.WorkItemGroup g : groups)
			{
				if (g.name == 'Blacklisted Number')
				{
					System.assertEquals(1, g.count);
				}
				else
				{
					System.assertEquals(0, g.count);
				}
			}
		}
	}

	@IsTest
	static void testTakeItemRT()
	{
		User testUser = [SELECT Id FROM User WHERE Profile.Name = '*Customer Success - TSL' AND IsActive = true LIMIT 1];
		System.runAs(testUser)
		{
			WorkItem__c item = WorkItemTransferController.takeWorkItemRT('Blacklisted Number');

			System.assertNotEquals(null, item);
		}
	}
}