metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>ReviewAudit__c</fullName>
        <label>Review Audit</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Concerning behavior</fullName>
                </value>
                <value>
                    <fullName>Deposit no-show</fullName>
                </value>
                <value>
                    <fullName>General dissatisfaction</fullName>
                </value>
                <value>
                    <fullName>Inappropriate physical contact</fullName>
                </value>
                <value>
                    <fullName>Insufficient info</fullName>
                </value>
                <value>
                    <fullName>No-show (unpaid)</fullName>
                </value>
                <value>
                    <fullName>Pricing concerns</fullName>
                </value>
                <value>
                    <fullName>Property damage</fullName>
                </value>
                <value>
                    <fullName>Stolen property</fullName>
                </value>
                <value>
                    <fullName>Text &amp; rating don’t match</fullName>
                </value>
                <value>
                    <fullName>Threats of or actual physical harm</fullName>
                </value>
                <value>
                    <fullName>Unprofessional</fullName>
                </value>
                <value>
                    <fullName>Unresolved unsatisfactory work</fullName>
                </value>
                <value>
                    <fullName>Work not complete</fullName>
                </value>
                <value>
                    <fullName>Open MTS Incident</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banned Pro Re-entry</fullName>
                </value>
                <value>
                    <fullName>BGC Identity Mismatch</fullName>
                </value>
                <value>
                    <fullName>Chargeback Removal</fullName>
                </value>
                <value>
                    <fullName>Chargeback Warning</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Customer Payment Review</fullName>
                </value>
                <value>
                    <fullName>In Product Fraud Report</fullName>
                </value>
                <value>
                    <fullName>Low Quality to Remove</fullName>
                </value>
                <value>
                    <fullName>Messaging Verification</fullName>
                </value>
                <value>
                    <fullName>PA Request a Call Error</fullName>
                </value>
                <value>
                    <fullName>Review Message</fullName>
                </value>
                <value>
                    <fullName>Review Message for Spam</fullName>
                </value>
                <value>
                    <fullName>Verified Fake Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rev_review_id__c</fullName>
        <externalId>true</externalId>
        <label>Review Id</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>External user ID field used for syncing done with Becquerel.</description>
        <externalId>true</externalId>
        <label>User ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/BeckyWorkItemSyncQueueableTest.cls
/*
   Copyright (c) 2017 Thumbtack, All rights reserved.

Change List:
------------
Version   Date         Author           Description
========+============+=================+================================================
1.0       10/17/17      jkennington          Created
========+============+=================+===============================================*/
@IsTest
private class BeckyWorkItemSyncQueueableTest
{
    @isTest
    private static void getConcerningReviewsWithWorkItemsFromBeckyTest()
    {

        Id rId = WorkItem__c.SObjectType.getDescribe().getRecordTypeInfosByName().get('Concerning Review').getRecordTypeId();
        WorkItem__c wi = new WorkItem__c(rev_review_id__c = 1234, RecordTypeId = rId, usr_user_id__c = TestUtilities.CUSTOMER_USER_PK_ID_INT, Name = 'testIsAfterInsert', Type__c = 'Blacklisted Number', ReviewAudit__c = 'No Action Needed');
        insert wi;
        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Test.startTest();
                new BeckyWorkItemSyncQueueable().execute(null);
            Test.stopTest();
            List<WorkItem__c> wi2 = [select Id From WorkItem__c];
            system.debug('wi2: ' + wi2);
            system.assert(wi2.size() == 1);
        }
    }

    @isTest
    private static void getConcerningReviewsWithNoWorkItemsFromBeckyTest()
    {
        TestUtilities.insertFourCoreThumbtackUsers();

        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Test.startTest();
                new ScheduledGetWorkItems().execute(NULL);
            Test.stopTest();

            List<WorkItem__c> wi2 = [select Id From WorkItem__c];
            system.debug('wi2: ' + wi2);
            system.assert(wi2.size() == 1);

        }

    }
}