metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>OwnerIsQueue__c</fullName>
        <description>True if owner is queue, false if owner is user</description>
        <formula>BEGINS(OwnerId,&quot;00G&quot;)</formula>
        <label>Owner Is Queue</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for work item</description>
        <inlineHelpText>Status for work item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banned Pro Re-entry</fullName>
                </value>
                <value>
                    <fullName>BGC Identity Mismatch</fullName>
                </value>
                <value>
                    <fullName>Chargeback Removal</fullName>
                </value>
                <value>
                    <fullName>Chargeback Warning</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Customer Payment Review</fullName>
                </value>
                <value>
                    <fullName>In Product Fraud Report</fullName>
                </value>
                <value>
                    <fullName>Low Quality to Remove</fullName>
                </value>
                <value>
                    <fullName>Messaging Verification</fullName>
                </value>
                <value>
                    <fullName>PA Request a Call Error</fullName>
                </value>
                <value>
                    <fullName>Review Message</fullName>
                </value>
                <value>
                    <fullName>Review Message for Spam</fullName>
                </value>
                <value>
                    <fullName>Verified Fake Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/WorkItemTransferController.cls
/*
  Copyright (c) 2017 Thumbtack. All rights reserved.

  Version      Date          Author            Description
  ========+============+=================+================================================
  1.0      2017-10-03   Mendel Guillaume       Created
  ========+============+=================+===============================================
*/

public with sharing class WorkItemTransferController
{
	@AuraEnabled
	public static List<WorkItemGroup> getWorkItemsByType()
	{
		AggregateResult[] ars = [SELECT Count(Id) items, Type__c
								FROM WorkItem__c
								WHERE Status__c != 'Completed' AND OwnerIsQueue__c = true AND Type__c != null
									 AND RecordTypeId = :WorkItemHelper.STANDARD_WORK_ITEM_RECORD_TYPE_ID
								GROUP BY Type__c];
		Map<String, WorkItemGroup> groupsMap = new Map<String, WorkItemGroup>();
		List<Schema.PicklistEntry> ples = WorkItem__c.Type__c.getDescribe().getPicklistValues();
		List<WorkItemGroup> groups = new List<WorkItemGroup>();

		for(AggregateResult ar : ars)
		{
			groupsMap.put((String)ar.get('Type__c'), new WorkItemGroup((String)ar.get('Type__c'), (Integer)ar.get('items')));
		}

		//Using picklist order
		for(Schema.PicklistEntry p : ples)
		{
			if (!groupsMap.containsKey(p.getValue()))
			{
				groups.add(new WorkItemGroup(p.getValue(), 0));
			}
			else
			{
				groups.add(groupsMap.get(p.getValue()));
			}
		}

		return groups;
	}

	@AuraEnabled
	public static List<WorkItemGroup> getWorkItemsByRecordType()
	{
		AggregateResult[] ars = [SELECT Count(Id) items, RecordType.Name rt
									FROM WorkItem__c
									WHERE Status__c != 'Completed' AND OwnerIsQueue__c = true
										AND (RecordTypeId = :WorkItemHelper.BLACKLISTED_NUMBER_RECORD_TYPE_ID OR
												RecordTypeId = :WorkItemHelper.CONCERNING_REVIEW_RECORD_TYPE_ID)
									GROUP BY RecordType.Name];
		Map<String, WorkItemGroup> groupsMap = new Map<String, WorkItemGroup>();
		List<Schema.PicklistEntry> ples = WorkItem__c.Type__c.getDescribe().getPicklistValues();
		List<WorkItemGroup> groups = new List<WorkItemGroup>();

		for(AggregateResult ar : ars)
		{
			groupsMap.put((String)ar.get('rt'), new WorkItemGroup((String)ar.get('rt'), (Integer)ar.get('items')));
		}

		if(groupsMap.containsKey('Blacklisted Number'))
		{
			groups.add(groupsMap.get('Blacklisted Number'));
		}
		else
		{
			groups.add(new WorkItemGroup('Blacklisted Number', 0));
		}

		if(groupsMap.containsKey('Concerning Review'))
		{
			groups.add(groupsMap.get('Concerning Review'));
		}
		else
		{
			groups.add(new WorkItemGroup('Concerning Review', 0));
		}

		return groups;
	}

	@AuraEnabled
	public static WorkItem__c takeWorkItem(String type)
	{
		List<WorkItem__c> items = [SELECT Id, Name FROM WorkItem__c
									WHERE Type__c = :type  AND Status__c != 'Completed' AND OwnerIsQueue__c = true
									ORDER BY CreatedDate ASC LIMIT 1];
		WorkItem__c wi = null;

		if(!items.isEmpty())
		{
			wi = items[0];
			wi.OwnerId = UserInfo.getUserId();
			update wi;
		}

		return wi;
	}

	@AuraEnabled
	public static WorkItem__c takeWorkItemRT(String recordTypeName)
	{
		List<WorkItem__c> items = [SELECT Id, Name FROM WorkItem__c
									WHERE RecordType.Name = :recordTypeName  AND Status__c != 'Completed' AND OwnerIsQueue__c = true
									ORDER BY CreatedDate ASC LIMIT 1];
		WorkItem__c wi = null;

		if(!items.isEmpty())
		{
			wi = items[0];
			wi.OwnerId = UserInfo.getUserId();
			update wi;
		}

		return wi;
	}

	public class WorkItemGroup
	{
		@AuraEnabled
		public String name{get;set;}

		@AuraEnabled
		public Integer count{get;set;}

		public WorkItemGroup(String name, Integer count)
		{
			this.name = name;
			this.count = count;
		}
	}
}