metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>BidId__c</fullName>
        <label>Bid ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Details__c</fullName>
        <label>Details</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for work item</description>
        <inlineHelpText>Status for work item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banned Pro Re-entry</fullName>
                </value>
                <value>
                    <fullName>BGC Identity Mismatch</fullName>
                </value>
                <value>
                    <fullName>Chargeback Removal</fullName>
                </value>
                <value>
                    <fullName>Chargeback Warning</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Customer Payment Review</fullName>
                </value>
                <value>
                    <fullName>In Product Fraud Report</fullName>
                </value>
                <value>
                    <fullName>Low Quality to Remove</fullName>
                </value>
                <value>
                    <fullName>Messaging Verification</fullName>
                </value>
                <value>
                    <fullName>PA Request a Call Error</fullName>
                </value>
                <value>
                    <fullName>Review Message</fullName>
                </value>
                <value>
                    <fullName>Review Message for Spam</fullName>
                </value>
                <value>
                    <fullName>Verified Fake Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>External user ID field used for syncing done with Becquerel.</description>
        <externalId>true</externalId>
        <label>User ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/RESTWorkItemTest.cls
/*
   Copyright (c) 2017 Thumbtack, All rights reserved.

Change List:
------------
Version   Date         Author           Description
========+============+=================+================================================
1.0       10/18/17      jkennington          Created
========+============+=================+===============================================*/
@IsTest
private class RESTWorkItemTest
{
    @IsTest
    static void doPostTest()
    {

        WorkItem__c wi = new WorkItem__c(Name = 'Review Message for Intent', CreatedDate = Date.today().addDays(-8), RecordTypeId = '01231000000y2AlAAI', BidId__c = '74t2kfgj', Details__c = 'TT Test Details', Priority__c = 'Medium', Status__c = 'New', Type__c = 'Concerning Review', usr_user_id__c = 12345);
        WorkItem__c wi2 = new WorkItem__c(Name = 'Review', RecordTypeId = '01231000000y2AlAAI', BidId__c = '74t2kfgj', Details__c = 'TT Test Details', Priority__c = 'High', Status__c = 'New', Type__c = 'Concerning Review', usr_user_id__c = 12345);
        WorkItem__c wi3 = new WorkItem__c(Name = 'Review', RecordTypeId = '01231000000y2AlAAI', BidId__c = '74t2kfgj', Details__c = 'TT Test Details', Priority__c = 'High', Status__c = 'New', Type__c = 'Concerning Review', usr_user_id__c = 12345);

        System.runAs(TestUtilities.USER_TACK_BOT)
        {
            Test.startTest();
            RESTWorkItemController.doPost(wi);
            RESTWorkItemController.doPost(wi2);
            System.assertEquals([SELECT Count() FROM WorkItem__c WHERE usr_user_id__c = 12345 AND RecordTypeId = :wi.RecordTypeId], 2, 'Did not create second record');
            Test.stopTest();

            RESTWorkItemController.doPost(wi3);
        }
        System.assertEquals([SELECT Count() FROM WorkItem__c WHERE usr_user_id__c = 12345  AND RecordTypeId = :wi.RecordTypeId], 2, 'Did not update record');
        System.assertEquals([SELECT Priority__c FROM WorkItem__c WHERE usr_user_id__c = 12345 AND CreatedDate > :Date.today().addDays(-7) AND RecordTypeId = :wi2.RecordTypeId LIMIT 1][0].Priority__c, 'High', 'Record not updated');
    }
}