metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banned Pro Re-entry</fullName>
                </value>
                <value>
                    <fullName>BGC Identity Mismatch</fullName>
                </value>
                <value>
                    <fullName>Chargeback Removal</fullName>
                </value>
                <value>
                    <fullName>Chargeback Warning</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Customer Payment Review</fullName>
                </value>
                <value>
                    <fullName>In Product Fraud Report</fullName>
                </value>
                <value>
                    <fullName>Low Quality to Remove</fullName>
                </value>
                <value>
                    <fullName>Messaging Verification</fullName>
                </value>
                <value>
                    <fullName>PA Request a Call Error</fullName>
                </value>
                <value>
                    <fullName>Review Message</fullName>
                </value>
                <value>
                    <fullName>Review Message for Spam</fullName>
                </value>
                <value>
                    <fullName>Verified Fake Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rev_usr_user_id_reviewed__c</fullName>
        <label>User Id Reviewed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>External user ID field used for syncing done with Becquerel.</description>
        <externalId>true</externalId>
        <label>User ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/DeleteBlacklisted.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
******************************************************************************** 

Change List:
------------
Version      Date          Author            Description
========+============+=================+================================================
1.0       04/04/2017     Scott Purcell          Created
========+============+=================+===============================================*/

public with sharing class DeleteBlacklisted {
	
    public static void blacklisted()
    {
        List<WorkItem__c> nids = new List<WorkItem__c>();
        List<Decimal> userIds = new List<Decimal>();
        List<String> workItemIds = new List<String>();
        List<WorkItem__c> wiList = [Select Id,Type__c,rev_usr_user_id_reviewed__c,usr_user_id__c From WorkItem__c Where Type__c =:'Blacklisted Number'];
        for(WorkItem__c wi: wiList)
        {
            userIds.add(wi.rev_usr_user_id_reviewed__c);
        }
        List<Account> accSet = [Select Name,Id,WhiteListed__c,usr_user_id__c From Account Where WhiteListed__c =:true AND usr_user_id__c IN: userIds];
        system.debug('workItemIds: '+workItemIds);
        system.debug('accSet.size(): '+accSet.size());
        
        for(Account acc:accSet)
        {
            for(WorkItem__c wi: wiList)
            {
                if(wi.Type__c == 'Blacklisted Number' && wi.rev_usr_user_id_reviewed__c == acc.usr_user_id__c)
                    nids.add(wi);
            }
        }
        system.debug('deletelist: '+nids.size());
        if(nids.size()>0)
        {
            delete nids;
            system.debug('deletelist: successfully deleted');
        }
    }
}