metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Banned Pro Re-entry</fullName>
                </value>
                <value>
                    <fullName>BGC Identity Mismatch</fullName>
                </value>
                <value>
                    <fullName>Chargeback Removal</fullName>
                </value>
                <value>
                    <fullName>Chargeback Warning</fullName>
                </value>
                <value>
                    <fullName>Customer Contact Dispute</fullName>
                </value>
                <value>
                    <fullName>Customer Payment Review</fullName>
                </value>
                <value>
                    <fullName>In Product Fraud Report</fullName>
                </value>
                <value>
                    <fullName>Low Quality to Remove</fullName>
                </value>
                <value>
                    <fullName>Messaging Verification</fullName>
                </value>
                <value>
                    <fullName>PA Request a Call Error</fullName>
                </value>
                <value>
                    <fullName>Review Message</fullName>
                </value>
                <value>
                    <fullName>Review Message for Spam</fullName>
                </value>
                <value>
                    <fullName>Verified Fake Reviews</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>rev_usr_user_id_reviewed__c</fullName>
        <label>User Id Reviewed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>External user ID field used for syncing done with Becquerel.</description>
        <externalId>true</externalId>
        <label>User ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-classic/classes/DeleteBlacklistedTest.cls
/*******************************************************************************
*                                                                              *
*                                           ########                           *
*                                            #####                             *
*    Copyright (c) 2016 Thumbtack            ###                               *
*       All rights reserved.                ###                                *
*                                         #####                                *
*                                      #########                               *
*                                         #                                    *
*                                        #                                     *
*                                       #                                      *
*                                      #                                       *
*                                                                              *
******************************************************************************** 

Change List:
------------
Version      Date          Author            Description
========+============+=================+================================================
1.0       04/04/2017     Scott Purcell          Created
========+============+=================+===============================================*/
@isTest
public with sharing class DeleteBlacklistedTest {
	 @isTest static void  deleteBlacklistedTest1()
	{
		
        User testUser = [SELECT Id,Name FROM User WHERE UserName LIKE 'salesforceintegration@thumbtack.com%' AND IsActive=true LIMIT 1];
        String Username = 'System Integration';
        
        System.runAs(testUser) 
        {
            WorkItem__c w = new WorkItem__c();
			w.rev_usr_user_id_reviewed__c = 1234;
			w.Type__c ='Blacklisted Number';
			insert w;

			Account acc = new Account(
            Name='Chester Tester',
            Phone='8018675309',
            usr_first_name__c = 'Chester',
            usr_last_name__c = 'Tester',
            usr_email__c = 'chester@bogus.thumbtack.com',
            usr_user_id__c = 1234,
            WhiteListed__c = true
            );
            insert acc;
         
            Test.startTest();
            	DeleteBlacklisted.Blacklisted();
            
            Test.stopTest();
            List<WorkItem__c> wiList = [Select Id From WorkItem__c];
            system.debug(wiList.size());
            system.assertEquals(0,wiList.size());
		}
	}
}