metadata-classic/objects/WorkItem__c.object
<CustomObject>
    <description>Custom object used to store records for incoming tasks from product allowing end user to review and update outcome of the action completed.</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for work item</description>
        <inlineHelpText>Status for work item</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Assigned</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>usr_user_id__c</fullName>
        <description>External user ID field used for syncing done with Becquerel.</description>
        <externalId>true</externalId>
        <label>User ID</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Work Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Work Items</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

metadata-sfdx/force-app/main/default/classes/RESTWorkItemController.cls
/*
   Copyright (c) 2017 Thumbtack, All rights reserved.

Change List:
------------
Version   Date         Author           Description
========+============+=================+================================================
1.0       10/11/17      jkennington          Created
========+============+=================+===============================================*/
@RestResource(urlMapping='/V1/WorkItem/*')
global with sharing class RESTWorkItemController
{
    @HttpPost
    global static void doPost(WorkItem__c workItem)
    {
        try
        {
            for (WorkItem__c wi : [SELECT Id, RecordTypeId, Status__c FROM WorkItem__c WHERE CreatedDate > :Date.today().addDays(-7) AND usr_user_id__c = :workItem.usr_user_id__c])
            {
                if(wi.RecordTypeId == workItem.RecordTypeId)
                {
                    System.debug('***** setId');
                    workItem.Id = wi.Id;
                }
            }

            upsert workItem;
        }
        catch(DMLException e)
        {
            System.debug(LoggingLevel.ERROR, e);
        }
    }
}